:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),1).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),2).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),3).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',hallway)]),4).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',bathroom)]),5).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',hallway)]),6).
happensAt(frame('Giving',[fe('Owner',mary),fe('Theme',apple),fe('Recipient',fred)]),7).
happensAt(frame('Giving',[fe('Owner',fred),fe('Theme',apple),fe('Recipient',mary)]),8).
q(9,Answer) :- questionedAt(frame('Giving',[fe('Owner',Answer),fe('Theme',apple),fe('Recipient',_)]),9).
happensAt(frame('Giving',[fe('Owner',mary),fe('Theme',apple),fe('Recipient',fred)]),10).
happensAt(frame('Obtain',[fe('Person',fred),fe('Theme',football)]),11).
q(12,Answer) :- questionedAt(frame('Giving',[fe('Owner',mary),fe('Theme',apple),fe('Recipient',Answer)]),12).
happensAt(frame('Discard',[fe('Person',fred),fe('Theme',football)]),13).
happensAt(frame('Discard',[fe('Person',fred),fe('Theme',apple)]),14).
q(15,Answer) :- questionedAt(frame('Giving',[fe('Owner',_),fe('Theme',apple),fe('Recipient',Answer)]),15).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',office)]),16).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',hallway)]),17).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),18).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),19).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',bedroom)]),20).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),22).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',garden)]),23).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',office)]),24).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),25).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',bedroom)]),26).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',garden)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),28).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',hallway)]),29).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),31).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',bedroom)]),32).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',hallway)]),33).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),34).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',bedroom)]),35).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',kitchen)]),36).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',kitchen)]),37).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',kitchen)]),38).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',bathroom)]),39).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),40).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',hallway)]),41).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',hallway)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),43).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),46).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',garden)]),47).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),49).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',office)]),50).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',garden)]),51).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',bathroom)]),52).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',hallway)]),53).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',hallway)]),54).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',office)]),55).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',kitchen)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),58).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),59).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',garden)]),60).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',garden)]),61).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',bedroom)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),63).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',hallway)]),64).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',hallway)]),65).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',bathroom)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),67).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',office)]),68).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',kitchen)]),69).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',kitchen)]),70).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',office)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),72).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',garden)]),73).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),74).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',kitchen)]),75).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),77).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',garden)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),79).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',bathroom)]),80).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),81).
happensAt(frame('Obtain',[fe('Person',bill),fe('Theme',football)]),82).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',office)]),83).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',garden)]),84).
happensAt(frame('Discard',[fe('Person',bill),fe('Theme',football)]),85).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',hallway)]),86).
happensAt(frame('Obtain',[fe('Person',bill),fe('Theme',football)]),87).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',bedroom)]),88).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),89).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',garden)]),90).
happensAt(frame('Travel',[fe('Person',bill),fe('Place',bathroom)]),91).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',office)]),92).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',office)]),93).
happensAt(frame('Travel',[fe('Person',fred),fe('Place',hallway)]),94).
happensAt(frame('Giving',[fe('Owner',bill),fe('Theme',football),fe('Recipient',mary)]),95).
q(96,Answer) :- questionedAt(frame('Giving',[fe('Owner',_),fe('Theme',football),fe('Recipient',Answer)]),96).
happensAt(frame('Travel',[fe('Person',jeff),fe('Place',kitchen)]),97).
happensAt(frame('Obtain',[fe('Person',bill),fe('Theme',milk)]),98).
q(99,Answer) :- questionedAt(frame('Giving',[fe('Owner',Answer),fe('Theme',football),fe('Recipient',_)]),99).
