:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),1).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),8).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),14).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),15).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),16).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),17).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),18).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),21).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),23).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),24).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),25).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),26).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),28).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),29).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),30).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),31).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),34).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),35).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),39).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),40).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),42).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),46).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),48).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),49).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),50).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),52).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),53).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),54).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),55).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),58).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),59).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),60).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),61).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),64).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),67).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),68).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),69).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),70).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),72).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),74).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),75).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),78).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),79).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),80).
q(81,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer)]),81).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),82).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),83).
q(84,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer)]),84).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),85).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),86).
q(87,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer)]),87).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),88).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),89).
q(90,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer)]),90).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),91).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),92).
q(93,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer)]),93).
