:- dynamic(learned_sentence/6).

learned_sentence('A person goes to a place.',index(1,3),'Travel',[pair('Person',index(1,2),required),pair('Place',index(1,6),required)],['travel','journey','move'],lvp('go','Travel',[pair('Person',index(1,2),[nsubj],required),pair('Place',index(1,6),[obl_to],required)])).
learned_sentence('A person got something.',index(2,3),'Obtain',[pair('Person',index(2,2),required),pair('Theme',index(2,4),required)],['grab','take','pick_up'],lvp('get','Obtain',[pair('Person',index(2,2),[nsubj],required),pair('Theme',index(2,4),[obj],required)])).
learned_sentence('A person dropped something.',index(3,3),'Discard',[pair('Person',index(3,2),required),pair('Theme',index(3,4),required)],['discard','leave','put_down'],lvp('drop','Discard',[pair('Person',index(3,2),[nsubj],required),pair('Theme',index(3,4),[obj],required)])).
learned_sentence('Where is a thing before a place?',index(4,1),'Located',[pair('Entity',index(4,4),required),pair('Place',index(4,1),required),pair('Before_place',index(4,7),required)],[],lvp('where','Located',[pair('Entity',index(4,4),[nsubj],required),pair('Place',index(4,1),[self],required),pair('Before_place',index(4,7),[obl_before],required)])).
learned_sentence('A person holds a thing.',index(5,3),'Hold',[pair('Person',index(5,2),required),pair('Theme',index(5,5),required)],[],lvp('hold','Hold',[pair('Person',index(5,2),[nsubj],required),pair('Theme',index(5,5),[obj],required)])).
learned_sentence('A thing is located in a place.',index(6,4),'Located',[pair('Entity',index(6,2),required),pair('Place',index(6,7),required)],[],lvp('locate','Located',[pair('Entity',index(6,2),[obj],required),pair('Place',index(6,7),[obl_in],required)])).
learned_sentence('A thing is located in a place.',index(6,4),'Located',[pair('Entity',index(6,2),required),pair('Place',index(6,7),required)],[],lvp('located','Located',[pair('Entity',index(6,2),[nsubj],required),pair('Place',index(6,7),[obl_in],required)])).
learned_sentence('A thing is located in a place before another place.',index(7,4),'Located',[pair('Entity',index(7,2),required),pair('Place',index(7,7),required),pair('Before_place',index(7,10),required)],[],lvp('locate','Located',[pair('Entity',index(7,2),[obj],required),pair('Place',index(7,7),[obl_in],required),pair('Before_place',index(7,10),[obl_before],required)])).
learned_sentence('A thing is located in a place before another place.',index(7,4),'Located',[pair('Entity',index(7,2),required),pair('Place',index(7,7),required),pair('Before_place',index(7,10),required)],[],lvp('located','Located',[pair('Entity',index(7,2),[nsubj],required),pair('Place',index(7,7),[obl_in],required),pair('Before_place',index(7,10),[obl_before],required)])).
learned_sentence('Where is the milk before bedroom?',index(8,1),'Located',[pair('Entity',index(8,4),required),pair('Place',index(8,1),required),pair('Before_place',index(8,6),required)],[],lvp('where','Located',[pair('Entity',index(8,4),[nsubj],required),pair('Place',index(8,1),[self],required),pair('Before_place',index(8,6),[nsubj,obl_before],required)])).
