:- dynamic(learned_sentence/6).

learned_sentence('A place is north of a place.',index(1,4),'North_of',[pair('Entity1',index(1,2),required),pair('Entity2',index(1,7),required)],[],lvp('north','North_of',[pair('Entity1',index(1,2),[nsubj],required),pair('Entity2',index(1,7),[obl_of],required)])).
learned_sentence('A place is south of a place.',index(2,4),'South_of',[pair('Entity1',index(2,2),required),pair('Entity2',index(2,7),required)],[],lvp('south','South_of',[pair('Entity1',index(2,2),[nsubj],required),pair('Entity2',index(2,7),[obl_of],required)])).
learned_sentence('A place is east of a place.',index(3,4),'East_of',[pair('Entity1',index(3,2),required),pair('Entity2',index(3,7),required)],[],lvp('east','East_of',[pair('Entity1',index(3,2),[nsubj],required),pair('Entity2',index(3,7),[obl_of],required)])).
learned_sentence('A place is west of a place.',index(4,4),'West_of',[pair('Entity1',index(4,2),required),pair('Entity2',index(4,7),required)],[],lvp('west','West_of',[pair('Entity1',index(4,2),[nsubj],required),pair('Entity2',index(4,7),[obl_of],required)])).
learned_sentence('What is the location north of?',index(5,5),'North_of',[pair('Entity1',index(5,4),required),pair('Entity2',index(5,1),required)],[],lvp('north','North_of',[pair('Entity1',index(5,4),[domvda,nsubj],required),pair('Entity2',index(5,1),[domvda],required)])).
learned_sentence('What is the location south of?',index(6,5),'South_of',[pair('Entity1',index(6,4),required),pair('Entity2',index(6,1),required)],[],lvp('south','South_of',[pair('Entity1',index(6,4),[domvda,nsubj],required),pair('Entity2',index(6,1),[domvda],required)])).
learned_sentence('What is the location east of?',index(7,5),'East_of',[pair('Entity1',index(7,4),required),pair('Entity2',index(7,1),required)],[],lvp('east','East_of',[pair('Entity1',index(7,4),[domvda,nsubj],required),pair('Entity2',index(7,1),[domvda],required)])).
learned_sentence('What is the location west of?',index(8,5),'West_of',[pair('Entity1',index(8,4),required),pair('Entity2',index(8,1),required)],[],lvp('west','West_of',[pair('Entity1',index(8,4),[domvda,nsubj],required),pair('Entity2',index(8,1),[domvda],required)])).
learned_sentence('What is the kitchen north of?',index(9,5),'North_of',[pair('Entity1',index(9,4),required),pair('Entity2',index(9,1),required)],[],lvp('north','North_of',[pair('Entity1',index(9,4),[domvda],required),pair('Entity2',index(9,1),[domvda,jbusn],required)])).
learned_sentence('What is the kitchen south of?',index(10,5),'South_of',[pair('Entity1',index(10,4),required),pair('Entity2',index(10,1),required)],[],lvp('south','South_of',[pair('Entity1',index(10,4),[domvda,nsubj],required),pair('Entity2',index(10,1),[domvda],required)])).
learned_sentence('What is the kitchen east of?',index(11,5),'East_of',[pair('Entity1',index(11,4),required),pair('Entity2',index(11,1),required)],[],lvp('east','East_of',[pair('Entity1',index(11,4),[compound],required),pair('Entity2',index(11,1),[jbusn],required)])).
learned_sentence('What is the kitchen west of?',index(12,5),'West_of',[pair('Entity1',index(12,4),required),pair('Entity2',index(12,1),required)],[],lvp('west','West_of',[pair('Entity1',index(12,4),[domvda,nsubj],required),pair('Entity2',index(12,1),[domvda],required)])).
learned_sentence('What is the office west of?',index(13,5),'West_of',[pair('Entity1',index(13,4),required),pair('Entity2',index(13,1),required)],[],lvp('west','West_of',[pair('Entity1',index(13,4),[domvda],required),pair('Entity2',index(13,1),[domvda,jbusn],required)])).
learned_sentence('What is north of the garden?',index(14,3),'North_of',[pair('Entity1',index(14,1),required),pair('Entity2',index(14,6),required)],[],lvp('north','North_of',[pair('Entity1',index(14,1),[nsubj],required),pair('Entity2',index(14,6),[obl_of],required)])).
learned_sentence('What is south of the garden?',index(15,3),'South_of',[pair('Entity1',index(15,1),required),pair('Entity2',index(15,6),required)],[],lvp('south','South_of',[pair('Entity1',index(15,1),[nsubj],required),pair('Entity2',index(15,6),[obl_of],required)])).
learned_sentence('What is west of the garden?',index(16,3),'West_of',[pair('Entity1',index(16,1),required),pair('Entity2',index(16,6),required)],[],lvp('west','West_of',[pair('Entity1',index(16,1),[nsubj],required),pair('Entity2',index(16,6),[obl_of],required)])).
