:- dynamic(learned_sentence/6).

learned_sentence('John works as a salesman on a program at IBM in sales in London.',index(1,2),'Being_employed',[pair('Employee',index(1,1),required),pair('Employer',index(1,10),optional),pair('Place',index(1,14),optional),pair('Field',index(1,12),optional),pair('Position',index(1,5),optional),pair('Task',index(1,8),optional)],[],lvp('work','Being_employed',[pair('Employee',index(1,1),[nsubj],required),pair('Employer',index(1,10),[obl_at],optional),pair('Place',index(1,14),[obl_in],optional),pair('Field',index(1,12),[obl_in],optional),pair('Position',index(1,5),[obl_as],optional),pair('Task',index(1,8),[obl_on],optional)])).
learned_sentence('John works as a salesman on a program for IBM in sales in London.',index(2,2),'Being_employed',[pair('Employee',index(2,1),required),pair('Employer',index(2,10),optional),pair('Place',index(2,14),optional),pair('Field',index(2,12),optional),pair('Position',index(2,5),optional),pair('Task',index(2,8),optional)],[],lvp('work','Being_employed',[pair('Employee',index(2,1),[nsubj],required),pair('Employer',index(2,10),[obl_for],optional),pair('Place',index(2,14),[obl_in],optional),pair('Field',index(2,12),[obl_in],optional),pair('Position',index(2,5),[obl_as],optional),pair('Task',index(2,8),[obl_on],optional)])).
learned_sentence('John works as a salesman on a program in a company in sales in London.',index(3,2),'Being_employed',[pair('Employee',index(3,1),required),pair('Employer',index(3,11),optional),pair('Place',index(3,15),optional),pair('Field',index(3,13),optional),pair('Position',index(3,5),optional),pair('Task',index(3,8),optional)],[],lvp('work','Being_employed',[pair('Employee',index(3,1),[nsubj],required),pair('Employer',index(3,11),[obl_in],optional),pair('Place',index(3,15),[obl_in],optional),pair('Field',index(3,13),[obl_in],optional),pair('Position',index(3,5),[obl_as],optional),pair('Task',index(3,8),[obl_on],optional)])).
learned_sentence('John works as a salesman on a program in a company in sales at AEOI.',index(4,2),'Being_employed',[pair('Employee',index(4,1),required),pair('Employer',index(4,11),optional),pair('Place',index(4,15),optional),pair('Field',index(4,13),optional),pair('Position',index(4,5),optional),pair('Task',index(4,8),optional)],[],lvp('work','Being_employed',[pair('Employee',index(4,1),[nsubj],required),pair('Employer',index(4,11),[obl_in],optional),pair('Place',index(4,15),[obl_at],optional),pair('Field',index(4,13),[obl_in],optional),pair('Position',index(4,5),[obl_as],optional),pair('Task',index(4,8),[obl_on],optional)])).
learned_sentence('John has a salesman job in a company in sales in London.',index(5,5),'Being_employed',[pair('Employee',index(5,1),required),pair('Employer',index(5,8),optional),pair('Place',index(5,12),optional),pair('Field',index(5,10),optional),pair('Position',index(5,4),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(5,1),[jbo,nsubj],required),pair('Employer',index(5,8),[jbo,obl_in],optional),pair('Place',index(5,12),[jbo,obl_in],optional),pair('Field',index(5,10),[jbo,obl_in],optional),pair('Position',index(5,4),[compound],optional)])).
learned_sentence('John has a salesman job with an institute in sales in London.',index(6,5),'Being_employed',[pair('Employee',index(6,1),required),pair('Employer',index(6,8),optional),pair('Place',index(6,12),optional),pair('Field',index(6,10),optional),pair('Position',index(6,4),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(6,1),[jbo,nsubj],required),pair('Employer',index(6,8),[jbo,obl_with],optional),pair('Place',index(6,12),[jbo,obl_in],optional),pair('Field',index(6,10),[jbo,obl_in],optional),pair('Position',index(6,4),[compound],optional)])).
learned_sentence('John has a salesman job at IBM in sales in London.',index(7,5),'Being_employed',[pair('Employee',index(7,1),required),pair('Employer',index(7,7),optional),pair('Place',index(7,11),optional),pair('Field',index(7,9),optional),pair('Position',index(7,4),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(7,1),[jbo,nsubj],required),pair('Employer',index(7,7),[jbo,obl_at],optional),pair('Place',index(7,11),[jbo,obl_in],optional),pair('Field',index(7,9),[jbo,obl_in],optional),pair('Position',index(7,4),[compound],optional)])).
learned_sentence('John has a salesman job in a company in sales at AEOI.',index(8,5),'Being_employed',[pair('Employee',index(8,1),required),pair('Employer',index(8,8),optional),pair('Place',index(8,12),optional),pair('Field',index(8,10),optional),pair('Position',index(8,4),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(8,1),[jbo,nsubj],required),pair('Employer',index(8,8),[jbo,obl_in],optional),pair('Place',index(8,12),[jbo,obl_at],optional),pair('Field',index(8,10),[jbo,obl_in],optional),pair('Position',index(8,4),[compound],optional)])).
learned_sentence('John has a salesman job with an institute in sales at AEOI.',index(9,5),'Being_employed',[pair('Employee',index(9,1),required),pair('Employer',index(9,8),optional),pair('Place',index(9,12),optional),pair('Field',index(9,10),optional),pair('Position',index(9,4),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(9,1),[jbo,nsubj],required),pair('Employer',index(9,8),[jbo,obl_with],optional),pair('Place',index(9,12),[jbo,obl_at],optional),pair('Field',index(9,10),[jbo,obl_in],optional),pair('Position',index(9,4),[compound],optional)])).
learned_sentence('John has a salesman job at IBM in sales at AEOI.',index(10,5),'Being_employed',[pair('Employee',index(10,1),required),pair('Employer',index(10,7),optional),pair('Place',index(10,11),optional),pair('Field',index(10,9),optional),pair('Position',index(10,4),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(10,1),[jbo,nsubj],required),pair('Employer',index(10,7),[jbo,obl_at],optional),pair('Place',index(10,11),[jbo,obl_at],optional),pair('Field',index(10,9),[jbo,obl_in],optional),pair('Position',index(10,4),[compound],optional)])).
learned_sentence('John has the job of a salesman in a company in sales in London.',index(11,4),'Being_employed',[pair('Employee',index(11,1),required),pair('Employer',index(11,10),optional),pair('Place',index(11,14),optional),pair('Field',index(11,12),optional),pair('Position',index(11,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(11,1),[jbo,nsubj],required),pair('Employer',index(11,10),[jbo,obl_in],optional),pair('Place',index(11,14),[jbo,obl_in],optional),pair('Field',index(11,12),[jbo,obl_in],optional),pair('Position',index(11,7),[nmod_of],optional)])).
learned_sentence('John has the job of a salesman with an institute in sales in London.',index(12,4),'Being_employed',[pair('Employee',index(12,1),required),pair('Employer',index(12,10),optional),pair('Place',index(12,14),optional),pair('Field',index(12,12),optional),pair('Position',index(12,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(12,1),[jbo,nsubj],required),pair('Employer',index(12,10),[jbo,obl_with],optional),pair('Place',index(12,14),[jbo,obl_in],optional),pair('Field',index(12,12),[jbo,obl_in],optional),pair('Position',index(12,7),[nmod_of],optional)])).
learned_sentence('John has the job of a salesman at IBM in sales in London.',index(13,4),'Being_employed',[pair('Employee',index(13,1),required),pair('Employer',index(13,9),optional),pair('Place',index(13,13),optional),pair('Field',index(13,11),optional),pair('Position',index(13,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(13,1),[jbo,nsubj],required),pair('Employer',index(13,9),[jbo,obl_at],optional),pair('Place',index(13,13),[jbo,obl_in],optional),pair('Field',index(13,11),[jbo,obl_in],optional),pair('Position',index(13,7),[nmod_of],optional)])).
learned_sentence('John has the job of a salesman in a company in sales at AEOI.',index(14,4),'Being_employed',[pair('Employee',index(14,1),required),pair('Employer',index(14,10),optional),pair('Place',index(14,14),optional),pair('Field',index(14,12),optional),pair('Position',index(14,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(14,1),[jbo,nsubj],required),pair('Employer',index(14,10),[jbo,obl_in],optional),pair('Place',index(14,14),[jbo,obl_at],optional),pair('Field',index(14,12),[jbo,obl_in],optional),pair('Position',index(14,7),[nmod_of],optional)])).
learned_sentence('John has the job of a salesman with an institute in sales at AEOI.',index(15,4),'Being_employed',[pair('Employee',index(15,1),required),pair('Employer',index(15,10),optional),pair('Place',index(15,14),optional),pair('Field',index(15,12),optional),pair('Position',index(15,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(15,1),[jbo,nsubj],required),pair('Employer',index(15,10),[jbo,obl_with],optional),pair('Place',index(15,14),[jbo,obl_at],optional),pair('Field',index(15,12),[jbo,obl_in],optional),pair('Position',index(15,7),[nmod_of],optional)])).
learned_sentence('John has the job of a salesman at IBM in sales at AEOI.',index(16,4),'Being_employed',[pair('Employee',index(16,1),required),pair('Employer',index(16,9),optional),pair('Place',index(16,13),optional),pair('Field',index(16,11),optional),pair('Position',index(16,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(16,1),[jbo,nsubj],required),pair('Employer',index(16,9),[jbo,obl_at],optional),pair('Place',index(16,13),[jbo,obl_at],optional),pair('Field',index(16,11),[jbo,obl_in],optional),pair('Position',index(16,7),[nmod_of],optional)])).
learned_sentence('John has a job as a salesman in a company in sales in London.',index(17,4),'Being_employed',[pair('Employee',index(17,1),required),pair('Employer',index(17,10),optional),pair('Place',index(17,14),optional),pair('Field',index(17,12),optional),pair('Position',index(17,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(17,1),[jbo,nsubj],required),pair('Employer',index(17,10),[jbo,obl_in],optional),pair('Place',index(17,14),[jbo,obl_in],optional),pair('Field',index(17,12),[jbo,obl_in],optional),pair('Position',index(17,7),[jbo,obl_as],optional)])).
learned_sentence('John has a job as a salesman with an institute in sales in London.',index(18,4),'Being_employed',[pair('Employee',index(18,1),required),pair('Employer',index(18,10),optional),pair('Place',index(18,14),optional),pair('Field',index(18,12),optional),pair('Position',index(18,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(18,1),[jbo,nsubj],required),pair('Employer',index(18,10),[jbo,obl_with],optional),pair('Place',index(18,14),[jbo,obl_in],optional),pair('Field',index(18,12),[jbo,obl_in],optional),pair('Position',index(18,7),[jbo,obl_as],optional)])).
learned_sentence('John has a job as a salesman at IBM in sales in London.',index(19,4),'Being_employed',[pair('Employee',index(19,1),required),pair('Employer',index(19,9),optional),pair('Place',index(19,13),optional),pair('Field',index(19,11),optional),pair('Position',index(19,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(19,1),[jbo,nsubj],required),pair('Employer',index(19,9),[jbo,obl_at],optional),pair('Place',index(19,13),[jbo,obl_in],optional),pair('Field',index(19,11),[jbo,obl_in],optional),pair('Position',index(19,7),[jbo,obl_as],optional)])).
learned_sentence('John has a job as a salesman in a company in sales at AEOI.',index(20,4),'Being_employed',[pair('Employee',index(20,1),required),pair('Employer',index(20,10),optional),pair('Place',index(20,14),optional),pair('Field',index(20,12),optional),pair('Position',index(20,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(20,1),[jbo,nsubj],required),pair('Employer',index(20,10),[jbo,obl_in],optional),pair('Place',index(20,14),[jbo,obl_at],optional),pair('Field',index(20,12),[jbo,obl_in],optional),pair('Position',index(20,7),[jbo,obl_as],optional)])).
learned_sentence('John has a job as a salesman with an institute in sales at AEOI.',index(21,4),'Being_employed',[pair('Employee',index(21,1),required),pair('Employer',index(21,10),optional),pair('Place',index(21,14),optional),pair('Field',index(21,12),optional),pair('Position',index(21,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(21,1),[jbo,nsubj],required),pair('Employer',index(21,10),[jbo,obl_with],optional),pair('Place',index(21,14),[jbo,obl_at],optional),pair('Field',index(21,12),[jbo,obl_in],optional),pair('Position',index(21,7),[jbo,obl_as],optional)])).
learned_sentence('John has a job as a salesman at IBM in sales at AEOI.',index(22,4),'Being_employed',[pair('Employee',index(22,1),required),pair('Employer',index(22,9),optional),pair('Place',index(22,13),optional),pair('Field',index(22,11),optional),pair('Position',index(22,7),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(22,1),[jbo,nsubj],required),pair('Employer',index(22,9),[jbo,obl_at],optional),pair('Place',index(22,13),[jbo,obl_at],optional),pair('Field',index(22,11),[jbo,obl_in],optional),pair('Position',index(22,7),[jbo,obl_as],optional)])).
learned_sentence('The job of John is a salesman in a company in sales in London.',index(23,2),'Being_employed',[pair('Employee',index(23,4),required),pair('Employer',index(23,10),optional),pair('Place',index(23,14),optional),pair('Field',index(23,12),optional),pair('Position',index(23,7),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(23,4),[nmod_of],required),pair('Employer',index(23,10),[jbusn,obl_in],optional),pair('Place',index(23,14),[jbusn,obl_in],optional),pair('Field',index(23,12),[jbusn,obl_in],optional),pair('Position',index(23,7),[jbusn],required)])).
learned_sentence('The job of John is a salesman with an institute in sales in London.',index(24,2),'Being_employed',[pair('Employee',index(24,4),required),pair('Employer',index(24,10),optional),pair('Place',index(24,14),optional),pair('Field',index(24,12),optional),pair('Position',index(24,7),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(24,4),[nmod_of],required),pair('Employer',index(24,10),[jbusn,obl_with],optional),pair('Place',index(24,14),[jbusn,obl_in],optional),pair('Field',index(24,12),[jbusn,obl_in],optional),pair('Position',index(24,7),[jbusn],required)])).
learned_sentence('The job of John is a salesman at IBM in sales in London.',index(25,2),'Being_employed',[pair('Employee',index(25,4),required),pair('Employer',index(25,9),optional),pair('Place',index(25,13),optional),pair('Field',index(25,11),optional),pair('Position',index(25,7),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(25,4),[nmod_of],required),pair('Employer',index(25,9),[jbusn,obl_at],optional),pair('Place',index(25,13),[jbusn,obl_in],optional),pair('Field',index(25,11),[jbusn,obl_in],optional),pair('Position',index(25,7),[jbusn],required)])).
learned_sentence('The job of John is a salesman in a company in sales at AEOI.',index(26,2),'Being_employed',[pair('Employee',index(26,4),required),pair('Employer',index(26,10),optional),pair('Place',index(26,14),optional),pair('Field',index(26,12),optional),pair('Position',index(26,7),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(26,4),[nmod_of],required),pair('Employer',index(26,10),[jbusn,obl_in],optional),pair('Place',index(26,14),[jbusn,obl_at],optional),pair('Field',index(26,12),[jbusn,obl_in],optional),pair('Position',index(26,7),[jbusn],required)])).
learned_sentence('The job of John is a salesman with an institute in sales at AEOI.',index(27,2),'Being_employed',[pair('Employee',index(27,4),required),pair('Employer',index(27,10),optional),pair('Place',index(27,14),optional),pair('Field',index(27,12),optional),pair('Position',index(27,7),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(27,4),[nmod_of],required),pair('Employer',index(27,10),[jbusn,obl_with],optional),pair('Place',index(27,14),[jbusn,obl_at],optional),pair('Field',index(27,12),[jbusn,obl_in],optional),pair('Position',index(27,7),[jbusn],required)])).
learned_sentence('The job of John is a salesman at IBM in sales at AEOI.',index(28,2),'Being_employed',[pair('Employee',index(28,4),required),pair('Employer',index(28,9),optional),pair('Place',index(28,13),optional),pair('Field',index(28,11),optional),pair('Position',index(28,7),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(28,4),[nmod_of],required),pair('Employer',index(28,9),[jbusn,obl_at],optional),pair('Place',index(28,13),[jbusn,obl_at],optional),pair('Field',index(28,11),[jbusn,obl_in],optional),pair('Position',index(28,7),[jbusn],required)])).
learned_sentence('The job of John is as a salesman in a company in sales in London.',index(29,2),'Being_employed',[pair('Employee',index(29,4),required),pair('Employer',index(29,11),optional),pair('Place',index(29,15),optional),pair('Field',index(29,13),optional),pair('Position',index(29,8),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(29,4),[nmod_of],required),pair('Employer',index(29,11),[jbusn,obl_in],optional),pair('Place',index(29,15),[jbusn,obl_in],optional),pair('Field',index(29,13),[jbusn,obl_in],optional),pair('Position',index(29,8),[jbusn],required)])).
learned_sentence('The job of John is as a salesman with an institute in sales in London.',index(30,2),'Being_employed',[pair('Employee',index(30,4),required),pair('Employer',index(30,11),optional),pair('Place',index(30,15),optional),pair('Field',index(30,13),optional),pair('Position',index(30,8),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(30,4),[nmod_of],required),pair('Employer',index(30,11),[jbusn,obl_with],optional),pair('Place',index(30,15),[jbusn,obl_in],optional),pair('Field',index(30,13),[jbusn,obl_in],optional),pair('Position',index(30,8),[jbusn],required)])).
learned_sentence('The job of John is as a salesman at IBM in sales in London.',index(31,2),'Being_employed',[pair('Employee',index(31,4),required),pair('Employer',index(31,10),optional),pair('Place',index(31,14),optional),pair('Field',index(31,12),optional),pair('Position',index(31,8),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(31,4),[nmod_of],required),pair('Employer',index(31,10),[jbusn,obl_at],optional),pair('Place',index(31,14),[jbusn,obl_in],optional),pair('Field',index(31,12),[jbusn,obl_in],optional),pair('Position',index(31,8),[jbusn],required)])).
learned_sentence('The job of John is as a salesman in a company in sales at AEOI.',index(32,2),'Being_employed',[pair('Employee',index(32,4),required),pair('Employer',index(32,11),optional),pair('Place',index(32,15),optional),pair('Field',index(32,13),optional),pair('Position',index(32,8),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(32,4),[nmod_of],required),pair('Employer',index(32,11),[jbusn,obl_in],optional),pair('Place',index(32,15),[jbusn,obl_at],optional),pair('Field',index(32,13),[jbusn,obl_in],optional),pair('Position',index(32,8),[jbusn],required)])).
learned_sentence('The job of John is as a salesman with an institute in sales at AEOI.',index(33,2),'Being_employed',[pair('Employee',index(33,4),required),pair('Employer',index(33,11),optional),pair('Place',index(33,15),optional),pair('Field',index(33,13),optional),pair('Position',index(33,8),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(33,4),[nmod_of],required),pair('Employer',index(33,11),[jbusn,obl_with],optional),pair('Place',index(33,15),[jbusn,obl_at],optional),pair('Field',index(33,13),[jbusn,obl_in],optional),pair('Position',index(33,8),[jbusn],required)])).
learned_sentence('The job of John is as a salesman at IBM in sales at AEOI.',index(34,2),'Being_employed',[pair('Employee',index(34,4),required),pair('Employer',index(34,10),optional),pair('Place',index(34,14),optional),pair('Field',index(34,12),optional),pair('Position',index(34,8),required)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(34,4),[nmod_of],required),pair('Employer',index(34,10),[jbusn,obl_at],optional),pair('Place',index(34,14),[jbusn,obl_at],optional),pair('Field',index(34,12),[jbusn,obl_in],optional),pair('Position',index(34,8),[jbusn],required)])).
learned_sentence('John has a job of management in a company in sales in London.',index(35,4),'Being_employed',[pair('Employee',index(35,1),required),pair('Employer',index(35,9),optional),pair('Place',index(35,13),optional),pair('Field',index(35,11),optional),pair('Task',index(35,6),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(35,1),[jbo,nsubj],required),pair('Employer',index(35,9),[jbo,obl_in],optional),pair('Place',index(35,13),[jbo,obl_in],optional),pair('Field',index(35,11),[jbo,obl_in],optional),pair('Task',index(35,6),[nmod_of],optional)])).
learned_sentence('John has a job of management with an institute in sales in London.',index(36,4),'Being_employed',[pair('Employee',index(36,1),required),pair('Employer',index(36,9),optional),pair('Place',index(36,13),optional),pair('Field',index(36,11),optional),pair('Task',index(36,6),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(36,1),[jbo,nsubj],required),pair('Employer',index(36,9),[jbo,obl_with],optional),pair('Place',index(36,13),[jbo,obl_in],optional),pair('Field',index(36,11),[jbo,obl_in],optional),pair('Task',index(36,6),[nmod_of],optional)])).
learned_sentence('John has a job of management at IBM in sales in London.',index(37,4),'Being_employed',[pair('Employee',index(37,1),required),pair('Employer',index(37,8),optional),pair('Place',index(37,12),optional),pair('Field',index(37,10),optional),pair('Task',index(37,6),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(37,1),[jbo,nsubj],required),pair('Employer',index(37,8),[jbo,obl_at],optional),pair('Place',index(37,12),[jbo,obl_in],optional),pair('Field',index(37,10),[jbo,obl_in],optional),pair('Task',index(37,6),[nmod_of],optional)])).
learned_sentence('John has a job of management in a company in sales at AEOI.',index(38,4),'Being_employed',[pair('Employee',index(38,1),required),pair('Employer',index(38,9),optional),pair('Place',index(38,13),optional),pair('Field',index(38,11),optional),pair('Task',index(38,6),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(38,1),[jbo,nsubj],required),pair('Employer',index(38,9),[jbo,obl_in],optional),pair('Place',index(38,13),[jbo,obl_at],optional),pair('Field',index(38,11),[jbo,obl_in],optional),pair('Task',index(38,6),[nmod_of],optional)])).
learned_sentence('John has a job of management with an institute in sales at AEOI.',index(39,4),'Being_employed',[pair('Employee',index(39,1),required),pair('Employer',index(39,9),optional),pair('Place',index(39,13),optional),pair('Field',index(39,11),optional),pair('Task',index(39,6),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(39,1),[jbo,nsubj],required),pair('Employer',index(39,9),[jbo,obl_with],optional),pair('Place',index(39,13),[jbo,obl_at],optional),pair('Field',index(39,11),[jbo,obl_in],optional),pair('Task',index(39,6),[nmod_of],optional)])).
learned_sentence('John has a job of management at IBM in sales at AEOI.',index(40,4),'Being_employed',[pair('Employee',index(40,1),required),pair('Employer',index(40,8),optional),pair('Place',index(40,12),optional),pair('Field',index(40,10),optional),pair('Task',index(40,6),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(40,1),[jbo,nsubj],required),pair('Employer',index(40,8),[jbo,obl_at],optional),pair('Place',index(40,12),[jbo,obl_at],optional),pair('Field',index(40,10),[jbo,obl_in],optional),pair('Task',index(40,6),[nmod_of],optional)])).
learned_sentence('John is employed as a salesman in a company in sales in London.',index(41,3),'Being_employed',[pair('Employee',index(41,1),required),pair('Employer',index(41,9),optional),pair('Place',index(41,13),optional),pair('Field',index(41,11),optional),pair('Position',index(41,6),required)],[],lvp('employ','Being_employed',[pair('Employee',index(41,1),[obj],required),pair('Employer',index(41,9),[obl_in],optional),pair('Place',index(41,13),[obl_in],optional),pair('Field',index(41,11),[obl_in],optional),pair('Position',index(41,6),[obl_as],required)])).
learned_sentence('John is employed as a salesman in a company in sales in London.',index(41,3),'Being_employed',[pair('Employee',index(41,1),required),pair('Employer',index(41,9),optional),pair('Place',index(41,13),optional),pair('Field',index(41,11),optional),pair('Position',index(41,6),required)],[],lvp('employed','Being_employed',[pair('Employee',index(41,1),[nsubj],required),pair('Employer',index(41,9),[obl_in],optional),pair('Place',index(41,13),[obl_in],optional),pair('Field',index(41,11),[obl_in],optional),pair('Position',index(41,6),[obl_as],required)])).
learned_sentence('John is a salesman.',index(42,4),'Being_employed',[pair('Employee',index(42,1),required),pair('Position',index(42,4),required)],['teacher'],lvp('salesman','Being_employed',[pair('Employee',index(42,1),[nsubj],required),pair('Position',index(42,4),[self],required)])).
learned_sentence('Mary is a female.',index(43,2),'Human_gender',[pair('Person',index(43,1),required),pair('Gender',index(43,4),required)],[],lvp('be','Human_gender',[pair('Person',index(43,1),[poc_null_noun,nsubj],required),pair('Gender',index(43,4),[poc_null_noun],required)])).
learned_sentence('Mary has the gender of female.',index(44,4),'Human_gender',[pair('Person',index(44,1),required),pair('Gender',index(44,6),required)],[],lvp('gender','Human_gender',[pair('Person',index(44,1),[jbo,nsubj],required),pair('Gender',index(44,6),[nmod_of],required)])).
learned_sentence('The gender of Mary is female.',index(45,2),'Human_gender',[pair('Person',index(45,4),required),pair('Gender',index(45,6),required)],[],lvp('gender','Human_gender',[pair('Person',index(45,4),[nmod_of],required),pair('Gender',index(45,6),[jbusn],required)])).
learned_sentence('Mary holds a female gender.',index(46,5),'Human_gender',[pair('Person',index(46,1),required),pair('Gender',index(46,4),required)],[],lvp('gender','Human_gender',[pair('Person',index(46,1),[jbo,nsubj],required),pair('Gender',index(46,4),[amod],required)])).
learned_sentence('Mary lives in a town with John.',index(47,2),'Residence',[pair('Resident',index(47,1),required),pair('Location',index(47,5),required),pair('Co_resident',index(47,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live','Residence',[pair('Resident',index(47,1),[nsubj],required),pair('Location',index(47,5),[obl_in],required),pair('Co_resident',index(47,7),[obl_with],optional)])).
learned_sentence('Mary lives on a dessert with John.',index(48,2),'Residence',[pair('Resident',index(48,1),required),pair('Location',index(48,5),required),pair('Co_resident',index(48,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live','Residence',[pair('Resident',index(48,1),[nsubj],required),pair('Location',index(48,5),[obl_on],required),pair('Co_resident',index(48,7),[obl_with],optional)])).
learned_sentence('Mary lives above a station with John.',index(49,2),'Residence',[pair('Resident',index(49,1),required),pair('Location',index(49,5),required),pair('Co_resident',index(49,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live','Residence',[pair('Resident',index(49,1),[nsubj],required),pair('Location',index(49,5),[obl_above],required),pair('Co_resident',index(49,7),[obl_with],optional)])).
learned_sentence('Mary lives around a station with John.',index(50,2),'Residence',[pair('Resident',index(50,1),required),pair('Location',index(50,5),required),pair('Co_resident',index(50,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live','Residence',[pair('Resident',index(50,1),[nsubj],required),pair('Location',index(50,5),[obl_around],required),pair('Co_resident',index(50,7),[obl_with],optional)])).
learned_sentence('Mary lives across a border with John.',index(51,2),'Residence',[pair('Resident',index(51,1),required),pair('Location',index(51,5),required),pair('Co_resident',index(51,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live','Residence',[pair('Resident',index(51,1),[nsubj],required),pair('Location',index(51,5),[obl_across],required),pair('Co_resident',index(51,7),[obl_with],optional)])).
learned_sentence('Mary lives at a house with John.',index(52,2),'Residence',[pair('Resident',index(52,1),required),pair('Location',index(52,5),required),pair('Co_resident',index(52,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live','Residence',[pair('Resident',index(52,1),[nsubj],required),pair('Location',index(52,5),[obl_at],required),pair('Co_resident',index(52,7),[obl_with],optional)])).
learned_sentence('Mary lives down a road with John.',index(53,2),'Residence',[pair('Resident',index(53,1),required),pair('Location',index(53,5),required),pair('Co_resident',index(53,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live_down','Residence',[pair('Resident',index(53,1),[nsubj],required),pair('Location',index(53,5),[obj],required),pair('Co_resident',index(53,7),[obl_with],optional)])).
learned_sentence('Mary lives down a road with John.',index(53,2),'Residence',[pair('Resident',index(53,1),required),pair('Location',index(53,5),required),pair('Co_resident',index(53,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live','Residence',[pair('Resident',index(53,1),[nsubj],required),pair('Location',index(53,5),[obl_down],required),pair('Co_resident',index(53,7),[obl_with],optional)])).
learned_sentence('Mary lives near a site with John.',index(54,2),'Residence',[pair('Resident',index(54,1),required),pair('Location',index(54,5),required),pair('Co_resident',index(54,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live','Residence',[pair('Resident',index(54,1),[nsubj],required),pair('Location',index(54,5),[obl_near],required),pair('Co_resident',index(54,7),[obl_with],optional)])).
learned_sentence('Mary lives outside a community with John.',index(55,2),'Residence',[pair('Resident',index(55,1),required),pair('Location',index(55,5),required),pair('Co_resident',index(55,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live','Residence',[pair('Resident',index(55,1),[nsubj],required),pair('Location',index(55,5),[obl_outside],required),pair('Co_resident',index(55,7),[obl_with],optional)])).
learned_sentence('Mary lives upon an island with John.',index(56,2),'Residence',[pair('Resident',index(56,1),required),pair('Location',index(56,5),required),pair('Co_resident',index(56,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live','Residence',[pair('Resident',index(56,1),[nsubj],required),pair('Location',index(56,5),[obl_upon],required),pair('Co_resident',index(56,7),[obl_with],optional)])).
learned_sentence('Mary lives along a road with John.',index(57,2),'Residence',[pair('Resident',index(57,1),required),pair('Location',index(57,5),required),pair('Co_resident',index(57,7),optional)],['reside','camp','dwell','lodge','occupy','room','stay'],lvp('live','Residence',[pair('Resident',index(57,1),[nsubj],required),pair('Location',index(57,5),[obl_along],required),pair('Co_resident',index(57,7),[obl_with],optional)])).
learned_sentence('Mary is a resident of London.',index(58,4),'Residence',[pair('Resident',index(58,1),required),pair('Location',index(58,6),required)],['occupant','dweller','inhabitant'],lvp('resident','Residence',[pair('Resident',index(58,1),[nsubj],required),pair('Location',index(58,6),[nmod_of],required)])).
learned_sentence('Mary is a resident from London.',index(59,4),'Residence',[pair('Resident',index(59,1),required),pair('Location',index(59,6),required)],['occupant','dweller','inhabitant'],lvp('resident','Residence',[pair('Resident',index(59,1),[nsubj],required),pair('Location',index(59,6),[obl_from],required)])).
learned_sentence('Mary is a resident in London.',index(60,4),'Residence',[pair('Resident',index(60,1),required),pair('Location',index(60,6),required)],['occupant','dweller','inhabitant'],lvp('resident','Residence',[pair('Resident',index(60,1),[nsubj],required),pair('Location',index(60,6),[obl_in],required)])).
learned_sentence('Mary is inhabited in a town with John.',index(61,3),'Residence',[pair('Resident',index(61,1),required),pair('Location',index(61,6),required),pair('Co_resident',index(61,8),optional)],['camped'],lvp('inhabit','Residence',[pair('Resident',index(61,1),[obj],required),pair('Location',index(61,6),[obl_in],required),pair('Co_resident',index(61,8),[obl_with],optional)])).
learned_sentence('Mary is inhabited in a town with John.',index(61,3),'Residence',[pair('Resident',index(61,1),required),pair('Location',index(61,6),required),pair('Co_resident',index(61,8),optional)],['camped'],lvp('inhabited','Residence',[pair('Resident',index(61,1),[nsubj],required),pair('Location',index(61,6),[obl_in],required),pair('Co_resident',index(61,8),[obl_with],optional)])).
learned_sentence('Mary was born in London in 1986.',index(62,3),'Being_born',[pair('Person',index(62,1),required),pair('Place',index(62,5),optional),pair('Time',index(62,7),optional)],[],lvp('bear','Being_born',[pair('Person',index(62,1),[obj],required),pair('Place',index(62,5),[obl_in],optional),pair('Time',index(62,7),[obl_in],optional)])).
learned_sentence('Mary was born in London in 1986.',index(62,3),'Being_born',[pair('Person',index(62,1),required),pair('Place',index(62,5),optional),pair('Time',index(62,7),optional)],[],lvp('borne','Being_born',[pair('Person',index(62,1),[nsubj],required),pair('Place',index(62,5),[obl_in],optional),pair('Time',index(62,7),[obl_in],optional)])).
learned_sentence('Moore rents a garage from Dawson at a rate of 500 dollars.',index(63,2),'Renting',[pair('Lessee',index(63,1),required),pair('Goods',index(63,4),required),pair('Lessor',index(63,6),optional),pair('Money',index(63,12),optional)],['charter','lease'],lvp('rent','Renting',[pair('Lessee',index(63,1),[nsubj],required),pair('Goods',index(63,4),[obj],required),pair('Lessor',index(63,6),[obl_from],optional),pair('Money',index(63,12),[obl_at,nmod_of],optional)])).
learned_sentence('Mary buys a car from George for John in London at a price of 300 dollars.',index(64,2),'Commerce_buy',[pair('Buyer',index(64,1),required),pair('Goods',index(64,4),required),pair('Seller',index(64,6),optional),pair('Recipient',index(64,8),optional),pair('Place',index(64,10),optional),pair('Money',index(64,16),optional)],['purchase'],lvp('buy','Commerce_buy',[pair('Buyer',index(64,1),[nsubj],required),pair('Goods',index(64,4),[obj],required),pair('Seller',index(64,6),[obl_from],optional),pair('Recipient',index(64,8),[obl_for],optional),pair('Place',index(64,10),[obl_in],optional),pair('Money',index(64,16),[obl_at,nmod_of],optional)])).
learned_sentence('Mary buys a car from George for John in London for 300 dollars.',index(65,2),'Commerce_buy',[pair('Buyer',index(65,1),required),pair('Goods',index(65,4),required),pair('Seller',index(65,6),optional),pair('Recipient',index(65,8),optional),pair('Place',index(65,10),optional),pair('Money',index(65,13),optional)],['purchase'],lvp('buy','Commerce_buy',[pair('Buyer',index(65,1),[nsubj],required),pair('Goods',index(65,4),[obj],required),pair('Seller',index(65,6),[obl_from],optional),pair('Recipient',index(65,8),[obl_for],optional),pair('Place',index(65,10),[obl_in],optional),pair('Money',index(65,13),[obl_for],optional)])).
learned_sentence('Mary buys a car from George for John in London with 300 dollars.',index(66,2),'Commerce_buy',[pair('Buyer',index(66,1),required),pair('Goods',index(66,4),required),pair('Seller',index(66,6),optional),pair('Recipient',index(66,8),optional),pair('Place',index(66,10),optional),pair('Money',index(66,13),optional)],['purchase'],lvp('buy','Commerce_buy',[pair('Buyer',index(66,1),[nsubj],required),pair('Goods',index(66,4),[obj],required),pair('Seller',index(66,6),[obl_from],optional),pair('Recipient',index(66,8),[obl_for],optional),pair('Place',index(66,10),[obl_in],optional),pair('Money',index(66,13),[obl_with],optional)])).
learned_sentence('Mary buys John a car from George in London at a price of 300 dollars.',index(67,2),'Commerce_buy',[pair('Buyer',index(67,1),required),pair('Goods',index(67,5),required),pair('Seller',index(67,7),optional),pair('Recipient',index(67,3),optional),pair('Place',index(67,9),optional),pair('Money',index(67,15),optional)],['purchase'],lvp('buy','Commerce_buy',[pair('Buyer',index(67,1),[nsubj],required),pair('Goods',index(67,5),[obj],required),pair('Seller',index(67,7),[obl_from],optional),pair('Recipient',index(67,3),[iobj],optional),pair('Place',index(67,9),[obl_in],optional),pair('Money',index(67,15),[obl_at,nmod_of],optional)])).
learned_sentence('Mary buys John a car from George in London for 300 dollars.',index(68,2),'Commerce_buy',[pair('Buyer',index(68,1),required),pair('Goods',index(68,5),required),pair('Seller',index(68,7),optional),pair('Recipient',index(68,3),optional),pair('Place',index(68,9),optional),pair('Money',index(68,12),optional)],['purchase'],lvp('buy','Commerce_buy',[pair('Buyer',index(68,1),[nsubj],required),pair('Goods',index(68,5),[obj],required),pair('Seller',index(68,7),[obl_from],optional),pair('Recipient',index(68,3),[iobj],optional),pair('Place',index(68,9),[obl_in],optional),pair('Money',index(68,12),[obl_for],optional)])).
learned_sentence('Mary buys John a car from George in London with 300 dollars.',index(69,2),'Commerce_buy',[pair('Buyer',index(69,1),required),pair('Goods',index(69,5),required),pair('Seller',index(69,7),optional),pair('Recipient',index(69,3),optional),pair('Place',index(69,9),optional),pair('Money',index(69,12),optional)],['purchase'],lvp('buy','Commerce_buy',[pair('Buyer',index(69,1),[nsubj],required),pair('Goods',index(69,5),[obj],required),pair('Seller',index(69,7),[obl_from],optional),pair('Recipient',index(69,3),[iobj],optional),pair('Place',index(69,9),[obl_in],optional),pair('Money',index(69,12),[obl_with],optional)])).
learned_sentence('Mary makes a purchase of a car from George for John in London at a price of 300 dollars.',index(70,4),'Commerce_buy',[pair('Buyer',index(70,1),required),pair('Goods',index(70,7),required),pair('Seller',index(70,9),optional),pair('Recipient',index(70,11),optional),pair('Place',index(70,13),optional),pair('Money',index(70,19),optional)],[],lvp('purchase','Commerce_buy',[pair('Buyer',index(70,1),[jbo,nsubj],required),pair('Goods',index(70,7),[nmod_of],required),pair('Seller',index(70,9),[jbo,obl_from],optional),pair('Recipient',index(70,11),[jbo,obl_for],optional),pair('Place',index(70,13),[jbo,obl_in],optional),pair('Money',index(70,19),[jbo,obl_at,nmod_of],optional)])).
learned_sentence('Mary makes a purchase of a car from George for John in London for 300 dollars.',index(71,4),'Commerce_buy',[pair('Buyer',index(71,1),required),pair('Goods',index(71,7),required),pair('Seller',index(71,9),optional),pair('Recipient',index(71,11),optional),pair('Place',index(71,13),optional),pair('Money',index(71,16),optional)],[],lvp('purchase','Commerce_buy',[pair('Buyer',index(71,1),[jbo,nsubj],required),pair('Goods',index(71,7),[nmod_of],required),pair('Seller',index(71,9),[jbo,obl_from],optional),pair('Recipient',index(71,11),[jbo,obl_for],optional),pair('Place',index(71,13),[jbo,obl_in],optional),pair('Money',index(71,16),[jbo,obl_for],optional)])).
learned_sentence('Mary makes a purchase of a car from George for John in London with 300 dollars.',index(72,4),'Commerce_buy',[pair('Buyer',index(72,1),required),pair('Goods',index(72,7),required),pair('Seller',index(72,9),optional),pair('Recipient',index(72,11),optional),pair('Place',index(72,13),optional),pair('Money',index(72,16),optional)],[],lvp('purchase','Commerce_buy',[pair('Buyer',index(72,1),[jbo,nsubj],required),pair('Goods',index(72,7),[nmod_of],required),pair('Seller',index(72,9),[jbo,obl_from],optional),pair('Recipient',index(72,11),[jbo,obl_for],optional),pair('Place',index(72,13),[jbo,obl_in],optional),pair('Money',index(72,16),[jbo,obl_with],optional)])).
learned_sentence('Mary pays 400 dollars for a store.',index(73,2),'Commerce_buy',[pair('Buyer',index(73,1),required),pair('Goods',index(73,7),required),pair('Money',index(73,4),required)],[],lvp('pay','Commerce_buy',[pair('Buyer',index(73,1),[nsubj],required),pair('Goods',index(73,7),[obl_for],required),pair('Money',index(73,4),[obj],required)])).
learned_sentence('Mary pays John 400 dollars for a store.',index(74,2),'Commerce_buy',[pair('Buyer',index(74,1),required),pair('Goods',index(74,8),required),pair('Money',index(74,5),optional),pair('Seller',index(74,3),required)],[],lvp('pay','Commerce_buy',[pair('Buyer',index(74,1),[nsubj],required),pair('Goods',index(74,8),[obl_for],required),pair('Money',index(74,5),[obj],optional),pair('Seller',index(74,3),[obj,compound],required)])).
learned_sentence('Mary is a buyer of a store.',index(75,4),'Commerce_buy',[pair('Buyer',index(75,1),required),pair('Goods',index(75,7),required)],['purchaser'],lvp('buyer','Commerce_buy',[pair('Buyer',index(75,1),[nsubj],required),pair('Goods',index(75,7),[nmod_of],required)])).
learned_sentence('Mary sells a car to John in London at a price of 300 dollars.',index(76,2),'Commerce_buy',[pair('Buyer',index(76,6),required),pair('Goods',index(76,4),required),pair('Seller',index(76,1),required),pair('Place',index(76,8),optional),pair('Money',index(76,14),optional)],[],lvp('sell','Commerce_buy',[pair('Buyer',index(76,6),[obl_to],required),pair('Goods',index(76,4),[obj],required),pair('Seller',index(76,1),[nsubj],required),pair('Place',index(76,8),[obl_in],optional),pair('Money',index(76,14),[obl_at,nmod_of],optional)])).
learned_sentence('Mary sells a car to John in London for 300 dollars.',index(77,2),'Commerce_buy',[pair('Buyer',index(77,6),required),pair('Goods',index(77,4),required),pair('Seller',index(77,1),required),pair('Place',index(77,8),optional),pair('Money',index(77,11),optional)],[],lvp('sell','Commerce_buy',[pair('Buyer',index(77,6),[obl_to],required),pair('Goods',index(77,4),[obj],required),pair('Seller',index(77,1),[nsubj],required),pair('Place',index(77,8),[obl_in],optional),pair('Money',index(77,11),[obl_for],optional)])).
learned_sentence('Mary sells John a car in London at a price of 300 dollars.',index(78,2),'Commerce_buy',[pair('Buyer',index(78,3),required),pair('Goods',index(78,5),required),pair('Seller',index(78,1),required),pair('Place',index(78,7),optional),pair('Money',index(78,13),optional)],[],lvp('sell','Commerce_buy',[pair('Buyer',index(78,3),[iobj],required),pair('Goods',index(78,5),[obj],required),pair('Seller',index(78,1),[nsubj],required),pair('Place',index(78,7),[obl_in],optional),pair('Money',index(78,13),[obl_at,nmod_of],optional)])).
learned_sentence('Mary sells John a car in London for 300 dollars.',index(79,2),'Commerce_buy',[pair('Buyer',index(79,3),required),pair('Goods',index(79,5),required),pair('Seller',index(79,1),required),pair('Place',index(79,7),optional),pair('Money',index(79,10),optional)],[],lvp('sell','Commerce_buy',[pair('Buyer',index(79,3),[iobj],required),pair('Goods',index(79,5),[obj],required),pair('Seller',index(79,1),[nsubj],required),pair('Place',index(79,7),[obl_in],optional),pair('Money',index(79,10),[obl_for],optional)])).
learned_sentence('Mary owns a car.',index(80,2),'Possession',[pair('Owner',index(80,1),required),pair('Possession',index(80,4),required)],['get','have','possess'],lvp('own','Possession',[pair('Owner',index(80,1),[nsubj],required),pair('Possession',index(80,4),[obj],required)])).
learned_sentence('Mary is the owner of a car.',index(81,4),'Possession',[pair('Owner',index(81,1),required),pair('Possession',index(81,7),required)],['possessor'],lvp('owner','Possession',[pair('Owner',index(81,1),[nsubj],required),pair('Possession',index(81,7),[nmod_of],required)])).
learned_sentence('Mary is in the possession of a car.',index(82,5),'Possession',[pair('Owner',index(82,1),required),pair('Possession',index(82,8),required)],[],lvp('possession','Possession',[pair('Owner',index(82,1),[nsubj],required),pair('Possession',index(82,8),[nmod_of],required)])).
learned_sentence('Mary has the ownership of a car.',index(83,4),'Possession',[pair('Owner',index(83,1),required),pair('Possession',index(83,7),required)],[],lvp('ownership','Possession',[pair('Owner',index(83,1),[jbo,nsubj],required),pair('Possession',index(83,7),[nmod_of],required)])).
learned_sentence('Mary cooks a meal in the kitchen for John.',index(84,2),'Cooking',[pair('Cook',index(84,1),required),pair('Food',index(84,4),required),pair('Place',index(84,7),optional),pair('Recipient',index(84,9),optional)],['bake','make','fry','grill','boil','roast'],lvp('cook','Cooking',[pair('Cook',index(84,1),[nsubj],required),pair('Food',index(84,4),[obj],required),pair('Place',index(84,7),[obl_in],optional),pair('Recipient',index(84,9),[obl_for],optional)])).
learned_sentence('John dresses in a suit.',index(85,2),'Dressing',[pair('Wearer',index(85,1),required),pair('Clothing',index(85,5),required)],['dress_up'],lvp('dress_in','Dressing',[pair('Wearer',index(85,1),[nsubj],required),pair('Clothing',index(85,5),[obj],required)])).
learned_sentence('John dresses in a suit.',index(85,2),'Dressing',[pair('Wearer',index(85,1),required),pair('Clothing',index(85,5),required)],['dress_up'],lvp('dress','Dressing',[pair('Wearer',index(85,1),[nsubj],required),pair('Clothing',index(85,5),[obl_in],required)])).
learned_sentence('John puts on a suit.',index(86,2),'Dressing',[pair('Wearer',index(86,1),required),pair('Clothing',index(86,5),required)],['pull_on'],lvp('put_on','Dressing',[pair('Wearer',index(86,1),[nsubj],required),pair('Clothing',index(86,5),[obj],required)])).
learned_sentence('John puts on a suit.',index(86,2),'Dressing',[pair('Wearer',index(86,1),required),pair('Clothing',index(86,5),required)],['pull_on'],lvp('put','Dressing',[pair('Wearer',index(86,1),[nsubj],required),pair('Clothing',index(86,5),[obl_on],required)])).
learned_sentence('John wears a suit.',index(87,2),'Dressing',[pair('Wearer',index(87,1),required),pair('Clothing',index(87,4),required)],[],lvp('wear','Dressing',[pair('Wearer',index(87,1),[nsubj],required),pair('Clothing',index(87,4),[obj],required)])).
learned_sentence('Mary commutes from Boston to London.',index(88,2),'Travel',[pair('Traveler',index(88,1),required),pair('Source',index(88,4),optional),pair('Goal',index(88,6),optional)],['travel','journey'],lvp('commute','Travel',[pair('Traveler',index(88,1),[nsubj],required),pair('Source',index(88,4),[obl_from],optional),pair('Goal',index(88,6),[obl_to],optional)])).
learned_sentence('Mary makes a trip from Boston to London.',index(89,4),'Travel',[pair('Traveler',index(89,1),optional),pair('Source',index(89,6),optional),pair('Goal',index(89,8),optional)],['journey','tour','expedition','getaway','safari','excursion','odyssey','voyage'],lvp('trip','Travel',[pair('Traveler',index(89,1),[jbo,nsubj],optional),pair('Source',index(89,6),[jbo,obl_from],optional),pair('Goal',index(89,8),[jbo,obl_to],optional)])).
learned_sentence('Mary founds a company in London in 1990.',index(90,2),'Create_organization',[pair('Creator',index(90,1),required),pair('Organization',index(90,4),required),pair('Place',index(90,6),optional),pair('Time',index(90,8),optional)],['create','make','form','yield'],lvp('found','Create_organization',[pair('Creator',index(90,1),[nsubj],required),pair('Organization',index(90,4),[obj],required),pair('Place',index(90,6),[obl_in],optional),pair('Time',index(90,8),[obl_in],optional)])).
learned_sentence('Mary is the founder of a company in London.',index(91,4),'Create_organization',[pair('Creator',index(91,1),required),pair('Organization',index(91,7),required),pair('Place',index(91,9),optional)],['creator'],lvp('founder','Create_organization',[pair('Creator',index(91,1),[nsubj],required),pair('Organization',index(91,7),[nmod_of],required),pair('Place',index(91,9),[obl_in],optional)])).
learned_sentence('Mary obtains a bachelor degree in Biology from Cambridge University.',index(92,2),'Education',[pair('Student',index(92,1),required),pair('Institution',index(92,10),optional),pair('Degree',index(92,5),optional),pair('Subject',index(92,7),optional)],['get','earn','receive'],lvp('obtain','Education',[pair('Student',index(92,1),[nsubj],required),pair('Institution',index(92,10),[obl_from],optional),pair('Degree',index(92,5),[obj],optional),pair('Subject',index(92,7),[obl_in],optional)])).
learned_sentence('Mary enrolls in Cambridge University.',index(93,2),'Education',[pair('Student',index(93,1),required),pair('Institution',index(93,5),required)],[],lvp('enroll','Education',[pair('Student',index(93,1),[nsubj],required),pair('Institution',index(93,5),[obl_in],required)])).
learned_sentence('Mary goes to Cambridge University.',index(94,2),'Education',[pair('Student',index(94,1),required),pair('Institution',index(94,5),required)],[],lvp('go','Education',[pair('Student',index(94,1),[nsubj],required),pair('Institution',index(94,5),[obl_to],required)])).
learned_sentence('Mary enters Cambridge University.',index(95,2),'Education',[pair('Student',index(95,1),required),pair('Institution',index(95,4),required)],['attend'],lvp('enter','Education',[pair('Student',index(95,1),[nsubj],required),pair('Institution',index(95,4),[obj],required)])).
learned_sentence('Mary studies Biology at Cambridge University.',index(96,2),'Education',[pair('Student',index(96,1),required),pair('Institution',index(96,6),optional),pair('Subject',index(96,3),optional)],[],lvp('study','Education',[pair('Student',index(96,1),[nsubj],required),pair('Institution',index(96,6),[obl_at],optional),pair('Subject',index(96,3),[obj],optional)])).
learned_sentence('Mary graduates from Cambridge University.',index(97,2),'Education',[pair('Student',index(97,1),required),pair('Institution',index(97,5),required)],[],lvp('graduate','Education',[pair('Student',index(97,1),[nsubj],required),pair('Institution',index(97,5),[obl_from],required)])).
learned_sentence('Mary donates some money to a school.',index(98,2),'Giving',[pair('Donor',index(98,1),required),pair('Recipient',index(98,7),required),pair('Theme',index(98,4),optional)],['contribute'],lvp('donate','Giving',[pair('Donor',index(98,1),[nsubj],required),pair('Recipient',index(98,7),[obl_to],required),pair('Theme',index(98,4),[obj],optional)])).
learned_sentence('Mary is a donor to a school.',index(99,4),'Giving',[pair('Donor',index(99,1),required),pair('Recipient',index(99,7),required)],['contributor'],lvp('donor','Giving',[pair('Donor',index(99,1),[nsubj],required),pair('Recipient',index(99,7),[obl_to],required)])).
learned_sentence('Mary endows a church with some money.',index(100,2),'Giving',[pair('Donor',index(100,1),required),pair('Recipient',index(100,4),required),pair('Theme',index(100,7),optional)],[],lvp('endow','Giving',[pair('Donor',index(100,1),[nsubj],required),pair('Recipient',index(100,4),[obj],required),pair('Theme',index(100,7),[obl_with],optional)])).
learned_sentence('Mary makes a donation of some money to a school.',index(101,4),'Giving',[pair('Donor',index(101,1),required),pair('Recipient',index(101,10),optional),pair('Theme',index(101,7),optional)],['contribution'],lvp('donation','Giving',[pair('Donor',index(101,1),[jbo,nsubj],required),pair('Recipient',index(101,10),[jbo,obl_to],optional),pair('Theme',index(101,7),[nmod_of],optional)])).
learned_sentence('Mary and John are married.',index(102,5),'Personal_relationship',[pair('Marriage_partner_1',index(102,1),required),pair('Marriage_partner_2',index(102,3),required)],[],lvp('marry','Personal_relationship',[pair('Marriage_partner_1',index(102,1),[obj],required),pair('Marriage_partner_2',index(102,3),[obj],required)])).
learned_sentence('Mary and John are married.',index(102,5),'Personal_relationship',[pair('Marriage_partner_1',index(102,1),required),pair('Marriage_partner_2',index(102,3),required)],[],lvp('married','Personal_relationship',[pair('Marriage_partner_1',index(102,1),[nsubj],required),pair('Marriage_partner_2',index(102,3),[nsubj],required)])).
learned_sentence('Mary is married to John.',index(103,3),'Personal_relationship',[pair('Marriage_partner_1',index(103,1),required),pair('Marriage_partner_2',index(103,5),required)],[],lvp('marry','Personal_relationship',[pair('Marriage_partner_1',index(103,1),[obj],required),pair('Marriage_partner_2',index(103,5),[obl_to],required)])).
learned_sentence('Mary is married to John.',index(103,3),'Personal_relationship',[pair('Marriage_partner_1',index(103,1),required),pair('Marriage_partner_2',index(103,5),required)],[],lvp('married','Personal_relationship',[pair('Marriage_partner_1',index(103,1),[nsubj],required),pair('Marriage_partner_2',index(103,5),[obl_to],required)])).
learned_sentence('Mary and John are a couple.',index(104,6),'Personal_relationship',[pair('Marriage_partner_1',index(104,1),required),pair('Marriage_partner_2',index(104,3),required)],[],lvp('couple','Personal_relationship',[pair('Marriage_partner_1',index(104,1),[nsubj],required),pair('Marriage_partner_2',index(104,3),[nsubj],required)])).
learned_sentence('Mary is the mother of John.',index(105,4),'Personal_relationship',[pair('Mother',index(105,1),required),pair('Child',index(105,6),required)],[],lvp('mother','Personal_relationship',[pair('Mother',index(105,1),[nsubj],required),pair('Child',index(105,6),[nmod_of],required)])).
learned_sentence('Mary is the daughter of John.',index(106,4),'Personal_relationship',[pair('Daughter',index(106,1),required),pair('Parent',index(106,6),required)],[],lvp('daughter','Personal_relationship',[pair('Daughter',index(106,1),[nsubj],required),pair('Parent',index(106,6),[nmod_of],required)])).
learned_sentence('Mary is a parent of John.',index(107,4),'Personal_relationship',[pair('Parent',index(107,1),required),pair('Child',index(107,6),required)],[],lvp('parent','Personal_relationship',[pair('Parent',index(107,1),[nsubj],required),pair('Child',index(107,6),[nmod_of],required)])).
learned_sentence('Mary is a child of John.',index(108,4),'Personal_relationship',[pair('Child',index(108,1),required),pair('Parent',index(108,6),required)],[],lvp('child','Personal_relationship',[pair('Child',index(108,1),[nsubj],required),pair('Parent',index(108,6),[nmod_of],required)])).
learned_sentence('Mary is the wife of John.',index(109,4),'Personal_relationship',[pair('Wife',index(109,1),required),pair('Husband',index(109,6),required)],[],lvp('wife','Personal_relationship',[pair('Wife',index(109,1),[nsubj],required),pair('Husband',index(109,6),[nmod_of],required)])).
learned_sentence('John is the husband of Mary.',index(110,4),'Personal_relationship',[pair('Wife',index(110,6),required),pair('Husband',index(110,1),required)],[],lvp('husband','Personal_relationship',[pair('Wife',index(110,6),[nmod_of],required),pair('Husband',index(110,1),[nsubj],required)])).
learned_sentence('John is the son of Mary.',index(111,4),'Personal_relationship',[pair('Parent',index(111,6),required),pair('Son',index(111,1),required)],[],lvp('son','Personal_relationship',[pair('Parent',index(111,6),[nmod_of],required),pair('Son',index(111,1),[nsubj],required)])).
learned_sentence('John is the father of Mary.',index(112,4),'Personal_relationship',[pair('Father',index(112,1),required),pair('Child',index(112,6),required)],[],lvp('father','Personal_relationship',[pair('Father',index(112,1),[nsubj],required),pair('Child',index(112,6),[nmod_of],required)])).
learned_sentence('Mary is an American.',index(113,2),'People_by_origin',[pair('Person',index(113,1),required),pair('Origin',index(113,4),required)],[],lvp('be','People_by_origin',[pair('Person',index(113,1),[poc_null_propn,nsubj],required),pair('Origin',index(113,4),[poc_null_propn],required)])).
learned_sentence('The ancestry of Mary is American.',index(114,2),'People_by_origin',[pair('Person',index(114,4),required),pair('Origin',index(114,6),required)],['nationality'],lvp('ancestry','People_by_origin',[pair('Person',index(114,4),[nmod_of],required),pair('Origin',index(114,6),[jbusn],required)])).
learned_sentence('Mary has an American ancestry.',index(115,5),'People_by_origin',[pair('Person',index(115,1),required),pair('Origin',index(115,4),required)],['nationality'],lvp('ancestry','People_by_origin',[pair('Person',index(115,1),[jbo,nsubj],required),pair('Origin',index(115,4),[amod],required)])).
learned_sentence('Mary is a Christian.',index(116,2),'People_by_religion',[pair('Person',index(116,1),required),pair('Religion',index(116,4),required)],[],lvp('be','People_by_religion',[pair('Person',index(116,1),[poc_null_propn,nsubj],required),pair('Religion',index(116,4),[poc_null_propn],required)])).
learned_sentence('The religion of Mary is Christian.',index(117,2),'People_by_religion',[pair('Person',index(117,4),required),pair('Religion',index(117,6),required)],[],lvp('religion','People_by_religion',[pair('Person',index(117,4),[nmod_of],required),pair('Religion',index(117,6),[jbusn],required)])).
learned_sentence('Mary works with John on a project.',index(118,2),'Collaboration',[pair('Partner1',index(118,1),required),pair('Partner2',index(118,4),required),pair('Undertaking',index(118,7),optional)],['partner','team_up','conspire','cooperate','collaborate'],lvp('work','Collaboration',[pair('Partner1',index(118,1),[nsubj],required),pair('Partner2',index(118,4),[obl_with],required),pair('Undertaking',index(118,7),[obl_on],optional)])).
learned_sentence('Mary works with John in a project.',index(119,2),'Collaboration',[pair('Partner1',index(119,1),required),pair('Partner2',index(119,4),required),pair('Undertaking',index(119,7),optional)],['partner','team_up','conspire','cooperate','collaborate'],lvp('work','Collaboration',[pair('Partner1',index(119,1),[nsubj],required),pair('Partner2',index(119,4),[obl_with],required),pair('Undertaking',index(119,7),[obl_in],optional)])).
learned_sentence('Mary has a cooperation with John over a project.',index(120,4),'Collaboration',[pair('Partner1',index(120,1),required),pair('Partner2',index(120,6),required),pair('Undertaking',index(120,9),optional)],['collaboration'],lvp('cooperation','Collaboration',[pair('Partner1',index(120,1),[jbo,nsubj],required),pair('Partner2',index(120,6),[jbo,obl_with],required),pair('Undertaking',index(120,9),[jbo,obl_over],optional)])).
learned_sentence('Mary is a partner of John.',index(121,4),'Collaboration',[pair('Partner1',index(121,1),required),pair('Partner2',index(121,6),required)],['collaborator'],lvp('partner','Collaboration',[pair('Partner1',index(121,1),[nsubj],required),pair('Partner2',index(121,6),[nmod_of],required)])).
learned_sentence('Mary leaves the company.',index(122,2),'Quitting',[pair('Employee',index(122,1),required),pair('Employer',index(122,4),required)],[],lvp('leave','Quitting',[pair('Employee',index(122,1),[nsubj],required),pair('Employer',index(122,4),[obj],required)])).
learned_sentence('Mary quits a job.',index(123,2),'Quitting',[pair('Employee',index(123,1),required),pair('Position',index(123,4),required)],[],lvp('quit','Quitting',[pair('Employee',index(123,1),[nsubj],required),pair('Position',index(123,4),[obj],required)])).
learned_sentence('Mary resigns as the chairman from a company.',index(124,2),'Quitting',[pair('Employee',index(124,1),required),pair('Position',index(124,5),optional),pair('Employer',index(124,8),optional)],['step_down','retire'],lvp('resign','Quitting',[pair('Employee',index(124,1),[nsubj],required),pair('Position',index(124,5),[obl_as],optional),pair('Employer',index(124,8),[obl_from],optional)])).
learned_sentence('Mary resigns from the chairman of a company.',index(125,2),'Quitting',[pair('Employee',index(125,1),required),pair('Position',index(125,5),optional),pair('Employer',index(125,8),optional)],['step_down','retire'],lvp('resign','Quitting',[pair('Employee',index(125,1),[nsubj],required),pair('Position',index(125,5),[obl_from],optional),pair('Employer',index(125,8),[obl_from,nmod_of],optional)])).
learned_sentence('Mary makes a resignation as the chairman from a company.',index(126,4),'Quitting',[pair('Employee',index(126,1),required),pair('Position',index(126,7),optional),pair('Employer',index(126,10),optional)],[],lvp('resignation','Quitting',[pair('Employee',index(126,1),[jbo,nsubj],required),pair('Position',index(126,7),[jbo,obl_as],optional),pair('Employer',index(126,10),[jbo,obl_from],optional)])).
learned_sentence('Mary gets a cold.',index(127,2),'Medical_conditions',[pair('Patient',index(127,1),required),pair('Ailment',index(127,4),required)],['catch'],lvp('get','Medical_conditions',[pair('Patient',index(127,1),[nsubj],required),pair('Ailment',index(127,4),[obj],required)])).
learned_sentence('Mary is infected with a cold.',index(128,3),'Medical_conditions',[pair('Patient',index(128,1),required),pair('Ailment',index(128,6),required)],['diagnose','ill'],lvp('infect','Medical_conditions',[pair('Patient',index(128,1),[obj],required),pair('Ailment',index(128,6),[obl_with],required)])).
learned_sentence('Mary is infected with a cold.',index(128,3),'Medical_conditions',[pair('Patient',index(128,1),required),pair('Ailment',index(128,6),required)],['diagnosed','ill'],lvp('infected','Medical_conditions',[pair('Patient',index(128,1),[nsubj],required),pair('Ailment',index(128,6),[obl_with],required)])).
learned_sentence('Mary suffers from a cold.',index(129,2),'Medical_conditions',[pair('Patient',index(129,1),required),pair('Ailment',index(129,5),required)],[],lvp('suffer','Medical_conditions',[pair('Patient',index(129,1),[nsubj],required),pair('Ailment',index(129,5),[obl_from],required)])).
learned_sentence('Mary has an age of 20.',index(130,4),'Age',[pair('Person',index(130,1),required),pair('Age',index(130,6),required)],[],lvp('age','Age',[pair('Person',index(130,1),[jbo,nsubj],required),pair('Age',index(130,6),[nmod_of],required)])).
learned_sentence('Mary is at the age of 20.',index(131,5),'Age',[pair('Person',index(131,1),required),pair('Age',index(131,7),required)],[],lvp('age','Age',[pair('Person',index(131,1),[nsubj],required),pair('Age',index(131,7),[nmod_of],required)])).
learned_sentence('Mary is under the age of 20.',index(132,5),'Age',[pair('Person',index(132,1),required),pair('Age',index(132,7),required)],[],lvp('age','Age',[pair('Person',index(132,1),[nsubj],required),pair('Age',index(132,7),[nmod_of],required)])).
learned_sentence('Mary is 20.',index(133,2),'Age',[pair('Person',index(133,1),required),pair('Age',index(133,3),required)],[],lvp('be','Age',[pair('Person',index(133,1),[poc_null_num,nsubj],required),pair('Age',index(133,3),[poc_null_num],required)])).
learned_sentence('Mary is assigned a Nobel prize by Swedish Academy in 1986.',index(134,3),'Award',[pair('Person',index(134,1),required),pair('Award',index(134,6),required),pair('Organization',index(134,9),optional),pair('Time',index(134,11),optional)],['give','grant','award'],lvp('assign','Award',[pair('Person',index(134,1),[iobj],required),pair('Award',index(134,6),[obj],required),pair('Organization',index(134,9),[obl_by],optional),pair('Time',index(134,11),[obl_in],optional)])).
learned_sentence('Mary is assigned a Nobel prize by Swedish Academy in 1986.',index(134,3),'Award',[pair('Person',index(134,1),required),pair('Award',index(134,6),required),pair('Organization',index(134,9),optional),pair('Time',index(134,11),optional)],['give','grant','award'],lvp('assign','Award',[pair('Person',index(134,1),[iobj],required),pair('Award',index(134,6),[obj],required),pair('Organization',index(134,9),[nsubj],optional),pair('Time',index(134,11),[obl_in],optional)])).
learned_sentence('Mary is assigned a Nobel prize by Swedish Academy in 1986.',index(134,3),'Award',[pair('Person',index(134,1),required),pair('Award',index(134,6),required),pair('Organization',index(134,9),optional),pair('Time',index(134,11),optional)],['given','granted','awarded'],lvp('assigned','Award',[pair('Person',index(134,1),[nsubj_pass],required),pair('Award',index(134,6),[nsubj],required),pair('Organization',index(134,9),[obl_by],optional),pair('Time',index(134,11),[obl_in],optional)])).
learned_sentence('A Nobel prize is awarded to Mary in 1986.',index(135,5),'Award',[pair('Person',index(135,7),required),pair('Award',index(135,3),required),pair('Time',index(135,9),optional)],['give','grant','assign'],lvp('award','Award',[pair('Person',index(135,7),[obl_to],required),pair('Award',index(135,3),[obj],required),pair('Time',index(135,9),[obl_in],optional)])).
learned_sentence('A Nobel prize is awarded to Mary in 1986.',index(135,5),'Award',[pair('Person',index(135,7),required),pair('Award',index(135,3),required),pair('Time',index(135,9),optional)],['given','granted','assigned'],lvp('awarded','Award',[pair('Person',index(135,7),[obl_to],required),pair('Award',index(135,3),[nsubj],required),pair('Time',index(135,9),[obl_in],optional)])).
learned_sentence('A soldier uses a weapon.',index(136,3),'Using',[pair('Agent',index(136,2),required),pair('Instrument',index(136,5),required)],['operate','apply','employ','exercise','utilize'],lvp('use','Using',[pair('Agent',index(136,2),[nsubj],required),pair('Instrument',index(136,5),[obj],required)])).
learned_sentence('Iraq\'s use of a nuclear weapon is banned.',index(137,3),'Using',[pair('Agent',index(137,1),required),pair('Instrument',index(137,7),required)],['application','operation','utilization'],lvp('use','Using',[pair('Agent',index(137,1),[nmod_poss],required),pair('Instrument',index(137,7),[nmod_of],required)])).
learned_sentence('Jack builds a new house with a hammer.',index(138,2),'Building',[pair('Agent',index(138,1),required),pair('Instrument',index(138,8),optional),pair('Created_entity',index(138,5),required)],['construct','assemble','make','put_together','make','weld','piece_together'],lvp('build','Building',[pair('Agent',index(138,1),[nsubj],required),pair('Instrument',index(138,8),[obl_with],optional),pair('Created_entity',index(138,5),[obj],required)])).
learned_sentence('Jack makes the construction of a new house with a hammer.',index(139,4),'Building',[pair('Agent',index(139,1),required),pair('Instrument',index(139,11),optional),pair('Created_entity',index(139,8),required)],[],lvp('construction','Building',[pair('Agent',index(139,1),[jbo,nsubj],required),pair('Instrument',index(139,11),[jbo,obl_with],optional),pair('Created_entity',index(139,8),[nmod_of],required)])).
learned_sentence('Jack kills mary with a knife.',index(140,2),'Killing',[pair('Killer',index(140,1),required),pair('Victim',index(140,3),required),pair('Instrument',index(140,6),optional)],['annihilate','assassinate','butcher','destroy','decapitate','destroy','drown','eliminate','exterminate','massacre'],lvp('kill','Killing',[pair('Killer',index(140,1),[nsubj],required),pair('Victim',index(140,3),[obj],required),pair('Instrument',index(140,6),[obl_with],optional)])).
learned_sentence('Jack is the killer of Mary.',index(141,4),'Killing',[pair('Killer',index(141,1),required),pair('Victim',index(141,6),required)],['murderer','slaughterer','assassinator'],lvp('killer','Killing',[pair('Killer',index(141,1),[nsubj],required),pair('Victim',index(141,6),[nmod_of],required)])).
learned_sentence('The police arrest Jack for murder.',index(142,3),'Arrest',[pair('Authorities',index(142,2),required),pair('Suspect',index(142,4),required),pair('Charges',index(142,6),optional)],['apprehend','summon','nab'],lvp('arrest','Arrest',[pair('Authorities',index(142,2),[nsubj],required),pair('Suspect',index(142,4),[obj],required),pair('Charges',index(142,6),[obl_for],optional)])).
learned_sentence('Jack is under arrest by police for murder.',index(143,4),'Arrest',[pair('Authorities',index(143,6),required),pair('Suspect',index(143,1),required),pair('Charges',index(143,8),optional)],['apprehension'],lvp('arrest','Arrest',[pair('Authorities',index(143,6),[obl_by],required),pair('Suspect',index(143,1),[nsubj],required),pair('Charges',index(143,8),[obl_for],optional)])).
learned_sentence('Jack is under arrest by police on a charge of murder.',index(144,4),'Arrest',[pair('Authorities',index(144,6),required),pair('Suspect',index(144,1),required),pair('Charges',index(144,11),optional)],['apprehension'],lvp('arrest','Arrest',[pair('Authorities',index(144,6),[obl_by],required),pair('Suspect',index(144,1),[nsubj],required),pair('Charges',index(144,11),[obl_on,nmod_of],optional)])).
learned_sentence('The police arrest Jack on a charge of murder.',index(145,3),'Arrest',[pair('Authorities',index(145,2),required),pair('Suspect',index(145,4),required),pair('Charges',index(145,9),optional)],[],lvp('arrest','Arrest',[pair('Authorities',index(145,2),[nsubj],required),pair('Suspect',index(145,4),[obj],required),pair('Charges',index(145,9),[obl_on,nmod_of],optional)])).
learned_sentence('A mysterious fighter attacks a guardsman.',index(146,4),'Attack',[pair('Assailant',index(146,3),required),pair('Victim',index(146,6),required)],['ambush','assail','assault','bomb','hit','raid','strike'],lvp('attack','Attack',[pair('Assailant',index(146,3),[nsubj],required),pair('Victim',index(146,6),[obj],required)])).
learned_sentence('US troops launch an attack on Iraq.',index(147,5),'Attack',[pair('Assailant',index(147,2),required),pair('Victim',index(147,7),required)],['airstrike','assailant','assault','bombardment','bombing','infiltration','onset','strike'],lvp('attack','Attack',[pair('Assailant',index(147,2),[jbo,nsubj],required),pair('Victim',index(147,7),[jbo,obl_on],required)])).
learned_sentence('US troops launch an attack against Iraq.',index(148,5),'Attack',[pair('Assailant',index(148,2),required),pair('Victim',index(148,7),required)],['airstrike','assailant','assault','bombardment','bombing','infiltration','onset','strike'],lvp('attack','Attack',[pair('Assailant',index(148,2),[jbo,nsubj],required),pair('Victim',index(148,7),[jbo,obl_against],required)])).
learned_sentence('Jack leads a company as a chairman.',index(149,2),'Leadership',[pair('Leader',index(149,1),required),pair('Governed',index(149,4),required),pair('Role',index(149,7),optional)],['administer','chair','command','govern','head','lead','reign','rule'],lvp('lead','Leadership',[pair('Leader',index(149,1),[nsubj],required),pair('Governed',index(149,4),[obj],required),pair('Role',index(149,7),[obl_as],optional)])).
learned_sentence('Jack is the leader of a company.',index(150,4),'Leadership',[pair('Leader',index(150,1),required),pair('Governed',index(150,7),required),pair('Role',index(150,4),optional)],['boss','chairman','captain','chief','commander','director','executive','governor','head','president','ruler'],lvp('leader','Leadership',[pair('Leader',index(150,1),[nsubj],required),pair('Governed',index(150,7),[nmod_of],required),pair('Role',index(150,4),[self],optional)])).
learned_sentence('Mary perished in Italy in 1979.',index(151,2),'Death',[pair('Protagonist',index(151,1),required),pair('Place',index(151,4),optional),pair('Time',index(151,6),optional)],['die'],lvp('perish','Death',[pair('Protagonist',index(151,1),[nsubj],required),pair('Place',index(151,4),[obl_in],optional),pair('Time',index(151,6),[obl_in],optional)])).
learned_sentence('Mary dies of cancer in Italy in 1979.',index(152,2),'Death',[pair('Protagonist',index(152,1),required),pair('Cause',index(152,4),required),pair('Place',index(152,6),optional),pair('Time',index(152,8),optional)],[],lvp('die','Death',[pair('Protagonist',index(152,1),[nsubj],required),pair('Cause',index(152,4),[obl_of],required),pair('Place',index(152,6),[obl_in],optional),pair('Time',index(152,8),[obl_in],optional)])).
learned_sentence('Mary perishes from hunger in Italy in 1979.',index(153,2),'Death',[pair('Protagonist',index(153,1),required),pair('Cause',index(153,4),required),pair('Place',index(153,6),optional),pair('Time',index(153,8),optional)],['die'],lvp('perish','Death',[pair('Protagonist',index(153,1),[nsubj],required),pair('Cause',index(153,4),[obl_from],required),pair('Place',index(153,6),[obl_in],optional),pair('Time',index(153,8),[obl_in],optional)])).
learned_sentence('GE manufactures cars.',index(154,2),'Manufacturing',[pair('Producer',index(154,1),required),pair('Product',index(154,3),required)],['fabricate','produce'],lvp('manufacture','Manufacturing',[pair('Producer',index(154,1),[nsubj],required),pair('Product',index(154,3),[obj],required)])).
learned_sentence('GE is a manufacturer of cars.',index(155,4),'Manufacturing',[pair('Producer',index(155,1),required),pair('Product',index(155,6),required)],['maker','producer'],lvp('manufacturer','Manufacturing',[pair('Producer',index(155,1),[nsubj],required),pair('Product',index(155,6),[nmod_of],required)])).
learned_sentence('GE makes the manufacture of cars.',index(156,4),'Manufacturing',[pair('Producer',index(156,1),required),pair('Product',index(156,6),required)],['fabrication','production','manufacturing'],lvp('manufacture','Manufacturing',[pair('Producer',index(156,1),[jbo,nsubj],required),pair('Product',index(156,6),[nmod_of],required)])).
learned_sentence('John earns 3000 dollars on investment.',index(157,2),'Earnings',[pair('Earner',index(157,1),required),pair('Money',index(157,4),required),pair('Goods',index(157,6),optional)],['make','net'],lvp('earn','Earnings',[pair('Earner',index(157,1),[nsubj],required),pair('Money',index(157,4),[obj],required),pair('Goods',index(157,6),[obl_on],optional)])).
learned_sentence('John has an income of 3000 dollars on investment.',index(158,4),'Earnings',[pair('Earner',index(158,1),required),pair('Money',index(158,7),required),pair('Goods',index(158,9),optional)],['earnings','net','profit','revenue'],lvp('income','Earnings',[pair('Earner',index(158,1),[jbo,nsubj],required),pair('Money',index(158,7),[nmod_of],required),pair('Goods',index(158,9),[jbo,obl_on],optional)])).
learned_sentence('Mary beats John in a game.',index(159,2),'Beat_opponent',[pair('Winner',index(159,1),required),pair('Loser',index(159,3),required),pair('Competition',index(159,6),optional)],['defeat','demolish','prevail','upend'],lvp('beat','Beat_opponent',[pair('Winner',index(159,1),[nsubj],required),pair('Loser',index(159,3),[obj],required),pair('Competition',index(159,6),[obl_in],optional)])).
learned_sentence('Mary beats John at a game.',index(160,2),'Beat_opponent',[pair('Winner',index(160,1),required),pair('Loser',index(160,3),required),pair('Competition',index(160,6),optional)],['defeat','demolish','prevail','upend'],lvp('beat','Beat_opponent',[pair('Winner',index(160,1),[nsubj],required),pair('Loser',index(160,3),[obj],required),pair('Competition',index(160,6),[obl_at],optional)])).
learned_sentence('The defeat of Mary in a game is sad.',index(161,2),'Beat_opponent',[pair('Loser',index(161,4),required),pair('Competition',index(161,7),optional)],[],lvp('defeat','Beat_opponent',[pair('Loser',index(161,4),[nmod_of],required),pair('Competition',index(161,7),[jbusn,obl_in],optional)])).
learned_sentence('The defeat of Mary at a game is sad.',index(162,2),'Beat_opponent',[pair('Loser',index(162,4),required),pair('Competition',index(162,7),optional)],[],lvp('defeat','Beat_opponent',[pair('Loser',index(162,4),[nmod_of],required),pair('Competition',index(162,7),[jbusn,obl_at],optional)])).
learned_sentence('Mary cures the headache of Jack with a pill.',index(163,2),'Cure',[pair('Healer',index(163,1),required),pair('Patient',index(163,6),required),pair('Disease',index(163,4),required),pair('Medication',index(163,9),optional)],['alleviate','ease','heal','palliate','rehabilitate','remedy','treat'],lvp('cure','Cure',[pair('Healer',index(163,1),[nsubj],required),pair('Patient',index(163,6),[obj,nmod_of],required),pair('Disease',index(163,4),[obj],required),pair('Medication',index(163,9),[obl_with],optional)])).
learned_sentence('Mary cures Jack with a pill.',index(164,2),'Cure',[pair('Healer',index(164,1),required),pair('Patient',index(164,3),required),pair('Medication',index(164,6),optional)],['alleviate','ease','heal','palliate','rehabilitate','remedy','treat'],lvp('cure','Cure',[pair('Healer',index(164,1),[nsubj],required),pair('Patient',index(164,3),[obj],required),pair('Medication',index(164,6),[obl_with],optional)])).
learned_sentence('Mary visits Paris.',index(165,2),'Travel',[pair('Traveler',index(165,1),required),pair('Goal',index(165,3),required)],['enter'],lvp('visit','Travel',[pair('Traveler',index(165,1),[nsubj],required),pair('Goal',index(165,3),[obj],required)])).
learned_sentence('Mary arrives in Paris.',index(166,2),'Travel',[pair('Traveler',index(166,1),required),pair('Goal',index(166,4),required)],[],lvp('arrive','Travel',[pair('Traveler',index(166,1),[nsubj],required),pair('Goal',index(166,4),[obl_in],required)])).
learned_sentence('Mary arrives at Paris.',index(167,2),'Travel',[pair('Traveler',index(167,1),required),pair('Goal',index(167,4),required)],[],lvp('arrive','Travel',[pair('Traveler',index(167,1),[nsubj],required),pair('Goal',index(167,4),[obl_at],required)])).
learned_sentence('Mary comes to Paris.',index(168,2),'Travel',[pair('Traveler',index(168,1),required),pair('Goal',index(168,4),required)],['return','approach'],lvp('come','Travel',[pair('Traveler',index(168,1),[nsubj],required),pair('Goal',index(168,4),[obl_to],required)])).
learned_sentence('The arrival of Mary in Paris is delayed.',index(169,2),'Travel',[pair('Traveler',index(169,4),required),pair('Goal',index(169,6),required)],[],lvp('arrival','Travel',[pair('Traveler',index(169,4),[nmod_of],required),pair('Goal',index(169,6),[jbo,obl_in],required)])).
learned_sentence('The arrival of Mary in Paris is delayed.',index(169,2),'Travel',[pair('Traveler',index(169,4),required),pair('Goal',index(169,6),required)],[],lvp('arrival','Travel',[pair('Traveler',index(169,4),[nmod_of],required),pair('Goal',index(169,6),[jbusn,obl_in],required)])).
learned_sentence('The arrival of Mary at Paris is delayed.',index(170,2),'Travel',[pair('Traveler',index(170,4),required),pair('Goal',index(170,6),required)],[],lvp('arrival','Travel',[pair('Traveler',index(170,4),[nmod_of],required),pair('Goal',index(170,6),[jbo,obl_at],required)])).
learned_sentence('The arrival of Mary at Paris is delayed.',index(170,2),'Travel',[pair('Traveler',index(170,4),required),pair('Goal',index(170,6),required)],[],lvp('arrival','Travel',[pair('Traveler',index(170,4),[nmod_of],required),pair('Goal',index(170,6),[jbusn,obl_at],required)])).
learned_sentence('A visit of Mary to Paris is delayed.',index(171,2),'Travel',[pair('Traveler',index(171,4),required),pair('Goal',index(171,6),required)],['approach','return','entry'],lvp('visit','Travel',[pair('Traveler',index(171,4),[nmod_of],required),pair('Goal',index(171,6),[jbo,obl_to],required)])).
learned_sentence('A visit of Mary to Paris is delayed.',index(171,2),'Travel',[pair('Traveler',index(171,4),required),pair('Goal',index(171,6),required)],['approached','returned','entry'],lvp('visit','Travel',[pair('Traveler',index(171,4),[nmod_of],required),pair('Goal',index(171,6),[jbusn,obl_to],required)])).
learned_sentence('Mary leaves Paris.',index(172,2),'Travel',[pair('Traveler',index(172,1),required),pair('Source',index(172,3),required)],[],lvp('leave','Travel',[pair('Traveler',index(172,1),[nsubj],required),pair('Source',index(172,3),[obj],required)])).
learned_sentence('Mary leaves from Paris to London.',index(173,2),'Travel',[pair('Traveler',index(173,1),required),pair('Source',index(173,4),optional),pair('Goal',index(173,6),optional)],['depart','exit','vanish','escape'],lvp('leave','Travel',[pair('Traveler',index(173,1),[nsubj],required),pair('Source',index(173,4),[obl_from],optional),pair('Goal',index(173,6),[obl_to],optional)])).
learned_sentence('Mary calls John.',index(174,2),'Contacting',[pair('Communicator',index(174,1),required),pair('Addressee',index(174,3),required)],['contact','email','call_in','call_up','fax','mail','phone','reach','ring','telephone','cable'],lvp('call','Contacting',[pair('Communicator',index(174,1),[nsubj],required),pair('Addressee',index(174,3),[obj],required)])).
learned_sentence('Mary writes to John.',index(175,2),'Contacting',[pair('Communicator',index(175,1),required),pair('Addressee',index(175,4),required)],[],lvp('write','Contacting',[pair('Communicator',index(175,1),[nsubj],required),pair('Addressee',index(175,4),[obl_to],required)])).
learned_sentence('Mary makes a call to John.',index(176,4),'Contacting',[pair('Communicator',index(176,1),required),pair('Addressee',index(176,6),required)],[],lvp('call','Contacting',[pair('Communicator',index(176,1),[jbo,nsubj],required),pair('Addressee',index(176,6),[jbo,obl_to],required)])).
learned_sentence('Mary makes a contact with John.',index(177,4),'Contacting',[pair('Communicator',index(177,1),required),pair('Addressee',index(177,6),required)],[],lvp('contact','Contacting',[pair('Communicator',index(177,1),[jbo,nsubj],required),pair('Addressee',index(177,6),[jbo,obl_with],required)])).
learned_sentence('Mary protests against the government.',index(178,2),'Protest',[pair('Protester',index(178,1),required),pair('Side',index(178,5),required)],['demonstrate'],lvp('protest','Protest',[pair('Protester',index(178,1),[nsubj],required),pair('Side',index(178,5),[obl_against],required)])).
learned_sentence('Mary makes a protest against the government.',index(179,4),'Protest',[pair('Protester',index(179,1),required),pair('Side',index(179,7),required)],['demonstration'],lvp('protest','Protest',[pair('Protester',index(179,1),[jbo,nsubj],required),pair('Side',index(179,7),[jbo,obl_against],required)])).
learned_sentence('Mary submits a form to the government.',index(180,2),'Submitting_documents',[pair('Submitter',index(180,1),required),pair('Documents',index(180,4),required),pair('Authority',index(180,7),optional)],['file','turn_in','hand_in'],lvp('submit','Submitting_documents',[pair('Submitter',index(180,1),[nsubj],required),pair('Documents',index(180,4),[obj],required),pair('Authority',index(180,7),[obl_to],optional)])).
learned_sentence('John plays Hamlet in a play with Mary.',index(181,2),'Performing',[pair('Performer',index(181,1),required),pair('Role',index(181,3),optional),pair('Performance',index(181,6),optional),pair('Costar',index(181,8),optional)],['star','feature'],lvp('play','Performing',[pair('Performer',index(181,1),[nsubj],required),pair('Role',index(181,3),[obj],optional),pair('Performance',index(181,6),[obl_in],optional),pair('Costar',index(181,8),[obl_with],optional)])).
learned_sentence('John plays the role of Hamlet in a play with Mary.',index(182,2),'Performing',[pair('Performer',index(182,1),required),pair('Role',index(182,6),optional),pair('Performance',index(182,9),optional),pair('Costar',index(182,11),optional)],['star','feature'],lvp('play','Performing',[pair('Performer',index(182,1),[nsubj],required),pair('Role',index(182,6),[obj,nmod_of],optional),pair('Performance',index(182,9),[obl_in],optional),pair('Costar',index(182,11),[obl_with],optional)])).
learned_sentence('John acts as Hamlet in a play with Mary.',index(183,2),'Performing',[pair('Performer',index(183,1),required),pair('Role',index(183,4),optional),pair('Performance',index(183,7),optional),pair('Costar',index(183,9),optional)],['appear'],lvp('act','Performing',[pair('Performer',index(183,1),[nsubj],required),pair('Role',index(183,4),[obl_as],optional),pair('Performance',index(183,7),[obl_in],optional),pair('Costar',index(183,9),[obl_with],optional)])).
learned_sentence('John co-stars with Mary in a play.',index(184,2),'Performing',[pair('Performer',index(184,1),required),pair('Performance',index(184,7),optional),pair('Costar',index(184,4),optional)],[],lvp('co_star','Performing',[pair('Performer',index(184,1),[nsubj],required),pair('Performance',index(184,7),[obl_in],optional),pair('Costar',index(184,4),[obl_with],optional)])).
learned_sentence('The police release a suspect from prison.',index(185,3),'Releasing_from_custody',[pair('Authorities',index(185,2),required),pair('Suspect',index(185,5),required),pair('Place',index(185,7),optional)],['set_free','let_go'],lvp('release','Releasing_from_custody',[pair('Authorities',index(185,2),[nsubj],required),pair('Suspect',index(185,5),[obj],required),pair('Place',index(185,7),[obl_from],optional)])).
learned_sentence('Mary is released from a prison.',index(186,3),'Releasing_from_custody',[pair('Suspect',index(186,1),required),pair('Place',index(186,6),required)],[],lvp('release','Releasing_from_custody',[pair('Suspect',index(186,1),[obj],required),pair('Place',index(186,6),[obl_from],required)])).
learned_sentence('Mary is released from a prison.',index(186,3),'Releasing_from_custody',[pair('Suspect',index(186,1),required),pair('Place',index(186,6),required)],[],lvp('released','Releasing_from_custody',[pair('Suspect',index(186,1),[nsubj],required),pair('Place',index(186,6),[obl_from],required)])).
learned_sentence('Mary signs a contract.',index(187,2),'Sign_agreement',[pair('Signatory',index(187,1),optional),pair('Agreement',index(187,4),required)],[],lvp('sign','Sign_agreement',[pair('Signatory',index(187,1),[nsubj],optional),pair('Agreement',index(187,4),[obj],required)])).
learned_sentence('Mary accedes to a contract.',index(188,2),'Sign_agreement',[pair('Signatory',index(188,1),required),pair('Agreement',index(188,5),required)],[],lvp('accede','Sign_agreement',[pair('Signatory',index(188,1),[nsubj],required),pair('Agreement',index(188,5),[obl_to],required)])).
learned_sentence('Mary publishes an article with Nature.',index(189,2),'Publishing',[pair('Author',index(189,1),required),pair('Work',index(189,4),required),pair('Publisher',index(189,6),optional)],['release'],lvp('publish','Publishing',[pair('Author',index(189,1),[nsubj],required),pair('Work',index(189,4),[obj],required),pair('Publisher',index(189,6),[obl_with],optional)])).
learned_sentence('Mary publishes an article in Nature.',index(190,2),'Publishing',[pair('Author',index(190,1),required),pair('Work',index(190,4),required),pair('Publisher',index(190,6),optional)],['release'],lvp('publish','Publishing',[pair('Author',index(190,1),[nsubj],required),pair('Work',index(190,4),[obj],required),pair('Publisher',index(190,6),[obl_in],optional)])).
learned_sentence('Nature publishes an article of Mary.',index(191,2),'Publishing',[pair('Author',index(191,6),required),pair('Work',index(191,4),required),pair('Publisher',index(191,1),required)],['release'],lvp('publish','Publishing',[pair('Author',index(191,6),[obj,nmod_of],required),pair('Work',index(191,4),[obj],required),pair('Publisher',index(191,1),[nsubj],required)])).
learned_sentence('John loses 3000 dollars on investment.',index(192,2),'Losing',[pair('Owner',index(192,1),required),pair('Money',index(192,4),required),pair('Goods',index(192,6),optional)],[],lvp('lose','Losing',[pair('Owner',index(192,1),[nsubj],required),pair('Money',index(192,4),[obj],required),pair('Goods',index(192,6),[obl_on],optional)])).
learned_sentence('John has a loss of 3000 dollars on investment.',index(193,4),'Losing',[pair('Owner',index(193,1),required),pair('Money',index(193,7),required),pair('Goods',index(193,9),optional)],[],lvp('loss','Losing',[pair('Owner',index(193,1),[jbo,nsubj],required),pair('Money',index(193,7),[nmod_of],required),pair('Goods',index(193,9),[jbo,obl_on],optional)])).
learned_sentence('John loses the phone.',index(194,2),'Losing',[pair('Owner',index(194,1),required),pair('Goods',index(194,4),required)],[],lvp('lose','Losing',[pair('Owner',index(194,1),[nsubj],required),pair('Goods',index(194,4),[obj],required)])).
learned_sentence('Mary surrenders to the police on a charge of murder.',index(195,2),'Surrendering',[pair('Authorities',index(195,5),required),pair('Fugitive',index(195,1),required),pair('Charges',index(195,10),optional)],['give_up'],lvp('surrender','Surrendering',[pair('Authorities',index(195,5),[obl_to],required),pair('Fugitive',index(195,1),[nsubj],required),pair('Charges',index(195,10),[obl_on,nmod_of],optional)])).
learned_sentence('Mary writes a letter.',index(196,2),'Text_creation',[pair('Author',index(196,1),required),pair('Text',index(196,4),required)],['author','compose','draft','jot_down','pen','type','type_in','write_up'],lvp('write','Text_creation',[pair('Author',index(196,1),[nsubj],required),pair('Text',index(196,4),[obj],required)])).
learned_sentence('Mary steals a watch from John.',index(197,2),'Theft',[pair('Perpetrator',index(197,1),required),pair('Goods',index(197,4),required),pair('Victim',index(197,6),optional)],['thieve','swipe','snitch','snatch','shoplift','pilfer','pickpocket','filch','embezzle'],lvp('steal','Theft',[pair('Perpetrator',index(197,1),[nsubj],required),pair('Goods',index(197,4),[obj],required),pair('Victim',index(197,6),[obl_from],optional)])).
learned_sentence('Mary takes off the hat.',index(198,2),'Undressing',[pair('Wearer',index(198,1),required),pair('Clothing',index(198,5),required)],['kick_off','remove','slip','strip_off','pull_off','throw_off','peel_off'],lvp('take_off','Undressing',[pair('Wearer',index(198,1),[nsubj],required),pair('Clothing',index(198,5),[obj],required)])).
learned_sentence('Mary takes off the hat.',index(198,2),'Undressing',[pair('Wearer',index(198,1),required),pair('Clothing',index(198,5),required)],['kick_off','remove','slip','strip_off','pull_off','throw_off','peel_off'],lvp('take','Undressing',[pair('Wearer',index(198,1),[nsubj],required),pair('Clothing',index(198,5),[obl_off],required)])).
learned_sentence('Mary grows food.',index(199,2),'Growing_food',[pair('Grower',index(199,1),required),pair('Food',index(199,3),required)],['raise'],lvp('grow','Growing_food',[pair('Grower',index(199,1),[nsubj],required),pair('Food',index(199,3),[obj],required)])).
learned_sentence('Mary participates in an event with John.',index(200,2),'Participation',[pair('Participant',index(200,1),required),pair('Event',index(200,5),required),pair('CoParticipant',index(200,7),optional)],['engage','involve','take_part'],lvp('participate','Participation',[pair('Participant',index(200,1),[nsubj],required),pair('Event',index(200,5),[obl_in],required),pair('CoParticipant',index(200,7),[obl_with],optional)])).
learned_sentence('Mary is involved in an event with John.',index(201,3),'Participation',[pair('Participant',index(201,1),required),pair('Event',index(201,6),required),pair('CoParticipant',index(201,8),optional)],['engage'],lvp('involve','Participation',[pair('Participant',index(201,1),[obj],required),pair('Event',index(201,6),[obl_in],required),pair('CoParticipant',index(201,8),[obl_with],optional)])).
learned_sentence('Mary is involved in an event with John.',index(201,3),'Participation',[pair('Participant',index(201,1),required),pair('Event',index(201,6),required),pair('CoParticipant',index(201,8),optional)],['engaged'],lvp('involved','Participation',[pair('Participant',index(201,1),[nsubj],required),pair('Event',index(201,6),[obl_in],required),pair('CoParticipant',index(201,8),[obl_with],optional)])).
learned_sentence('Mary borrows a book from John.',index(202,2),'Borrow_lend',[pair('Borrower',index(202,1),required),pair('Theme',index(202,4),required),pair('Lender',index(202,6),optional)],[],lvp('borrow','Borrow_lend',[pair('Borrower',index(202,1),[nsubj],required),pair('Theme',index(202,4),[obj],required),pair('Lender',index(202,6),[obl_from],optional)])).
learned_sentence('Mary lends a book to John.',index(203,2),'Borrow_lend',[pair('Borrower',index(203,6),optional),pair('Theme',index(203,4),required),pair('Lender',index(203,1),required)],[],lvp('lend','Borrow_lend',[pair('Borrower',index(203,6),[obl_to],optional),pair('Theme',index(203,4),[obj],required),pair('Lender',index(203,1),[nsubj],required)])).
learned_sentence('KFC is a cheap American restaurant in the US.',index(204,6),'Restaurant',[pair('Restaurant_name',index(204,1),required),pair('Price',index(204,4),optional),pair('Cuisine',index(204,5),optional),pair('Place',index(204,9),optional)],['eating_place','food_place','dining_place'],lvp('restaurant','Restaurant',[pair('Restaurant_name',index(204,1),[nsubj],required),pair('Price',index(204,4),[amod],optional),pair('Cuisine',index(204,5),[amod],optional),pair('Place',index(204,9),[obl_in],optional)])).
learned_sentence('Mary cures the headache with a pill.',index(205,2),'Cure',[pair('Healer',index(205,1),required),pair('Disease',index(205,4),required),pair('Medication',index(205,7),optional)],['alleviate','ease','heal','palliate','rehabilitate','remedy','treat'],lvp('cure','Cure',[pair('Healer',index(205,1),[nsubj],required),pair('Disease',index(205,4),[obj],required),pair('Medication',index(205,7),[obl_with],optional)])).
learned_sentence('Mary publishes an article in Nature.',index(206,2),'Publishing',[pair('Author',index(206,1),required),pair('Work',index(206,4),required),pair('Publisher',index(206,6),optional)],['release'],lvp('publish','Publishing',[pair('Author',index(206,1),[nsubj],required),pair('Work',index(206,4),[obj],required),pair('Publisher',index(206,6),[obl_in],optional)])).
learned_sentence('Mary publishes an article on Waltz.',index(207,2),'Publishing',[pair('Author',index(207,1),required),pair('Work',index(207,4),required),pair('Topic',index(207,6),optional)],['release'],lvp('publish','Publishing',[pair('Author',index(207,1),[nsubj],required),pair('Work',index(207,4),[obj],required),pair('Topic',index(207,6),[obl_on],optional)])).
learned_sentence('John is employed by IBM in London.',index(208,3),'Being_employed',[pair('Employee',index(208,1),required),pair('Employer',index(208,5),required),pair('Place',index(208,7),optional)],[],lvp('employ','Being_employed',[pair('Employee',index(208,1),[obj],required),pair('Employer',index(208,5),[obl_by],required),pair('Place',index(208,7),[obl_in],optional)])).
learned_sentence('John is employed by IBM in London.',index(208,3),'Being_employed',[pair('Employee',index(208,1),required),pair('Employer',index(208,5),required),pair('Place',index(208,7),optional)],[],lvp('employ','Being_employed',[pair('Employee',index(208,1),[obj],required),pair('Employer',index(208,5),[nsubj],required),pair('Place',index(208,7),[obl_in],optional)])).
learned_sentence('John is employed by IBM in London.',index(208,3),'Being_employed',[pair('Employee',index(208,1),required),pair('Employer',index(208,5),required),pair('Place',index(208,7),optional)],[],lvp('employed','Being_employed',[pair('Employee',index(208,1),[nsubj],required),pair('Employer',index(208,5),[obl_by],required),pair('Place',index(208,7),[obl_in],optional)])).
learned_sentence('China imports beef from Japan.',index(209,2),'Import_export',[pair('Importer',index(209,1),optional),pair('Exporter',index(209,5),optional),pair('Goods',index(209,3),required)],[],lvp('import','Import_export',[pair('Importer',index(209,1),[nsubj],optional),pair('Exporter',index(209,5),[obl_from],optional),pair('Goods',index(209,3),[obj],required)])).
learned_sentence('Japan exports beef to China.',index(210,2),'Import_export',[pair('Importer',index(210,5),optional),pair('Exporter',index(210,1),optional),pair('Goods',index(210,3),required)],[],lvp('export','Import_export',[pair('Importer',index(210,5),[obl_to],optional),pair('Exporter',index(210,1),[nsubj],optional),pair('Goods',index(210,3),[obj],required)])).
learned_sentence('Mary schedules a meeting in the offxice.',index(211,2),'Scheduling',[pair('Agent',index(211,1),required),pair('Event',index(211,4),required),pair('Place',index(211,7),optional)],['arrange','set_up'],lvp('schedule','Scheduling',[pair('Agent',index(211,1),[nsubj],required),pair('Event',index(211,4),[obj],required),pair('Place',index(211,7),[obl_in],optional)])).
learned_sentence('Mary schedules a meeting at the school.',index(212,2),'Scheduling',[pair('Agent',index(212,1),required),pair('Event',index(212,4),required),pair('Place',index(212,7),optional)],['arrange','set_up'],lvp('schedule','Scheduling',[pair('Agent',index(212,1),[nsubj],required),pair('Event',index(212,4),[obj],required),pair('Place',index(212,7),[obl_at],optional)])).
learned_sentence('Mary schedules a trip to London.',index(213,2),'Scheduling',[pair('Agent',index(213,1),required),pair('Event',index(213,4),required),pair('Place',index(213,6),optional)],['arrange','set_up'],lvp('schedule','Scheduling',[pair('Agent',index(213,1),[nsubj],required),pair('Event',index(213,4),[obj],required),pair('Place',index(213,6),[obl_to],optional)])).
learned_sentence('Mary inhabits the place.',index(214,2),'Residence',[pair('Resident',index(214,1),required),pair('Location',index(214,4),required)],[],lvp('inhabit','Residence',[pair('Resident',index(214,1),[nsubj],required),pair('Location',index(214,4),[obj],required)])).
learned_sentence('Mary applied for a teaching job.',index(215,6),'Being_employed',[pair('Employee',index(215,1),required),pair('Field',index(215,5),optional)],['stint','position','work'],lvp('job','Being_employed',[pair('Employee',index(215,1),[lbo_for,nsubj],required),pair('Field',index(215,5),[compound],optional)])).
learned_sentence('Mary admits on the arrest for burglary.',index(216,5),'Arrest',[pair('Suspect',index(216,1),required),pair('Charges',index(216,7),optional)],[],lvp('arrest','Arrest',[pair('Suspect',index(216,1),[lbo_on,nsubj],required),pair('Charges',index(216,7),[lbo_on,obl_for],optional)])).
learned_sentence('Mary launches assault in John.',index(217,3),'Attack',[pair('Assailant',index(217,1),required),pair('Victim',index(217,5),required)],[],lvp('assault','Attack',[pair('Assailant',index(217,1),[jbo,nsubj],required),pair('Victim',index(217,5),[jbo,obl_in],required)])).
learned_sentence('Mary protests officials.',index(218,2),'Protest',[pair('Protester',index(218,1),required),pair('Side',index(218,3),required)],[],lvp('protest','Protest',[pair('Protester',index(218,1),[nsubj],required),pair('Side',index(218,3),[obj],required)])).
learned_sentence('Mary does something at the age of 16.',index(219,6),'Age',[pair('Person',index(219,1),required),pair('Age',index(219,8),required)],[],lvp('age','Age',[pair('Person',index(219,1),[lbo_at,nsubj],required),pair('Age',index(219,8),[nmod_of],required)])).
learned_sentence('Mary recieves a call from John.',index(220,4),'Contacting',[pair('Communicator',index(220,6),required),pair('Addressee',index(220,1),required)],[],lvp('call','Contacting',[pair('Communicator',index(220,6),[jbo,obl_from],required),pair('Addressee',index(220,1),[jbo,nsubj],required)])).
learned_sentence('Mary is a resident at a street.',index(221,4),'Residence',[pair('Resident',index(221,1),required),pair('Location',index(221,7),required)],['occupant','dweller','inhabitant'],lvp('resident','Residence',[pair('Resident',index(221,1),[nsubj],required),pair('Location',index(221,7),[obl_at],required)])).
