:- dynamic(learned_sentence/6).

learned_sentence('A person administers something.',index(1,3),'Cure',[pair('Healer',index(1,2),required),pair('Medication',index(1,4),required)],[],lvp('administer','Cure',[pair('Healer',index(1,2),[nsubj],required),pair('Medication',index(1,4),[obj],required)])).
learned_sentence('A person undergoes something for a period.',index(2,3),'Undergoing',[pair('Entity',index(2,2),required),pair('Event',index(2,4),required),pair('Duration',index(2,7),optional)],[],lvp('undergo','Undergoing',[pair('Entity',index(2,2),[nsubj],required),pair('Event',index(2,4),[obj],required),pair('Duration',index(2,7),[obl_for],optional)])).
learned_sentence('A person is a young child.',index(3,6),'People_by_age',[pair('Person',index(3,2),required),pair('Type',index(3,6),required)],[],lvp('child','People_by_age',[pair('Person',index(3,2),[nsubj],required),pair('Type',index(3,6),[self],required)])).
learned_sentence('A person has a severe fever.',index(4,3),'Medical_conditions',[pair('Patient',index(4,2),required),pair('Degree',index(4,5),optional),pair('Aliment',index(4,6),required)],[],lvp('have','Medical_conditions',[pair('Patient',index(4,2),[nsubj],required),pair('Degree',index(4,5),[obj,amod],optional),pair('Aliment',index(4,6),[obj],required)])).
learned_sentence('A person considers something.',index(5,3),'Cogitation',[pair('Cognizer',index(5,2),required),pair('Topic',index(5,4),required)],[],lvp('consider','Cogitation',[pair('Cognizer',index(5,2),[nsubj],required),pair('Topic',index(5,4),[obj],required)])).
learned_sentence('A person assesses something.',index(6,3),'Assessing',[pair('Assessor',index(6,2),required),pair('Feature',index(6,4),required)],[],lvp('assess','Assessing',[pair('Assessor',index(6,2),[nsubj],required),pair('Feature',index(6,4),[obj],required)])).
learned_sentence('A person assesses the ability to retain something.',index(7,3),'Assessing',[pair('Assessor',index(7,2),required),pair('Feature',index(7,5),required),pair('Ability',index(7,8),required)],[],lvp('assess','Assessing',[pair('Assessor',index(7,2),[nsubj],required),pair('Feature',index(7,5),[obj],required),pair('Ability',index(7,8),[obj,acl,obj],required)])).
learned_sentence('A person is sufficiently ill.',index(8,5),'Medical_conditions',[pair('Patient',index(8,2),required),pair('Degree',index(8,4),required),pair('Aliment',index(8,5),required)],[],lvp('ill','Medical_conditions',[pair('Patient',index(8,2),[nsubj],required),pair('Degree',index(8,4),[advmod],required),pair('Aliment',index(8,5),[self],required)])).
learned_sentence('A person analyzes the person\'s culture of a urine specimen that is obtained by SPA, transurethral catheterization, or a convenient method.',index(9,3),'Scrutiny',[pair('Cognizer',index(9,2),required),pair('Patient',index(9,5),required),pair('Specimen',index(9,10),required),pair('Method',index(9,16),required),pair('Method',index(9,18),optional),pair('Method',index(9,24),optional)],[],lvp('analyze','Scrutiny',[pair('Cognizer',index(9,2),[nsubj],required),pair('Patient',index(9,5),[obj,nmod_poss],required),pair('Specimen',index(9,10),[obj,nmod_of,compound],required),pair('Method',index(9,16),[obj,nmod_of,acl_relcl,obl_by],required),pair('Method',index(9,18),[obj,nmod_of,acl_relcl,obl_by,conj,compound],optional),pair('Method',index(9,24),[obj,nmod_of,acl_relcl,obl_by,conj],optional)])).
learned_sentence('A person analyzes the person\'s culture of a urine specimen that is obtained by SPA, transurethral catheterization, or a convenient method.',index(9,3),'Scrutiny',[pair('Cognizer',index(9,2),required),pair('Patient',index(9,5),required),pair('Specimen',index(9,10),required),pair('Method',index(9,16),required),pair('Method',index(9,18),optional),pair('Method',index(9,24),optional)],[],lvp('analyze','Scrutiny',[pair('Cognizer',index(9,2),[nsubj],required),pair('Patient',index(9,5),[obj,nmod_poss],required),pair('Specimen',index(9,10),[obj,nmod_of,compound],required),pair('Method',index(9,16),[obj,nmod_of,acl_relcl,nsubj],required),pair('Method',index(9,18),[obj,nmod_of,acl_relcl,nsubj,conj,compound],optional),pair('Method',index(9,24),[obj,nmod_of,acl_relcl,nsubj,conj],optional)])).
learned_sentence('A person analyzes the person\'s culture of a urine specimen.',index(10,3),'Scrutiny',[pair('Cognizer',index(10,2),required),pair('Patient',index(10,5),required),pair('Specimen',index(10,10),required)],[],lvp('analyze','Scrutiny',[pair('Cognizer',index(10,2),[nsubj],required),pair('Patient',index(10,5),[obj,nmod_poss],required),pair('Specimen',index(10,10),[obj,nmod_of,compound],required)])).
learned_sentence('A person\'s culture of a urine specimen is obtained by a method.',index(11,10),'Obtaining',[pair('Patient',index(11,2),required),pair('Specimen',index(11,7),required),pair('Method',index(11,13),required)],[],lvp('obtain','Obtaining',[pair('Patient',index(11,2),[obj,nmod_poss],required),pair('Specimen',index(11,7),[obj,nmod_of,compound],required),pair('Method',index(11,13),[obl_by],required)])).
learned_sentence('A person\'s culture of a urine specimen is obtained by a method.',index(11,10),'Obtaining',[pair('Patient',index(11,2),required),pair('Specimen',index(11,7),required),pair('Method',index(11,13),required)],[],lvp('obtain','Obtaining',[pair('Patient',index(11,2),[obj,nmod_poss],required),pair('Specimen',index(11,7),[obj,nmod_of,compound],required),pair('Method',index(11,13),[nsubj],required)])).
learned_sentence('A person\'s culture of a urine specimen is obtained by a method.',index(11,10),'Obtaining',[pair('Patient',index(11,2),required),pair('Specimen',index(11,7),required),pair('Method',index(11,13),required)],[],lvp('obtained','Obtaining',[pair('Patient',index(11,2),[nsubj,nmod_poss],required),pair('Specimen',index(11,7),[nsubj,nmod_of,compound],required),pair('Method',index(11,13),[obl_by],required)])).
learned_sentence('The analysis of the person\'s culture of urine specimen suggests something.',index(12,11),'Suggestion',[pair('Patient',index(12,5),required),pair('Specimen',index(12,9),required),pair('Ailment',index(12,12),required)],[],lvp('suggest','Suggestion',[pair('Patient',index(12,5),[nsubj,nmod_of,nmod_poss],required),pair('Specimen',index(12,9),[nsubj,nmod_of,nmod_of,compound],required),pair('Ailment',index(12,12),[obj],required)])).
learned_sentence('The analysis of the person\'s culture of urine specimen confirms something.',index(13,11),'Confirmation',[pair('Patient',index(13,5),required),pair('Specimen',index(13,9),required),pair('Ailment',index(13,12),required)],[],lvp('confirm','Confirmation',[pair('Patient',index(13,5),[nsubj,nmod_of,nmod_poss],required),pair('Specimen',index(13,9),[nsubj,nmod_of,nmod_of,compound],required),pair('Ailment',index(13,12),[obj],required)])).
learned_sentence('The analysis of the person\'s culture of urine specimen excludes something.',index(14,11),'Exclusion',[pair('Patient',index(14,5),required),pair('Specimen',index(14,9),required),pair('Ailment',index(14,12),required)],[],lvp('exclude','Exclusion',[pair('Patient',index(14,5),[nsubj,nmod_of,nmod_poss],required),pair('Specimen',index(14,9),[nsubj,nmod_of,nmod_of,compound],required),pair('Ailment',index(14,12),[obj],required)])).
learned_sentence('A person is toxic.',index(15,4),'Toxic_substance',[pair('Victim',index(15,2),required)],[],lvp('toxic','Toxic_substance',[pair('Victim',index(15,2),[nsubj],required)])).
learned_sentence('A person is dehydrated.',index(16,4),'Cause_to_be_dry',[pair('Dryee',index(16,2),required)],[],lvp('dehydrate','Cause_to_be_dry',[pair('Dryee',index(16,2),[obj],required)])).
learned_sentence('A person is dehydrated.',index(16,4),'Cause_to_be_dry',[pair('Dryee',index(16,2),required)],[],lvp('dehydrated','Cause_to_be_dry',[pair('Dryee',index(16,2),[nsubj],required)])).
learned_sentence('A person is able to retain something.',index(17,6),'Retaining',[pair('Agent',index(17,2),required),pair('Theme',index(17,7),required)],[],lvp('retain','Retaining',[pair('Agent',index(17,2),[pmocx,nsubj],required),pair('Theme',index(17,7),[obj],required)])).
learned_sentence('A person administers a parenteral or oral antimicrobial therapy.',index(18,3),'Cure',[pair('Healer',index(18,2),required),pair('Medication',index(18,5),required),pair('Medication',index(18,7),required)],[],lvp('administer','Cure',[pair('Healer',index(18,2),[nsubj],required),pair('Medication',index(18,5),[obj,compound],required),pair('Medication',index(18,7),[obj,compound,conj],required)])).
learned_sentence('A person shows a response of a therapy.',index(19,5),'Responding',[pair('Person',index(19,2),required),pair('Theme',index(19,8),required)],[],lvp('response','Responding',[pair('Person',index(19,2),[jbo,nsubj],required),pair('Theme',index(19,8),[nmod_of],required)])).
learned_sentence('A person reevaluates another person.',index(20,3),'Evaluation',[pair('Healer',index(20,2),required),pair('Patient',index(20,5),required)],[],lvp('reevaluate','Evaluation',[pair('Healer',index(20,2),[nsubj],required),pair('Patient',index(20,5),[obj],required)])).
learned_sentence('A person administers an oral antimicrobial therapy that lasts at least 1 day.',index(21,3),'Cure',[pair('Entity',index(21,2),required),pair('Medication',index(21,5),required),pair('Limit',index(21,11),required),pair('Days',index(21,12),required)],[],lvp('administer','Cure',[pair('Entity',index(21,2),[nsubj],required),pair('Medication',index(21,5),[obj,amod],required),pair('Limit',index(21,11),[obj,acl_relcl,obl_at],required),pair('Days',index(21,12),[obj,acl_relcl,obl_tmod,nummod],required)])).
learned_sentence('A person administers an oral antimicrobial therapy that lasts at most 1 day.',index(22,3),'Cure',[pair('Entity',index(22,2),required),pair('Medication',index(22,5),required),pair('Limit',index(22,11),required),pair('Days',index(22,12),required)],[],lvp('administer','Cure',[pair('Entity',index(22,2),[nsubj],required),pair('Medication',index(22,5),[obj,amod],required),pair('Limit',index(22,11),[obj,acl_relcl,obl_at,amod],required),pair('Days',index(22,12),[obj,acl_relcl,obl_at,nummod],required)])).
learned_sentence('The therapy of the patient is completed.',index(23,7),'Activity_finish',[pair('Activity',index(23,2),required),pair('Patient',index(23,5),required)],[],lvp('complete','Activity_finish',[pair('Activity',index(23,2),[obj],required),pair('Patient',index(23,5),[obj,nmod_of],required)])).
learned_sentence('The therapy of the patient is completed.',index(23,7),'Activity_finish',[pair('Activity',index(23,2),required),pair('Patient',index(23,5),required)],[],lvp('completed','Activity_finish',[pair('Activity',index(23,2),[nsubj],required),pair('Patient',index(23,5),[nsubj,nmod_of],required)])).
learned_sentence('A person performs something or another thing promptly.',index(24,3),'Intentionally_act',[pair('Agent',index(24,2),required),pair('Study',index(24,4),required),pair('Study',index(24,7),optional),pair('Study_property',index(24,8),optional)],[],lvp('perform','Intentionally_act',[pair('Agent',index(24,2),[nsubj],required),pair('Study',index(24,4),[obj],required),pair('Study',index(24,7),[obj,conj],optional),pair('Study_property',index(24,8),[advmod],optional)])).
