:- dynamic(learned_sentence/6).

learned_sentence('A person is bored.',index(1,4),'Feeling',[pair('Person',index(1,2),required),pair('Feeling',index(1,4),required)],['hungry','thirsty','tired'],lvp('bored','Feeling',[pair('Person',index(1,2),[nsubj],required),pair('Feeling',index(1,4),[self],required)])).
learned_sentence('A person is bored.',index(1,4),'Feeling',[pair('Person',index(1,2),required),pair('Feeling',index(1,4),required)],['hungry','thirsty','tire'],lvp('bore','Feeling',[pair('Person',index(1,2),[obj],required),pair('Feeling',index(1,4),[self],required)])).
learned_sentence('A person goes to a place because of a feeling.',index(2,3),'Travel',[pair('Person',index(2,2),required),pair('Place',index(2,6),required),pair('Reason',index(2,10),optional)],['travel','journey','move'],lvp('go','Travel',[pair('Person',index(2,2),[nsubj],required),pair('Place',index(2,6),[obl_to],required),pair('Reason',index(2,10),[obl_because],optional)])).
learned_sentence('A person got something because of a feeling.',index(3,3),'Obtain',[pair('Person',index(3,2),required),pair('Theme',index(3,4),required),pair('Reason',index(3,8),optional)],['grab','take','pick_up','obtain'],lvp('get','Obtain',[pair('Person',index(3,2),[nsubj],required),pair('Theme',index(3,4),[obj],required),pair('Reason',index(3,8),[obl_because],optional)])).
learned_sentence('Where did the person go?',index(4,1),'Travel',[pair('Person',index(4,4),required),pair('Place',index(4,1),required)],[],lvp('where','Travel',[pair('Person',index(4,4),[domvda,nsubj],required),pair('Place',index(4,1),[self],required)])).
learned_sentence('Why did the person go to a place?',index(5,5),'Travel',[pair('Person',index(5,4),required),pair('Place',index(5,8),required),pair('Reason',index(5,1),required)],[],lvp('go','Travel',[pair('Person',index(5,4),[nsubj],required),pair('Place',index(5,8),[obl_to],required),pair('Reason',index(5,1),[advmod],required)])).
learned_sentence('Why did the person get the thing?',index(6,5),'Obtain',[pair('Person',index(6,4),required),pair('Theme',index(6,7),required),pair('Reason',index(6,1),required)],[],lvp('get','Obtain',[pair('Person',index(6,4),[nsubj],required),pair('Theme',index(6,7),[obj],required),pair('Reason',index(6,1),[advmod],required)])).
learned_sentence('A person has a feeling.',index(7,5),'Feeling',[pair('Person',index(7,2),required),pair('Feeling',index(7,5),required)],[],lvp('feeling','Feeling',[pair('Person',index(7,2),[jbo,nsubj],required),pair('Feeling',index(7,5),[self],required)])).
