:- dynamic(learned_sentence/6).

learned_sentence('Actors appear in the films.',index(1,2),'Movie',[pair('Movie_name',index(1,5),required),pair('Actor',index(1,1),required)],['act','star'],lvp('appear','Movie',[pair('Movie_name',index(1,5),[obl_in],required),pair('Actor',index(1,1),[nsubj],required)])).
learned_sentence('Actors are someones in the films.',index(2,1),'Movie',[pair('Movie_name',index(2,6),required),pair('Actor',index(2,1),required)],[],lvp('actor','Movie',[pair('Movie_name',index(2,6),[jbusn,obl_in],required),pair('Actor',index(2,1),[self],required)])).
learned_sentence('Director\'s films.',index(3,1),'Movie',[pair('Movie_name',index(3,3),required),pair('Director',index(3,1),required)],[],lvp('director','Movie',[pair('Movie_name',index(3,3),[ssop_domn],required),pair('Director',index(3,1),[self],required)])).
learned_sentence('Directors directed the films.',index(4,2),'Movie',[pair('Movie_name',index(4,4),required),pair('Director',index(4,1),required)],['co_direct'],lvp('direct','Movie',[pair('Movie_name',index(4,4),[obj],required),pair('Director',index(4,1),[nsubj],required)])).
learned_sentence('Films are directed by directors.',index(5,3),'Movie',[pair('Movie_name',index(5,1),required),pair('Director',index(5,5),required)],[],lvp('direct','Movie',[pair('Movie_name',index(5,1),[obj],required),pair('Director',index(5,5),[obl_by],required)])).
learned_sentence('Films are directed by directors.',index(5,3),'Movie',[pair('Movie_name',index(5,1),required),pair('Director',index(5,5),required)],[],lvp('direct','Movie',[pair('Movie_name',index(5,1),[obj],required),pair('Director',index(5,5),[nsubj],required)])).
learned_sentence('Films are directed by directors.',index(5,3),'Movie',[pair('Movie_name',index(5,1),required),pair('Director',index(5,5),required)],[],lvp('directed','Movie',[pair('Movie_name',index(5,1),[nsubj],required),pair('Director',index(5,5),[obl_by],required)])).
learned_sentence('Films are starred by actors.',index(6,3),'Movie',[pair('Movie_name',index(6,1),required),pair('Actor',index(6,5),required)],['act'],lvp('star','Movie',[pair('Movie_name',index(6,1),[obj],required),pair('Actor',index(6,5),[obl_by],required)])).
learned_sentence('Films are starred by actors.',index(6,3),'Movie',[pair('Movie_name',index(6,1),required),pair('Actor',index(6,5),required)],['act'],lvp('star','Movie',[pair('Movie_name',index(6,1),[obj],required),pair('Actor',index(6,5),[nsubj],required)])).
learned_sentence('Films are starred by actors.',index(6,3),'Movie',[pair('Movie_name',index(6,1),required),pair('Actor',index(6,5),required)],['act'],lvp('starred','Movie',[pair('Movie_name',index(6,1),[nsubj],required),pair('Actor',index(6,5),[obl_by],required)])).
learned_sentence('Films are starred by the actors in the films.',index(7,6),'Movie',[pair('Movie_name',index(7,9),required),pair('Actor',index(7,6),required)],[],lvp('actor','Movie',[pair('Movie_name',index(7,9),[lbo_by,obl_in],required),pair('Actor',index(7,6),[self],required)])).
learned_sentence('Films are starred by the actors in the films.',index(7,6),'Movie',[pair('Movie_name',index(7,9),required),pair('Actor',index(7,6),required)],[],lvp('actor','Movie',[pair('Movie_name',index(7,9),[jbusn,obl_in],required),pair('Actor',index(7,6),[self],required)])).
learned_sentence('Films starred actors.',index(8,2),'Movie',[pair('Movie_name',index(8,1),required),pair('Actor',index(8,3),required)],[],lvp('star','Movie',[pair('Movie_name',index(8,1),[nsubj],required),pair('Actor',index(8,3),[obj],required)])).
learned_sentence('Films share actors with the films.',index(9,3),'Movie',[pair('Movie_name',index(9,6),required),pair('Actor',index(9,3),required)],[],lvp('actor','Movie',[pair('Movie_name',index(9,6),[jbo,obl_with],required),pair('Actor',index(9,3),[self],required)])).
learned_sentence('Films share actors with the films.',index(10,3),'Movie',[pair('Movie_name',index(10,1),required),pair('Actor',index(10,3),required)],[],lvp('actor','Movie',[pair('Movie_name',index(10,1),[jbo,nsubj],required),pair('Actor',index(10,3),[self],required)])).
learned_sentence('Films share actors with the films.',index(11,2),'Inequality',[pair('Entity_1',index(11,1),required),pair('Entity_2',index(11,6),required)],[],lvp('share','Inequality',[pair('Entity_1',index(11,1),[nsubj],required),pair('Entity_2',index(11,6),[obl_with],required)])).
learned_sentence('Films share directors with the films.',index(12,3),'Movie',[pair('Movie_name',index(12,6),required),pair('Director',index(12,3),required)],[],lvp('director','Movie',[pair('Movie_name',index(12,6),[jbo,obl_with],required),pair('Director',index(12,3),[self],required)])).
learned_sentence('Films share directors with the films.',index(13,3),'Movie',[pair('Movie_name',index(13,1),required),pair('Director',index(13,3),required)],[],lvp('director','Movie',[pair('Movie_name',index(13,1),[jbo,nsubj],required),pair('Director',index(13,3),[self],required)])).
learned_sentence('Films share writers with the films.',index(14,3),'Movie',[pair('Movie_name',index(14,6),required),pair('Writer',index(14,3),required)],[],lvp('writer','Movie',[pair('Movie_name',index(14,6),[jbo,obl_with],required),pair('Writer',index(14,3),[self],required)])).
learned_sentence('Films share writers with the films.',index(15,3),'Movie',[pair('Movie_name',index(15,1),required),pair('Writer',index(15,3),required)],[],lvp('writer','Movie',[pair('Movie_name',index(15,1),[jbo,nsubj],required),pair('Writer',index(15,3),[self],required)])).
learned_sentence('Films were in the genres.',index(16,5),'Movie',[pair('Movie_name',index(16,1),required),pair('Genre',index(16,5),required)],[],lvp('genre','Movie',[pair('Movie_name',index(16,1),[nsubj],required),pair('Genre',index(16,5),[self],required)])).
learned_sentence('Films were released in 2021.',index(17,3),'Movie',[pair('Movie_name',index(17,1),required),pair('Release_year',index(17,5),required)],[],lvp('release','Movie',[pair('Movie_name',index(17,1),[obj],required),pair('Release_year',index(17,5),[obl_in],required)])).
learned_sentence('Films were released in 2021.',index(17,3),'Movie',[pair('Movie_name',index(17,1),required),pair('Release_year',index(17,5),required)],[],lvp('released','Movie',[pair('Movie_name',index(17,1),[nsubj],required),pair('Release_year',index(17,5),[obl_in],required)])).
learned_sentence('Film whose actors appear in the films.',index(18,3),'Movie',[pair('Movie_name',index(18,1),required),pair('Actor',index(18,3),required)],[],lvp('actor','Movie',[pair('Movie_name',index(18,1),[jbusn,lcler_lca],required),pair('Actor',index(18,3),[self],required)])).
learned_sentence('Film whose actors also appear in the films.',index(19,4),'Inequality',[pair('Entity_1',index(19,1),required),pair('Entity_2',index(19,8),required)],['act','star'],lvp('also','Inequality',[pair('Entity_1',index(19,1),[domvda,lcler_lca],required),pair('Entity_2',index(19,8),[domvda,obl_in],required)])).
learned_sentence('Film whose directors directed the films.',index(20,3),'Movie',[pair('Movie_name',index(20,1),required),pair('Director',index(20,3),required)],[],lvp('director','Movie',[pair('Movie_name',index(20,1),[jbusn,lcler_lca],required),pair('Director',index(20,3),[self],required)])).
learned_sentence('Film whose directors also directed the films.',index(21,4),'Inequality',[pair('Entity_1',index(21,1),required),pair('Entity_2',index(21,7),required)],['write'],lvp('also','Inequality',[pair('Entity_1',index(21,1),[domvda,lcler_lca],required),pair('Entity_2',index(21,7),[domvda,obj],required)])).
learned_sentence('Film whose writers wrote the films.',index(22,3),'Movie',[pair('Movie_name',index(22,1),required),pair('Writer',index(22,3),required)],['screenwriter','scriptwriter'],lvp('writer','Movie',[pair('Movie_name',index(22,1),[jbusn,lcler_lca],required),pair('Writer',index(22,3),[self],required)])).
learned_sentence('Films are written by writers.',index(23,3),'Movie',[pair('Movie_name',index(23,1),required),pair('Writer',index(23,5),required)],[],lvp('write','Movie',[pair('Movie_name',index(23,1),[obj],required),pair('Writer',index(23,5),[obl_by],required)])).
learned_sentence('Films are written by writers.',index(23,3),'Movie',[pair('Movie_name',index(23,1),required),pair('Writer',index(23,5),required)],[],lvp('write','Movie',[pair('Movie_name',index(23,1),[obj],required),pair('Writer',index(23,5),[nsubj],required)])).
learned_sentence('Films are written by writers.',index(23,3),'Movie',[pair('Movie_name',index(23,1),required),pair('Writer',index(23,5),required)],[],lvp('written','Movie',[pair('Movie_name',index(23,1),[nsubj],required),pair('Writer',index(23,5),[obl_by],required)])).
learned_sentence('Film actors.',index(24,2),'Movie',[pair('Movie_name',index(24,1),required),pair('Actor',index(24,2),required)],[],lvp('actor','Movie',[pair('Movie_name',index(24,1),[compound],required),pair('Actor',index(24,2),[self],required)])).
learned_sentence('Film directors.',index(25,2),'Movie',[pair('Movie_name',index(25,1),required),pair('Director',index(25,2),required)],[],lvp('director','Movie',[pair('Movie_name',index(25,1),[compound],required),pair('Director',index(25,2),[self],required)])).
learned_sentence('Film writers.',index(26,2),'Movie',[pair('Movie_name',index(26,1),required),pair('Writer',index(26,2),required)],['screenwriter','scriptwriter'],lvp('writer','Movie',[pair('Movie_name',index(26,1),[compound],required),pair('Writer',index(26,2),[self],required)])).
learned_sentence('Genres of the films.',index(27,1),'Movie',[pair('Movie_name',index(27,4),required),pair('Genre',index(27,1),required)],[],lvp('genre','Movie',[pair('Movie_name',index(27,4),[nmod_of],required),pair('Genre',index(27,1),[self],required)])).
learned_sentence('Languages are English in the films.',index(28,1),'Movie',[pair('Movie_name',index(28,6),required),pair('Language',index(28,3),required)],[],lvp('language','Movie',[pair('Movie_name',index(28,6),[jbusn,obl_in],required),pair('Language',index(28,3),[jbusn],required)])).
learned_sentence('Languages are spoken in the films.',index(29,3),'Movie',[pair('Movie_name',index(29,6),required),pair('Language',index(29,1),required)],[],lvp('speak','Movie',[pair('Movie_name',index(29,6),[obl_in],required),pair('Language',index(29,1),[obj],required)])).
learned_sentence('Languages are spoken in the films.',index(29,3),'Movie',[pair('Movie_name',index(29,6),required),pair('Language',index(29,1),required)],[],lvp('spoken','Movie',[pair('Movie_name',index(29,6),[obl_in],required),pair('Language',index(29,1),[nsubj],required)])).
learned_sentence('Films are the genres.',index(30,4),'Movie',[pair('Movie_name',index(30,1),required),pair('Genre',index(30,4),required)],['type'],lvp('genre','Movie',[pair('Movie_name',index(30,1),[nsubj],required),pair('Genre',index(30,4),[self],required)])).
learned_sentence('Films fall under the genres.',index(31,5),'Movie',[pair('Movie_name',index(31,1),required),pair('Genre',index(31,5),required)],[],lvp('genre','Movie',[pair('Movie_name',index(31,1),[jbo,nsubj],required),pair('Genre',index(31,5),[self],required)])).
learned_sentence('Films fall under the genres.',index(31,5),'Movie',[pair('Movie_name',index(31,1),required),pair('Genre',index(31,5),required)],[],lvp('genre','Movie',[pair('Movie_name',index(31,1),[lbo_under,nsubj],required),pair('Genre',index(31,5),[self],required)])).
learned_sentence('Films are in the languages.',index(32,5),'Movie',[pair('Movie_name',index(32,1),required),pair('Language',index(32,5),required)],[],lvp('language','Movie',[pair('Movie_name',index(32,1),[nsubj],required),pair('Language',index(32,5),[self],required)])).
learned_sentence('Release dates of the films.',index(33,2),'Movie',[pair('Movie_name',index(33,5),required),pair('Release_year',index(33,2),required)],['year'],lvp('date','Movie',[pair('Movie_name',index(33,5),[nmod_of],required),pair('Release_year',index(33,2),[self],required)])).
learned_sentence('The films released sometime.',index(34,3),'Movie',[pair('Movie_name',index(34,2),required),pair('Release_year',index(34,4),required)],[],lvp('release','Movie',[pair('Movie_name',index(34,2),[nsubj],required),pair('Release_year',index(34,4),[advmod],required)])).
learned_sentence('Directors directed the films for the writers.',index(35,2),'Movie',[pair('Movie_name',index(35,4),required),pair('Writer',index(35,7),required)],[],lvp('direct','Movie',[pair('Movie_name',index(35,4),[obj],required),pair('Writer',index(35,7),[obl_for],required)])).
learned_sentence('Actors starred the films for the directors.',index(36,2),'Movie',[pair('Movie_name',index(36,4),required),pair('Director',index(36,7),required)],[],lvp('star','Movie',[pair('Movie_name',index(36,4),[obj],required),pair('Director',index(36,7),[obl_for],required)])).
learned_sentence('Writers wrote the films.',index(37,2),'Movie',[pair('Movie_name',index(37,4),required),pair('Writer',index(37,1),required)],['co_write'],lvp('write','Movie',[pair('Movie_name',index(37,4),[obj],required),pair('Writer',index(37,1),[nsubj],required)])).
learned_sentence('Writer\'s films.',index(38,1),'Movie',[pair('Movie_name',index(38,3),required),pair('Writer',index(38,1),required)],['screenwreiter','scriptwriter'],lvp('writer','Movie',[pair('Movie_name',index(38,3),[ssop_domn],required),pair('Writer',index(38,1),[self],required)])).
learned_sentence('Actors starred the films.',index(39,2),'Movie',[pair('Movie_name',index(39,4),required),pair('Actor',index(39,1),required)],['act'],lvp('star','Movie',[pair('Movie_name',index(39,4),[obj],required),pair('Actor',index(39,1),[nsubj],required)])).
learned_sentence('Actors of the films.',index(40,1),'Movie',[pair('Movie_name',index(40,4),required),pair('Actor',index(40,1),required)],[],lvp('actor','Movie',[pair('Movie_name',index(40,4),[nmod_of],required),pair('Actor',index(40,1),[self],required)])).
learned_sentence('Directors of the films.',index(41,1),'Movie',[pair('Movie_name',index(41,4),required),pair('Director',index(41,1),required)],[],lvp('director','Movie',[pair('Movie_name',index(41,4),[nmod_of],required),pair('Director',index(41,1),[self],required)])).
learned_sentence('Writers of the films.',index(42,1),'Movie',[pair('Movie_name',index(42,4),required),pair('Writer',index(42,1),required)],['screenwreiter','scriptwriter'],lvp('writer','Movie',[pair('Movie_name',index(42,4),[nmod_of],required),pair('Writer',index(42,1),[self],required)])).
learned_sentence('Actors in the films also appear in the films.',index(43,5),'Inequality',[pair('Entity_1',index(43,4),required),pair('Entity_2',index(43,9),required)],['act','star'],lvp('also','Inequality',[pair('Entity_1',index(43,4),[domvda,obl_in],required),pair('Entity_2',index(43,9),[domvda,obl_in],required)])).
learned_sentence('Directors of the films also directed the films.',index(44,5),'Inequality',[pair('Entity_1',index(44,4),required),pair('Entity_2',index(44,8),required)],['write'],lvp('also','Inequality',[pair('Entity_1',index(44,4),[domvda,nsubj,nmod_of],required),pair('Entity_2',index(44,8),[domvda,obj],required)])).
learned_sentence('Film will release whose directors directed the films.',index(45,5),'Movie',[pair('Movie_name',index(45,1),required),pair('Director',index(45,5),required)],[],lvp('director','Movie',[pair('Movie_name',index(45,1),[jbusn,pmocc,nsubj],required),pair('Director',index(45,5),[self],required)])).
learned_sentence('Film will release whose also directors directed the films.',index(46,5),'Inequality',[pair('Entity_1',index(46,1),required),pair('Entity_2',index(46,9),required)],['write'],lvp('also','Inequality',[pair('Entity_1',index(46,1),[domvda,pmocc,nsubj],required),pair('Entity_2',index(46,9),[domvda,obj],required)])).
learned_sentence('Film will release whose writers wrote the films.',index(47,5),'Movie',[pair('Movie_name',index(47,1),required),pair('Writer',index(47,5),required)],[],lvp('writer','Movie',[pair('Movie_name',index(47,1),[jbusn,pmocc,nsubj],required),pair('Writer',index(47,5),[self],required)])).
learned_sentence('Film will release whose actors appear in the films.',index(48,5),'Movie',[pair('Movie_name',index(48,1),required),pair('Actor',index(48,5),required)],[],lvp('actor','Movie',[pair('Movie_name',index(48,1),[jbusn,pmocc,nsubj],required),pair('Actor',index(48,5),[self],required)])).
learned_sentence('Film will release whose actors also appear in the films.',index(49,6),'Inequality',[pair('Entity_1',index(49,1),required),pair('Entity_2',index(49,10),required)],[],lvp('also','Inequality',[pair('Entity_1',index(49,1),[domvda,pmocc,nsubj],required),pair('Entity_2',index(49,10),[domvda,obl_in],required)])).
learned_sentence('Films are directed by the director of the films.',index(50,3),'Movie',[pair('Movie_name',index(50,1),required),pair('Director',index(50,6),required)],[],lvp('direct','Movie',[pair('Movie_name',index(50,1),[obj],required),pair('Director',index(50,6),[obl_by],required)])).
learned_sentence('Films are directed by the director of the films.',index(50,3),'Movie',[pair('Movie_name',index(50,1),required),pair('Director',index(50,6),required)],[],lvp('direct','Movie',[pair('Movie_name',index(50,1),[obj],required),pair('Director',index(50,6),[nsubj],required)])).
learned_sentence('Films are directed by the director of the films.',index(50,3),'Movie',[pair('Movie_name',index(50,1),required),pair('Director',index(50,6),required)],[],lvp('directed','Movie',[pair('Movie_name',index(50,1),[nsubj],required),pair('Director',index(50,6),[obl_by],required)])).
learned_sentence('Films are directed by the same director of the films.',index(51,6),'Inequality',[pair('Entity_1',index(51,1),required),pair('Entity_2',index(51,10),required)],['write'],lvp('same','Inequality',[pair('Entity_1',index(51,1),[doma,lbo_by,obj],required),pair('Entity_2',index(51,10),[doma,nmod_of],required)])).
learned_sentence('Films are directed by the same director of the films.',index(51,6),'Inequality',[pair('Entity_1',index(51,1),required),pair('Entity_2',index(51,10),required)],['write'],lvp('same','Inequality',[pair('Entity_1',index(51,1),[doma,jbusn,obj],required),pair('Entity_2',index(51,10),[doma,nmod_of],required)])).
learned_sentence('Films are directed by the same director of the films.',index(51,6),'Inequality',[pair('Entity_1',index(51,1),required),pair('Entity_2',index(51,10),required)],['written'],lvp('same','Inequality',[pair('Entity_1',index(51,1),[doma,lbo_by,nsubj],required),pair('Entity_2',index(51,10),[doma,nmod_of],required)])).
learned_sentence('Films have actors of the films.',index(52,3),'Movie',[pair('Movie_name',index(52,1),required),pair('Actor',index(52,3),required)],[],lvp('actor','Movie',[pair('Movie_name',index(52,1),[jbo,nsubj],required),pair('Actor',index(52,3),[self],required)])).
learned_sentence('Films have the same actors of the films.',index(53,4),'Inequality',[pair('Entity_1',index(53,1),required),pair('Entity_2',index(53,7),required)],['share'],lvp('same','Inequality',[pair('Entity_1',index(53,1),[doma,jbo,nsubj],required),pair('Entity_2',index(53,7),[doma,nmod_of,det],required)])).
learned_sentence('Films have writers of the films.',index(54,3),'Movie',[pair('Movie_name',index(54,1),required),pair('Writer',index(54,3),required)],['screenwriter','scriptwriter'],lvp('writer','Movie',[pair('Movie_name',index(54,1),[jbo,nsubj],required),pair('Writer',index(54,3),[self],required)])).
learned_sentence('The [MASK]-starred movies.',index(55,6),'Movie',[pair('Movie_name',index(55,7),required),pair('Actor',index(55,3),required)],['act'],lvp('star','Movie',[pair('Movie_name',index(55,7),[doma],required),pair('Actor',index(55,3),[doma,compound],required)])).
learned_sentence('The [MASK]-directed films.',index(56,6),'Movie',[pair('Movie_name',index(56,7),required),pair('Director',index(56,3),required)],[],lvp('direct','Movie',[pair('Movie_name',index(56,7),[doma],required),pair('Director',index(56,3),[doma,compound],required)])).
learned_sentence('The [MASK]-written films.',index(57,6),'Movie',[pair('Movie_name',index(57,7),required),pair('Writer',index(57,3),required)],[],lvp('write','Movie',[pair('Movie_name',index(57,7),[doma],required),pair('Writer',index(57,3),[doma,compound],required)])).
learned_sentence('Films have actors of the films.',index(58,3),'Movie',[pair('Movie_name',index(58,1),required),pair('Actor',index(58,3),required)],[],lvp('actor','Movie',[pair('Movie_name',index(58,1),[jbo,nsubj],required),pair('Actor',index(58,3),[self],required)])).
learned_sentence('Films have the same actors of the films.',index(59,4),'Inequality',[pair('Entity_1',index(59,1),required),pair('Entity_2',index(59,8),required)],['share'],lvp('same','Inequality',[pair('Entity_1',index(59,1),[doma,jbo,nsubj],required),pair('Entity_2',index(59,8),[doma,nmod_of],required)])).
learned_sentence('Films have director of the films.',index(60,3),'Movie',[pair('Movie_name',index(60,1),required),pair('Director',index(60,3),required)],[],lvp('director','Movie',[pair('Movie_name',index(60,1),[jbo,nsubj],required),pair('Director',index(60,3),[self],required)])).
learned_sentence('Films have writers of the films.',index(61,3),'Movie',[pair('Movie_name',index(61,1),required),pair('Writer',index(61,3),required)],['screenwriter','scriptwriter'],lvp('writer','Movie',[pair('Movie_name',index(61,1),[jbo,nsubj],required),pair('Writer',index(61,3),[self],required)])).
learned_sentence('The co-writers of the writer.',index(62,2),'Coop',[pair('Writer',index(62,5),required),pair('Writer',index(62,2),required)],[],lvp('co_writer','Coop',[pair('Writer',index(62,5),[nmod_of],required),pair('Writer',index(62,2),[self],required)])).
learned_sentence('The co-directors of the director.',index(63,2),'Coop',[pair('Director',index(63,5),required),pair('Director',index(63,2),required)],[],lvp('co_director','Coop',[pair('Director',index(63,5),[nmod_of],required),pair('Director',index(63,2),[self],required)])).
learned_sentence('Actors of directors [MASK].',index(64,3),'Coop',[pair('Director',index(64,3),required),pair('Actor',index(64,1),required)],[],lvp('director','Coop',[pair('Director',index(64,3),[self],required),pair('Actor',index(64,1),[dnuopmoc,domn_of],required)])).
learned_sentence('Actors of writers [MASK].',index(65,3),'Coop',[pair('Writer',index(65,3),required),pair('Actor',index(65,1),required)],['screenwriter','scriptwriter'],lvp('writer','Coop',[pair('Writer',index(65,3),[self],required),pair('Actor',index(65,1),[dnuopmoc,domn_of],required)])).
learned_sentence('Writers wrote the screenplays for the movies.',index(66,2),'Movie',[pair('Movie_name',index(66,7),required),pair('Writer',index(66,1),required)],[],lvp('write','Movie',[pair('Movie_name',index(66,7),[obl_for],required),pair('Writer',index(66,1),[nsubj],required)])).
learned_sentence('Actors in the films.',index(67,1),'Movie',[pair('Movie_name',index(67,4),required),pair('Actor',index(67,1),required)],[],lvp('actor','Movie',[pair('Movie_name',index(67,4),[obl_in],required),pair('Actor',index(67,1),[self],required)])).
learned_sentence('Actors appear in the films with actors.',index(68,2),'Movie',[pair('Movie_name',index(68,5),required),pair('Actor',index(68,7),required)],[],lvp('appear','Movie',[pair('Movie_name',index(68,5),[obl_in],required),pair('Actor',index(68,7),[obl_with],required)])).
learned_sentence('Actors appear in the same films with actors.',index(69,5),'Inequality',[pair('Entity_1',index(69,1),required),pair('Entity_2',index(69,8),required)],[],lvp('same','Inequality',[pair('Entity_1',index(69,1),[doma,lbo_in,nsubj],required),pair('Entity_2',index(69,8),[doma,lbo_in,obl_with],required)])).
learned_sentence('Actors co-starred with actors.',index(70,2),'Coop',[pair('Actor',index(70,4),required),pair('Actor',index(70,1),required)],['act','star'],lvp('co_star','Coop',[pair('Actor',index(70,4),[obl_with],required),pair('Actor',index(70,1),[nsubj],required)])).
learned_sentence('Actor is a co-star of actor.',index(71,4),'Coop',[pair('Actor',index(71,6),required),pair('Actor',index(71,1),required)],[],lvp('co_star','Coop',[pair('Actor',index(71,6),[nmod_of],required),pair('Actor',index(71,1),[nsubj],required)])).
learned_sentence('Director of films is also the director of films.',index(72,5),'Inequality',[pair('Entity_1',index(72,3),required),pair('Entity_2',index(72,9),required)],[],lvp('also','Inequality',[pair('Entity_1',index(72,3),[domvda,nsubj,nmod_of],required),pair('Entity_2',index(72,9),[domvda,nmod_of],required)])).
learned_sentence('Directors co-directed films with directors.',index(73,2),'Movie',[pair('Movie_name',index(73,3),required),pair('Director',index(73,5),required)],['direct'],lvp('co_direct','Movie',[pair('Movie_name',index(73,3),[obj],required),pair('Director',index(73,5),[obl_with],required)])).
learned_sentence('Directors co-directed films with directors.',index(74,2),'Inequality',[pair('Entity_1',index(74,1),required),pair('Entity_2',index(74,5),required)],['direct','co_write','write'],lvp('co_direct','Inequality',[pair('Entity_1',index(74,1),[nsubj],required),pair('Entity_2',index(74,5),[obl_with],required)])).
learned_sentence('Writers co-write films with writers.',index(75,2),'Movie',[pair('Movie_name',index(75,3),required),pair('Writer',index(75,5),required)],['write'],lvp('co_write','Movie',[pair('Movie_name',index(75,3),[obj],required),pair('Writer',index(75,5),[obl_with],required)])).
learned_sentence('Actors of films also appear in the films.',index(76,4),'Inequality',[pair('Entity_1',index(76,3),required),pair('Entity_2',index(76,8),required)],['act','star'],lvp('also','Inequality',[pair('Entity_1',index(76,3),[domvda,nsubj,nmod_of],required),pair('Entity_2',index(76,8),[domvda,obl_in],required)])).
learned_sentence('When are the movies?',index(77,1),'Movie',[pair('Movie_name',index(77,4),required),pair('Release_year',index(77,1),required)],[],lvp('when','Movie',[pair('Movie_name',index(77,4),[nsubj],required),pair('Release_year',index(77,1),[self],required)])).
learned_sentence('Actors starred the movies for the writers.',index(78,2),'Movie',[pair('Movie_name',index(78,4),required),pair('Writer',index(78,7),required)],[],lvp('star','Movie',[pair('Movie_name',index(78,4),[obj],required),pair('Writer',index(78,7),[obl_for],required)])).
learned_sentence('Films share writers with the films.',index(79,2),'Inequality',[pair('Entity_1',index(79,1),required),pair('Entity_2',index(79,6),required)],[],lvp('share','Inequality',[pair('Entity_1',index(79,1),[nsubj],required),pair('Entity_2',index(79,6),[obl_with],required)])).
learned_sentence('Someone is listed as the director of the film.',index(80,6),'Movie',[pair('Movie_name',index(80,9),required),pair('Director',index(80,1),required)],[],lvp('director','Movie',[pair('Movie_name',index(80,9),[nmod_of],required),pair('Director',index(80,1),[lbo_as,obj],required)])).
learned_sentence('Someone is listed as the director of the film.',index(80,6),'Movie',[pair('Movie_name',index(80,9),required),pair('Director',index(80,1),required)],[],lvp('director','Movie',[pair('Movie_name',index(80,9),[nmod_of],required),pair('Director',index(80,1),[lbo_as,nsubj],required)])).
learned_sentence('Someone is listed as the writer of the film.',index(81,6),'Movie',[pair('Movie_name',index(81,9),required),pair('Writer',index(81,1),required)],['screenwriter','scriptwriter'],lvp('writer','Movie',[pair('Movie_name',index(81,9),[nmod_of],required),pair('Writer',index(81,1),[lbo_as,obj],required)])).
learned_sentence('Someone is listed as the writer of the film.',index(81,6),'Movie',[pair('Movie_name',index(81,9),required),pair('Writer',index(81,1),required)],['screenwriter','scriptwriter'],lvp('writer','Movie',[pair('Movie_name',index(81,9),[nmod_of],required),pair('Writer',index(81,1),[lbo_as,nsubj],required)])).
learned_sentence('What genres are films?',index(82,2),'Movie',[pair('Movie_name',index(82,4),required),pair('Genre',index(82,2),required)],[],lvp('genre','Movie',[pair('Movie_name',index(82,4),[jbusn],required),pair('Genre',index(82,2),[self],required)])).
