?-answer(2,[bedroom]).
?-answer(4,[kitchen]).
?-answer(6,[bedroom]).
?-answer(8,[tired]).
?-answer(10,[tired]).
?-answer(12,[thirsty]).
?-answer(14,[tired]).
?-answer(16,[garden]).
?-answer(18,[bored]).
?-answer(20,[bored]).
?-answer(22,[thirsty]).
