?-answer(2,[bedroom]).
?-answer(4,[kitchen]).
?-answer(6,[kitchen]).
?-answer(8,[hungry]).
?-answer(10,[hungry]).
?-answer(12,[tired]).
?-answer(14,[tired]).
?-answer(16,[thirsty]).
?-answer(18,[thirsty]).
?-answer(20,[kitchen]).
?-answer(22,[hungry]).
