?-answer(2,[bedroom]).
?-answer(4,[kitchen]).
?-answer(6,[tired]).
?-answer(8,[thirsty]).
?-answer(10,[tired]).
?-answer(12,[bedroom]).
?-answer(14,[tired]).
?-answer(16,[garden]).
?-answer(18,[bored]).
?-answer(20,[thirsty]).
?-answer(22,[bored]).
