?-answer(2,[garden]).
?-answer(4,[kitchen]).
?-answer(6,[kitchen]).
?-answer(8,[kitchen]).
?-answer(10,[bored]).
?-answer(12,[bored]).
?-answer(14,[hungry]).
?-answer(16,[thirsty]).
?-answer(18,[hungry]).
?-answer(20,[hungry]).
?-answer(22,[thirsty]).
