?-answer(2,[bedroom]).
?-answer(4,[kitchen]).
?-answer(6,[hungry]).
?-answer(8,[garden]).
?-answer(10,[bored]).
?-answer(12,[hungry]).
?-answer(14,[tired]).
?-answer(16,[garden]).
?-answer(18,[bored]).
?-answer(20,[bored]).
?-answer(22,[tired]).
