?-answer(2,[kitchen]).
?-answer(4,[kitchen]).
?-answer(6,[kitchen]).
?-answer(8,[hungry]).
?-answer(10,[kitchen]).
?-answer(12,[hungry]).
?-answer(14,[thirsty]).
?-answer(16,[thirsty]).
?-answer(18,[thirsty]).
?-answer(20,[thirsty]).
