?-answer(2,[kitchen]).
?-answer(4,[bedroom]).
?-answer(6,[tired]).
?-answer(8,[tired]).
?-answer(10,[bedroom]).
?-answer(12,[hungry]).
?-answer(14,[hungry]).
?-answer(16,[tired]).
?-answer(18,[garden]).
?-answer(20,[bored]).
?-answer(22,[bored]).
