?-answer(2,[kitchen]).
?-answer(4,[bedroom]).
?-answer(6,[tired]).
?-answer(8,[kitchen]).
?-answer(10,[tired]).
?-answer(12,[hungry]).
?-answer(14,[hungry]).
?-answer(16,[garden]).
?-answer(18,[bored]).
?-answer(20,[hungry]).
?-answer(22,[bored]).
