?-answer(2,[garden]).
?-answer(4,[kitchen]).
?-answer(6,[thirsty]).
?-answer(8,[kitchen]).
?-answer(10,[thirsty]).
?-answer(12,[garden]).
?-answer(14,[hungry]).
?-answer(16,[hungry]).
?-answer(18,[bored]).
?-answer(20,[bored]).
?-answer(22,[bored]).
