?-answer(2,[bedroom]).
?-answer(4,[kitchen]).
?-answer(6,[kitchen]).
?-answer(8,[tired]).
?-answer(10,[hungry]).
?-answer(12,[hungry]).
?-answer(14,[tired]).
?-answer(16,[garden]).
?-answer(18,[bored]).
?-answer(20,[hungry]).
?-answer(22,[bored]).
