?-answer(2,[kitchen]).
?-answer(4,[bedroom]).
?-answer(6,[bedroom]).
?-answer(8,[tired]).
?-answer(10,[thirsty]).
?-answer(12,[tired]).
?-answer(14,[tired]).
?-answer(16,[bedroom]).
?-answer(18,[tired]).
?-answer(20,[thirsty]).
