?-answer(2,[kitchen]).
?-answer(4,[thirsty]).
?-answer(6,[kitchen]).
?-answer(8,[thirsty]).
?-answer(10,[thirsty]).
?-answer(12,[kitchen]).
?-answer(14,[kitchen]).
?-answer(16,[hungry]).
?-answer(18,[hungry]).
?-answer(20,[hungry]).
