?-answer(2,[kitchen]).
?-answer(4,[hungry]).
?-answer(6,[kitchen]).
?-answer(8,[garden]).
?-answer(10,[bored]).
?-answer(12,[hungry]).
?-answer(14,[garden]).
?-answer(16,[bored]).
?-answer(18,[bored]).
?-answer(20,[thirsty]).
?-answer(22,[thirsty]).
