?-answer(2,[kitchen]).
?-answer(4,[kitchen]).
?-answer(6,[kitchen]).
?-answer(8,[thirsty]).
?-answer(10,[hungry]).
?-answer(12,[thirsty]).
?-answer(14,[thirsty]).
?-answer(16,[bedroom]).
?-answer(18,[tired]).
?-answer(20,[tired]).
?-answer(22,[hungry]).
