?-answer(2,[garden]).
?-answer(4,[kitchen]).
?-answer(6,[thirsty]).
?-answer(8,[thirsty]).
?-answer(10,[kitchen]).
?-answer(12,[bored]).
?-answer(14,[bored]).
?-answer(16,[bedroom]).
?-answer(18,[tired]).
?-answer(20,[tired]).
?-answer(22,[thirsty]).
