?-answer(2,[kitchen]).
?-answer(4,[kitchen]).
?-answer(6,[hungry]).
?-answer(8,[hungry]).
?-answer(10,[kitchen]).
?-answer(12,[hungry]).
?-answer(14,[bedroom]).
?-answer(16,[hungry]).
?-answer(18,[tired]).
?-answer(20,[tired]).
