?-answer(2,[garden]).
?-answer(4,[bored]).
?-answer(6,[bedroom]).
?-answer(8,[bored]).
?-answer(10,[bedroom]).
?-answer(12,[tired]).
?-answer(14,[tired]).
?-answer(16,[tired]).
?-answer(18,[garden]).
?-answer(20,[bored]).
