?-answer(2,[garden]).
?-answer(4,[kitchen]).
?-answer(6,[garden]).
?-answer(8,[garden]).
?-answer(10,[bored]).
?-answer(12,[bored]).
?-answer(14,[bored]).
?-answer(16,[hungry]).
?-answer(18,[hungry]).
?-answer(20,[bored]).
