?-answer(2,[bedroom]).
?-answer(4,[tired]).
?-answer(6,[kitchen]).
?-answer(8,[garden]).
?-answer(10,[hungry]).
?-answer(12,[hungry]).
?-answer(14,[tired]).
?-answer(16,[kitchen]).
?-answer(18,[hungry]).
?-answer(20,[bored]).
?-answer(22,[bored]).
