?-answer(2,[bedroom]).
?-answer(4,[garden]).
?-answer(6,[tired]).
?-answer(8,[garden]).
?-answer(10,[bedroom]).
?-answer(12,[bored]).
?-answer(14,[bored]).
?-answer(16,[tired]).
?-answer(18,[tired]).
?-answer(20,[bored]).
