?-answer(2,[garden]).
?-answer(4,[bored]).
?-answer(6,[kitchen]).
?-answer(8,[garden]).
?-answer(10,[bored]).
?-answer(12,[bored]).
?-answer(14,[bedroom]).
?-answer(16,[thirsty]).
?-answer(18,[thirsty]).
?-answer(20,[tired]).
?-answer(22,[tired]).
