?-answer(2,[kitchen]).
?-answer(4,[kitchen]).
?-answer(6,[garden]).
?-answer(8,[bored]).
?-answer(10,[thirsty]).
?-answer(12,[bored]).
?-answer(14,[thirsty]).
?-answer(16,[thirsty]).
?-answer(18,[kitchen]).
?-answer(20,[hungry]).
?-answer(22,[hungry]).
