?-answer(2,[kitchen]).
?-answer(4,[bedroom]).
?-answer(6,[tired]).
?-answer(8,[bedroom]).
?-answer(10,[tired]).
?-answer(12,[tired]).
?-answer(14,[kitchen]).
?-answer(16,[hungry]).
?-answer(18,[hungry]).
?-answer(20,[hungry]).
