?-answer(2,[kitchen]).
?-answer(4,[kitchen]).
?-answer(6,[kitchen]).
?-answer(8,[hungry]).
?-answer(10,[thirsty]).
?-answer(12,[bedroom]).
?-answer(14,[hungry]).
?-answer(16,[hungry]).
?-answer(18,[tired]).
?-answer(20,[thirsty]).
?-answer(22,[tired]).
