?-answer(2,[kitchen]).
?-answer(4,[bedroom]).
?-answer(6,[bedroom]).
?-answer(8,[tired]).
?-answer(10,[hungry]).
?-answer(12,[hungry]).
?-answer(14,[kitchen]).
?-answer(16,[tired]).
?-answer(18,[tired]).
?-answer(20,[thirsty]).
?-answer(22,[thirsty]).
