?-answer(2,[bedroom]).
?-answer(4,[tired]).
?-answer(6,[kitchen]).
?-answer(8,[kitchen]).
?-answer(10,[garden]).
?-answer(12,[bored]).
?-answer(14,[hungry]).
?-answer(16,[hungry]).
?-answer(18,[hungry]).
?-answer(20,[tired]).
?-answer(22,[bored]).
