?-answer(2,[kitchen]).
?-answer(4,[kitchen]).
?-answer(6,[kitchen]).
?-answer(8,[thirsty]).
?-answer(10,[thirsty]).
?-answer(12,[bedroom]).
?-answer(14,[thirsty]).
?-answer(16,[tired]).
?-answer(18,[hungry]).
?-answer(20,[tired]).
?-answer(22,[hungry]).
