:- dynamic(learned_sentence/6).

learned_sentence('A person goes to a place.',index(1,3),'Travel',[pair('Person',index(1,2),required),pair('Place',index(1,6),required)],['travel','journey','move'],lvp('go','Travel',[pair('Person',index(1,2),[nsubj],required),pair('Place',index(1,6),[obl_to],required)])).
learned_sentence('What is it carrying?',index(2,4),'Hold',[pair('Person',index(2,3),required),pair('Theme',index(2,1),required)],[],lvp('carry','Hold',[pair('Person',index(2,3),[nsubj],required),pair('Theme',index(2,1),[obj],required)])).
learned_sentence('A person got something.',index(3,3),'Obtain',[pair('Person',index(3,2),required),pair('Theme',index(3,4),required)],['grab','take','pick_up'],lvp('get','Obtain',[pair('Person',index(3,2),[nsubj],required),pair('Theme',index(3,4),[obj],required)])).
learned_sentence('A person dropped something.',index(4,3),'Discard',[pair('Person',index(4,2),required),pair('Theme',index(4,4),required)],['discard','leave','put_down'],lvp('drop','Discard',[pair('Person',index(4,2),[nsubj],required),pair('Theme',index(4,4),[obj],required)])).
learned_sentence('A person holds something.',index(5,3),'Hold',[pair('Person',index(5,2),required),pair('Theme',index(5,4),required)],[],lvp('hold','Hold',[pair('Person',index(5,2),[nsubj],required),pair('Theme',index(5,4),[obj],required)])).
learned_sentence('List2 equals list1 plus an element.',index(6,4),'Append',[pair('List1',index(6,3),required),pair('List2',index(6,6),required),pair('NewList',index(6,1),required)],[],lvp('plus','Append',[pair('List1',index(6,3),[cc,jnoc],required),pair('List2',index(6,6),[cc],required),pair('NewList',index(6,1),[cc,jnoc,jbo,nsubj],required)])).
learned_sentence('List2 equals list1 minus an element.',index(7,4),'Remove',[pair('List',index(7,3),required),pair('Element',index(7,6),required),pair('NewList',index(7,1),required)],[],lvp('minus','Remove',[pair('List',index(7,3),[esac,lbo_minus,obj],required),pair('Element',index(7,6),[esac],required),pair('NewList',index(7,1),[esac,lbo_minus,nsubj],required)])).
