:- dynamic(learned_sentence/6).

learned_sentence('A place is north of a place.',index(1,4),'North_of',[pair('Entity1',index(1,2),required),pair('Entity2',index(1,7),required)],[],lvp('north','North_of',[pair('Entity1',index(1,2),[nsubj],required),pair('Entity2',index(1,7),[obl_of],required)])).
learned_sentence('A place is south of a place.',index(2,4),'South_of',[pair('Entity1',index(2,2),required),pair('Entity2',index(2,7),required)],[],lvp('south','South_of',[pair('Entity1',index(2,2),[nsubj],required),pair('Entity2',index(2,7),[obl_of],required)])).
learned_sentence('A place is east of a place.',index(3,4),'East_of',[pair('Entity1',index(3,2),required),pair('Entity2',index(3,7),required)],[],lvp('east','East_of',[pair('Entity1',index(3,2),[nsubj],required),pair('Entity2',index(3,7),[obl_of],required)])).
learned_sentence('A place is west of a place.',index(4,4),'West_of',[pair('Entity1',index(4,2),required),pair('Entity2',index(4,7),required)],[],lvp('west','West_of',[pair('Entity1',index(4,2),[nsubj],required),pair('Entity2',index(4,7),[obl_of],required)])).
learned_sentence('How do you go from the bathroom to the hallway?',index(5,4),'Route',[pair('Source',index(5,7),required),pair('Target',index(5,10),required),pair('Path',index(5,1),required)],[],lvp('go','Route',[pair('Source',index(5,7),[obl_from],required),pair('Target',index(5,10),[obl_to],required),pair('Path',index(5,1),[advmod],required)])).
learned_sentence('A person travels from the source to the target via a path.',index(6,10),'Route',[pair('Source',index(6,6),required),pair('Target',index(6,9),required),pair('Path',index(6,12),required)],[],lvp('via','Route',[pair('Source',index(6,6),[esac,lbo_via,obl_from],required),pair('Target',index(6,9),[esac,lbo_via,obl_to],required),pair('Path',index(6,12),[esac],required)])).
learned_sentence('List2 equals list1 plus an element.',index(7,4),'Append',[pair('List1',index(7,3),required),pair('List2',index(7,6),required),pair('NewList',index(7,1),required)],[],lvp('plus','Append',[pair('List1',index(7,3),[cc,jbo,obj],required),pair('List2',index(7,6),[cc],required),pair('NewList',index(7,1),[cc,jbo,nsubj],required)])).
