:- dynamic(learned_sentence/6).

learned_sentence('A person goes to a place this morning.',index(1,3),'Travel',[pair('Person',index(1,2),required),pair('Place',index(1,6),required),pair('Period',index(1,8),required)],['travel','journey','move'],lvp('go','Travel',[pair('Person',index(1,2),[nsubj],required),pair('Place',index(1,6),[obl_to],required),pair('Period',index(1,8),[obl_tmod],required)])).
learned_sentence('Where is the person before a place?',index(2,1),'Located',[pair('Entity',index(2,4),required),pair('Place',index(2,1),required),pair('Before_place',index(2,7),required)],[],lvp('where','Located',[pair('Entity',index(2,4),[nsubj],required),pair('Place',index(2,1),[self],required),pair('Before_place',index(2,7),[obl_before],required)])).
learned_sentence('A time is before another time.',index(3,4),'Before_period',[pair('Period1',index(3,2),required),pair('Period2',index(3,6),required)],[],lvp('before','Before_period',[pair('Period1',index(3,2),[esac,nsubj],required),pair('Period2',index(3,6),[esac],required)])).
learned_sentence('A person goes to a place in a period.',index(4,3),'Travel',[pair('Person',index(4,2),required),pair('Place',index(4,6),required),pair('Period',index(4,9),required)],['travel','journey','move'],lvp('go','Travel',[pair('Person',index(4,2),[nsubj],required),pair('Place',index(4,6),[obl_to],required),pair('Period',index(4,9),[obl_in],required)])).
learned_sentence('A person is located at a place in a period.',index(5,4),'Located',[pair('Entity',index(5,2),required),pair('Place',index(5,7),required),pair('Period',index(5,10),required)],[],lvp('locate','Located',[pair('Entity',index(5,2),[obj],required),pair('Place',index(5,7),[obl_at],required),pair('Period',index(5,10),[obl_in],required)])).
learned_sentence('A person is located at a place in a period.',index(5,4),'Located',[pair('Entity',index(5,2),required),pair('Place',index(5,7),required),pair('Period',index(5,10),required)],[],lvp('located','Located',[pair('Entity',index(5,2),[nsubj],required),pair('Place',index(5,7),[obl_at],required),pair('Period',index(5,10),[obl_in],required)])).
learned_sentence('A person appears in a period before another period.',index(6,3),'Shown',[pair('Entity',index(6,2),required),pair('Period',index(6,6),required),pair('Before_period',index(6,9),required)],[],lvp('appear','Shown',[pair('Entity',index(6,2),[nsubj],required),pair('Period',index(6,6),[obl_in],required),pair('Before_period',index(6,9),[obl_before],required)])).
learned_sentence('A person is located at a place before a place.',index(7,4),'Located',[pair('Entity',index(7,2),required),pair('Place',index(7,7),required),pair('Before_place',index(7,10),required)],[],lvp('locate','Located',[pair('Entity',index(7,2),[obj],required),pair('Place',index(7,7),[obl_at],required),pair('Before_place',index(7,10),[obl_before],required)])).
learned_sentence('A person is located at a place before a place.',index(7,4),'Located',[pair('Entity',index(7,2),required),pair('Place',index(7,7),required),pair('Before_place',index(7,10),required)],[],lvp('located','Located',[pair('Entity',index(7,2),[nsubj],required),pair('Place',index(7,7),[obl_at],required),pair('Before_place',index(7,10),[obl_before],required)])).
