:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),1).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),6).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),7).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),8).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),10).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),12).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),14).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),15).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),16).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),17).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),18).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),19).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),20).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),21).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),24).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),25).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),26).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),28).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),30).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),32).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),33).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),34).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),35).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),38).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),39).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),40).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),41).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),42).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),45).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),46).
q(47,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),47).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),48).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),49).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),50).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),51).
q(52,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),52).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),53).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),54).
q(55,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',kitchen)]),55).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),56).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),57).
q(58,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',kitchen)]),58).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),59).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),60).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),61).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),62).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),63).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),64).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),65).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),67).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),68).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),69).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),72).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),74).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),75).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),76).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),77).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),79).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),80).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),81).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),82).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),83).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),84).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),85).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),86).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),87).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),88).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),89).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),90).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),92).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),93).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),94).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),95).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),96).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),97).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),98).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),99).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),100).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),101).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),102).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),103).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),104).
q(105,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),105).
