:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),1).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),2).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),3).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),6).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),7).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),9).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),10).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),11).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),14).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),15).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),16).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),17).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),18).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),19).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),20).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),21).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),22).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),23).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),24).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),26).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),27).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),28).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),31).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),32).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),33).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),34).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),35).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),37).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),41).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),42).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),43).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),44).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),45).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),47).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),48).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),49).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),50).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),52).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),53).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),55).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),56).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),57).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),58).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),60).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),61).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),62).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),64).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),67).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),69).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),71).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),74).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),75).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),80).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),81).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),82).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),83).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),84).
q(85,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),85).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),86).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),87).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),88).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),89).
q(90,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',hallway)]),90).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),91).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),92).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),93).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),94).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),95).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),96).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),97).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),98).
q(99,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',kitchen)]),99).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),100).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),101).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),102).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),103).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),104).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),105).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),106).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),107).
q(108,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),108).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),109).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),110).
q(111,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',kitchen)]),111).
