:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),1).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),2).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),3).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),4).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),6).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),7).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),8).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),10).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),11).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),12).
q(13,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),15).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),16).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),17).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),18).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),19).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),21).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),23).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),24).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),25).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),26).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),27).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),28).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),29).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),30).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),31).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),32).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),33).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),34).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),35).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),36).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),37).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),39).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),40).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),41).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),42).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),43).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),44).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),45).
q(46,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),46).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),47).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),48).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),49).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),50).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),52).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),53).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),54).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),55).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),56).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),57).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),58).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),59).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),60).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),61).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),62).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),63).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),64).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),65).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),66).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),67).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),68).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),69).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),70).
q(71,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),72).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),73).
q(74,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),76).
q(77,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),77).
