:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),1).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),3).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),4).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),6).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),7).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),10).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),13).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),14).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),15).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),16).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),17).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),18).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),19).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),21).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),22).
q(23,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),24).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),25).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),26).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),27).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),28).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),29).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),30).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),31).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),33).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),34).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),35).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),36).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),38).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),40).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),41).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),42).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),44).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),45).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),46).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),47).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),48).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),49).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),50).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),51).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),52).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),53).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),54).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),57).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),58).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),59).
q(60,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),60).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),61).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),62).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),63).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),64).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),66).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),67).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),68).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),70).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),72).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),73).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),74).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),75).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),77).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),78).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),79).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),80).
q(81,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),81).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),82).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),83).
q(84,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),84).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),85).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),86).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),87).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),88).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),89).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),90).
q(91,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),91).
