:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),3).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),5).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),6).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),10).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),14).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),15).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),16).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),17).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),18).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),21).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),23).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),24).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),25).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),28).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),29).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),31).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),32).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),33).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),34).
q(35,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),35).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),36).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),37).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),38).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),40).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),41).
q(42,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),42).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),43).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),45).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),47).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),48).
q(49,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',hallway)]),49).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),50).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),51).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),52).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),53).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),55).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),56).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),57).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),58).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),59).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),60).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),61).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),62).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),65).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),66).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),68).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),69).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),71).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),75).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),76).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),78).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),79).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),80).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),81).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),82).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),83).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),84).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),85).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),86).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),87).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),88).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),89).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),90).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),91).
q(92,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),92).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),93).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),94).
q(95,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),95).
