:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),2).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),3).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),4).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),6).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),10).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),12).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),13).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),14).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),15).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),16).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),17).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),18).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),19).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),20).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),22).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),24).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),26).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),27).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),28).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),30).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),31).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),32).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),35).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),36).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),39).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),40).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),41).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),42).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),43).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),46).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),47).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),48).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),49).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),50).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),51).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),52).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),53).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),54).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),55).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),56).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),58).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),59).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),60).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),61).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),62).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),63).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),64).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),67).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),68).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),69).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),70).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),71).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),72).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),73).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),74).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),76).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),78).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),79).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),80).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),81).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),82).
q(83,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),83).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),84).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),85).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),86).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),87).
q(88,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),88).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),90).
q(91,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),91).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),92).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),93).
q(94,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),94).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),95).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),96).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),97).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),98).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),99).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),100).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),101).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),102).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),103).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),104).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),105).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),106).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),107).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),108).
q(109,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),109).
