:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),1).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),3).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),4).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),6).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),7).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),8).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),10).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),11).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),14).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),15).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),16).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),17).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),18).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),19).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),20).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),22).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),23).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),24).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),25).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),26).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),27).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),28).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),31).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),35).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),37).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),40).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),41).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),42).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),44).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),45).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),47).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),48).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),49).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),50).
q(51,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',hallway)]),51).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),52).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),53).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),54).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),55).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),56).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),57).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),58).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),59).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),60).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),61).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),63).
q(64,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),64).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),66).
q(67,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),67).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),68).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),69).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),70).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),71).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),72).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),74).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),75).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),76).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),78).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),79).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),80).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),81).
q(82,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),82).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),83).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),84).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),85).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),86).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),87).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),88).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),90).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),91).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),92).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),93).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),94).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),95).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),96).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),97).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),98).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),99).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),100).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),101).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),102).
q(103,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),103).
