:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),1).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),2).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),6).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),7).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),8).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),9).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),10).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),11).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),15).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),16).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),17).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),18).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),19).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),21).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),22).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),23).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),24).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),26).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),27).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),28).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),29).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),30).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),31).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),32).
q(33,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),35).
q(36,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),36).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),37).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),38).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),39).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),40).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),41).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),42).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),46).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),48).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),49).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),50).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),52).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),53).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),54).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),55).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),58).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),59).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),60).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),62).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),63).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),66).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),67).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),69).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),70).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),71).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),72).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),75).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),80).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),81).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),82).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),83).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),84).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),85).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),86).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),87).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),88).
q(89,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),90).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),91).
q(92,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),92).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),93).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),94).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),95).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),96).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),97).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),98).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),99).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),100).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),101).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),102).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),103).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),104).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),105).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),106).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),107).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),108).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),109).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),110).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),111).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),112).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),113).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),114).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),115).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),116).
q(117,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',hallway)]),117).
