:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),3).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),5).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),6).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),8).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),10).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),15).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),16).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),17).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),18).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),19).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),21).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),22).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),23).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),24).
q(25,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),25).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),26).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),28).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),29).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),30).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),31).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),32).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),33).
q(34,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),34).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),35).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),37).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),40).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),41).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),42).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),43).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),45).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),46).
q(47,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),47).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),48).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),49).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),50).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),51).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),52).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),53).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),54).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),55).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),56).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),57).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),58).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),60).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),61).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),62).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),63).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),64).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),66).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),67).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),68).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),72).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),73).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),76).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),77).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),78).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),79).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),80).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),81).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),82).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),83).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),84).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),85).
q(86,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),86).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),87).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),88).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),90).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),92).
q(93,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),93).
