:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),1).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),3).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),4).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),5).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),9).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),10).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),11).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),14).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),15).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),16).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),17).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),18).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),19).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),20).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),21).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),22).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),23).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),24).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),26).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),27).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),28).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),29).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),30).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),32).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),34).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),35).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),36).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),37).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),39).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),40).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),42).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),43).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),46).
q(47,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),47).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),48).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),49).
q(50,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),50).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),51).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),52).
q(53,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),53).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),54).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),55).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),58).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),59).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),60).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),61).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),63).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),67).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),69).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),70).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),71).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),72).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),73).
q(74,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),74).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),75).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),76).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),78).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),79).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),80).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),81).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),82).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),83).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),84).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),85).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),86).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),87).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),88).
q(89,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),89).
