:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),4).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),5).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),8).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),9).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),10).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),11).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),12).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),13).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),14).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),15).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),16).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),17).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),18).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),19).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),20).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),21).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),22).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),23).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),24).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),25).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),26).
q(27,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),28).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),29).
q(30,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),30).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),32).
q(33,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),33).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),34).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),35).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),37).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),38).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),39).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),40).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),41).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),42).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),45).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),47).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),48).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),49).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),50).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),51).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),52).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),53).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),54).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),55).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),56).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),57).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),58).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),59).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),60).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),61).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),63).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),68).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),69).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),72).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),73).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),74).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),75).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),76).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),77).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),78).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),80).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),81).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),82).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),83).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),84).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),85).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),86).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),87).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),88).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),90).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),91).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),92).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),93).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),94).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),95).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),96).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),97).
q(98,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),98).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),99).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),100).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),101).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),102).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),103).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),104).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),105).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),106).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),107).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),108).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),109).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),110).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),111).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),112).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),113).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),114).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),115).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),116).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),117).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),118).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),119).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),120).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),121).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),122).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),123).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),124).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),125).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),126).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),127).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),128).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),129).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),130).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),131).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),132).
q(133,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),133).
