:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),1).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),7).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),9).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),10).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),12).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),13).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),15).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),16).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),17).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),18).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),19).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),20).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),23).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),24).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),25).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),28).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),29).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),30).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),34).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),35).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),37).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),38).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),39).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),40).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),41).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),42).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),43).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),45).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),46).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),47).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),48).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),49).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),50).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),51).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),52).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),53).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),54).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),56).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),57).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),58).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),59).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),60).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),61).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),62).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),63).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),64).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),66).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),67).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),68).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),70).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),71).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),72).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),73).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),75).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),76).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),78).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),79).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),80).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),81).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),82).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),83).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),84).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),85).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),86).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),87).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),88).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),89).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),90).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),92).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),93).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),94).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),95).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),96).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),97).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),98).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),99).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),100).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),101).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),102).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),103).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),104).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),105).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),106).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),107).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),108).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),109).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),110).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),111).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),112).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),113).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),114).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),115).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),116).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),117).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),118).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),119).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),120).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),121).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),122).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),123).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),124).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),125).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),126).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),127).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),128).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),129).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),130).
q(131,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),131).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),132).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),133).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),134).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),135).
q(136,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),136).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),137).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),138).
q(139,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),139).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),140).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),141).
q(142,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),142).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),143).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),144).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),145).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),146).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),147).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),148).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),149).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),150).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),151).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),152).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),153).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),154).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),155).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),156).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),157).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),158).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),159).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),160).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),161).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),162).
q(163,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),163).
