:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),1).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),2).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),3).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),4).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),7).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),8).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),9).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),14).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),15).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),16).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),17).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),19).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),21).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),22).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),23).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),24).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),25).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),27).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),28).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),29).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),30).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),33).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),34).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),35).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),37).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),38).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),39).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),40).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),41).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),42).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),43).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),45).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),46).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),49).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),50).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),52).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),53).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),54).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),55).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),56).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),57).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),58).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),59).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),60).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),61).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),62).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),63).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),64).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),65).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),68).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),70).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),72).
q(73,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),73).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),74).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),75).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),76).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),77).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),78).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),80).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),81).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),82).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),83).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),84).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),85).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),86).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),87).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),88).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),89).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),90).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),91).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),92).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),93).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),94).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),95).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),96).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),97).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),98).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),99).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),100).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),101).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),102).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),103).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),104).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),105).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),106).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),107).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),108).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),109).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),110).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),111).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),112).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),113).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),114).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),115).
q(116,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),116).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),117).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),118).
q(119,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),119).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),120).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),121).
q(122,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),122).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),123).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),124).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),125).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),126).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),127).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),128).
q(129,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),129).
