:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),1).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),2).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),3).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),5).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),6).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),8).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),9).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),10).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),15).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),16).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),17).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),18).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),20).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),23).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),24).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),25).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),26).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),27).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),28).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),29).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),30).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),33).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),34).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),35).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),37).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),39).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),40).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),41).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),43).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),44).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),45).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),46).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),48).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),49).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),50).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),52).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),53).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),54).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),55).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),56).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),58).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),59).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),60).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),62).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),65).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),66).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),67).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),68).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),69).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),70).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),72).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),74).
q(75,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),75).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),77).
q(78,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),78).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),79).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),80).
q(81,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),81).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),82).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),83).
q(84,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),84).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),85).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),86).
q(87,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),87).
