:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),1).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),2).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),3).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),5).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),6).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),7).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),10).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),11).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),13).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),14).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),15).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),16).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),17).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),18).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),19).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),20).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),21).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),23).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),24).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),25).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),28).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),29).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),30).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),32).
q(33,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),33).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),34).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),35).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),36).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),37).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),39).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),40).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),42).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),43).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),44).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),45).
q(46,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),46).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),47).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),49).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),50).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),52).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),53).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),54).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),56).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),57).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),58).
q(59,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),59).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),60).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),61).
q(62,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),62).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),64).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),67).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),68).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),69).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),71).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),74).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),75).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),78).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),79).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),80).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),81).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),82).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),83).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),84).
q(85,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),85).
