:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),1).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),2).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),3).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),4).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),6).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),7).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),9).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),10).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),11).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),13).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),14).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),15).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),16).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),17).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),20).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),21).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),22).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),23).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),24).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),25).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),26).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),27).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),28).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),29).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),33).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),35).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),36).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),38).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),39).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),40).
q(41,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),41).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),42).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),43).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),44).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),45).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),46).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),48).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),49).
q(50,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),50).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),52).
q(53,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),53).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),54).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),58).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),60).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),62).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),66).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),67).
q(68,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),68).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),69).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),70).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),71).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),72).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),73).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),75).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),76).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),77).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),78).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),79).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),80).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),81).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),82).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),83).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),84).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),85).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),86).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),87).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),88).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),89).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),90).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),91).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),92).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),93).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),94).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),95).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),96).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),97).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),98).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),99).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),100).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),101).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),102).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),103).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),104).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),105).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),106).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),107).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),108).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),109).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),110).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),111).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),112).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),113).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),114).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),115).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),116).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),117).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),118).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),119).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),120).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),121).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),122).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),123).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),124).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),125).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),126).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),127).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),128).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),129).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),130).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),131).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),132).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),133).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),134).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),135).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),136).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),137).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),138).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),139).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),140).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),141).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),142).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),143).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),144).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),145).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),146).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),147).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),148).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),149).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),150).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),151).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),152).
q(153,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),153).
