:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),4).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),6).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),9).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),10).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),12).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),15).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),16).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),17).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),18).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),19).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),20).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),21).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),22).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),23).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),24).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),26).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),28).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),29).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),33).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),34).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),35).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),37).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),38).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),39).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),40).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),41).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),47).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),49).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),50).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),52).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),53).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),54).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),55).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),56).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),57).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),58).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),59).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),60).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),61).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),62).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),63).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),66).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),67).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),68).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),69).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),71).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),73).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),77).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),79).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),80).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),81).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),82).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),83).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),84).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),85).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),86).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),87).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),88).
q(89,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),90).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),91).
q(92,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),92).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),93).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),94).
q(95,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),95).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),96).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),97).
q(98,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),98).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),99).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),100).
q(101,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),101).
