:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),3).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),4).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),5).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),6).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),7).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),12).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),13).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),15).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),16).
q(17,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),17).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),18).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),19).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),21).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),22).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),23).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),24).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),25).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),26).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),28).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),30).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),32).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),34).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),35).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),36).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),37).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),39).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),41).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),42).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),43).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),44).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),45).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),48).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),49).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),50).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),52).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),53).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),54).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),55).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),57).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),58).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),59).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),60).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),61).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),62).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),63).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),66).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),68).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),69).
q(70,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),70).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),71).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),72).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),74).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),75).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),76).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),78).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),79).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),80).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),81).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),82).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),83).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),84).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),85).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),86).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),87).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),88).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),89).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),90).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),91).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),92).
q(93,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),93).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),94).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),95).
q(96,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),96).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),97).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),98).
q(99,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),99).
