:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),1).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),2).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),3).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),4).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),5).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),6).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),8).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),9).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),10).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),11).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),12).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),13).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),15).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),16).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),17).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),18).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),19).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),21).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),22).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),23).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),24).
q(25,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),25).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),27).
q(28,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),28).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),29).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),30).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),31).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),32).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),33).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),34).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),35).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),36).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),37).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),38).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),39).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),42).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),43).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),45).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),46).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),47).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),48).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),49).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),50).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),52).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),53).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),54).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),55).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),56).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),57).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),58).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),59).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),60).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),61).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),62).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),63).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),65).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),66).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),67).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),68).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),69).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),70).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),71).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),72).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),77).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),80).
q(81,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),81).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),82).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),83).
q(84,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),84).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),85).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),86).
q(87,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',hallway)]),87).
