:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),1).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),2).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),3).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),4).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),5).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),6).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),7).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),8).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),9).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),10).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),14).
q(15,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),15).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),16).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),17).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),18).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),19).
q(20,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),21).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),22).
q(23,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),23).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),24).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),25).
q(26,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),26).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),27).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),28).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),31).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),32).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),35).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),36).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),37).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),38).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),39).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),40).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),42).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),43).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),44).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),46).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),47).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),48).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),49).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),50).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),51).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),52).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),53).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),54).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),55).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),57).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),58).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),59).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),60).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),61).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),62).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),63).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),67).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),68).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),69).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),70).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),71).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),74).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),75).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),76).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),77).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),78).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),80).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),81).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),82).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),83).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),84).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),85).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),86).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),87).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),88).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),89).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),90).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),91).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),92).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),93).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),94).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),95).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),96).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),97).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),98).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),99).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),100).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),101).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),102).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),103).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),104).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),105).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),106).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),107).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),108).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),109).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),110).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),111).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),112).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),113).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),114).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),115).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),116).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),117).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),118).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),119).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),120).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),121).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),122).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),123).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),124).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),125).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),126).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),127).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),128).
q(129,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),129).
