:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),2).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),3).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),4).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),8).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),9).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),10).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),11).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),12).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),13).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),15).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),16).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),17).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),18).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),19).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),22).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),23).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),24).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),26).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),27).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),28).
q(29,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),30).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),31).
q(32,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),32).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),33).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),34).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),35).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),37).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),39).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),40).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),41).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),42).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),44).
q(45,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),46).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),47).
q(48,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),48).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),49).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),50).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),51).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),52).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),53).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),56).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),58).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),60).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),63).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),64).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),65).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),66).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),67).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),68).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),69).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),71).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),72).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),73).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),74).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),75).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),76).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),78).
q(79,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),79).
