:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),1).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),3).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),4).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),6).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),7).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),8).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),9).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),10).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),11).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),15).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),16).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),17).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),18).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),19).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),20).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),22).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),23).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),24).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),25).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),26).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),27).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),28).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),30).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),31).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),33).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),34).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),35).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),36).
q(37,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),37).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),38).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),39).
q(40,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),40).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),41).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),42).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),44).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),46).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),47).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),49).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),50).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),52).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),53).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),54).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),55).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),56).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),57).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),58).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),59).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),60).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),61).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),63).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),65).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),66).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),67).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),68).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),69).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),70).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),71).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),73).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),75).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),77).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),79).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),80).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),81).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),82).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),83).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),84).
q(85,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',kitchen)]),85).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),86).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),87).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),88).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),89).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),90).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),91).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),92).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),93).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),94).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),95).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),96).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),97).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),98).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),99).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),100).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),101).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),102).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),103).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),104).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),105).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),106).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),107).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),108).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),109).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),110).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),111).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),112).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),113).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),114).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),115).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),116).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),117).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),118).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),119).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),120).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),121).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),122).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),123).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),124).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),125).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),126).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),127).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),128).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),129).
q(130,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),130).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),131).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),132).
q(133,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',hallway)]),133).
