:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),1).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),2).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),3).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),4).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),5).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),6).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),7).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),9).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),11).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),13).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),14).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),15).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),16).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),17).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),18).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),19).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),21).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),22).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),23).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),24).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),25).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),26).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),27).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),28).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),29).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),30).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),32).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),33).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),34).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),35).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),36).
q(37,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',hallway)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),39).
q(40,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),40).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),41).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),42).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),43).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),44).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),45).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),46).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),47).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),48).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),49).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),50).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),52).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),53).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),54).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),55).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),56).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),57).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),58).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),59).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),60).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),61).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),62).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),63).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),64).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),65).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),66).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),68).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),69).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),70).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),71).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),72).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),74).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),75).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),76).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),77).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),79).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),80).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),81).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),82).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),83).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),84).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),85).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),86).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),87).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),88).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),89).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),90).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),91).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),92).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),93).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),94).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),95).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),96).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),97).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),98).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),99).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),100).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),101).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),102).
q(103,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),103).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),104).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),105).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),106).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),107).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),108).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),109).
q(110,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),110).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),111).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),112).
q(113,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',kitchen)]),113).
