:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),1).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),2).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),3).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),4).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),5).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),6).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),7).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),8).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),9).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),10).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),13).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),14).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),15).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),16).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),17).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),19).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),20).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),21).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),22).
q(23,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),23).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),24).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),25).
q(26,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),26).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),27).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),28).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),29).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),30).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),33).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),34).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),35).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),36).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),37).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),38).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),39).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),41).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),42).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),45).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),46).
q(47,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),47).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),48).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),49).
q(50,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),50).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),52).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),53).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),54).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),55).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),56).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),58).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),60).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),61).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),62).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),68).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),69).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),71).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),72).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),73).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),75).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),76).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),77).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),79).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),80).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),81).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),82).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),83).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),84).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),85).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),86).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),87).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),88).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),89).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),90).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),91).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),92).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),93).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),94).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),95).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),96).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),97).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),98).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),99).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),100).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),101).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),102).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),103).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),104).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),105).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),106).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),107).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),108).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),109).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),110).
q(111,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),111).
