:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),1).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),3).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),4).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),6).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),8).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),13).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),14).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),15).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),16).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),17).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),18).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),19).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),21).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),23).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),24).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),28).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),34).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),35).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),36).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),37).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),38).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),39).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),40).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),41).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),42).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),43).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),44).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),45).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),46).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),47).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),49).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),50).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),51).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),52).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),53).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),55).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),56).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),58).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),59).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),60).
q(61,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),61).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),62).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),63).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),64).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),67).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),69).
q(70,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),70).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),72).
q(73,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),73).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),74).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),75).
q(76,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),77).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),78).
q(79,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),79).
