:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),1).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),2).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),6).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),10).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),11).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),15).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),16).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),17).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),18).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),19).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),20).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),21).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),23).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),24).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),25).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),26).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),27).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),28).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),29).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),30).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),32).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),33).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),34).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),35).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),36).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),37).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),38).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),39).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),40).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),42).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),43).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),44).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),45).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),46).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),48).
q(49,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),49).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),50).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),52).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),53).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),54).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),55).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),56).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),57).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),58).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),59).
q(60,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),60).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),61).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),62).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),64).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),66).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),67).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),70).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),71).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),72).
q(73,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),73).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),75).
q(76,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),77).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),78).
q(79,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),79).
