:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),1).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),3).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),4).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),5).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),6).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),10).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),11).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),12).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),15).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),16).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),17).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),18).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),19).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),20).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),21).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),22).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),23).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),24).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),25).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),27).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),28).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),29).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),31).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),32).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),34).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),35).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),36).
q(37,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),37).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),39).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),40).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),41).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),42).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),43).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),45).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),46).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),47).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),48).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),49).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),50).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),51).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),52).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),53).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),54).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),55).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),56).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),57).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),58).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),59).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),60).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),61).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),62).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),64).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),65).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),67).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),68).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),71).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),72).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),73).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),75).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),76).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),77).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),79).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),80).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),81).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),82).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),83).
q(84,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),84).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),85).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),86).
q(87,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),87).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),88).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),89).
q(90,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),90).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),92).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),93).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),94).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),95).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),96).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),97).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),98).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),99).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),100).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),101).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),102).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),103).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),104).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),105).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),106).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),107).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),108).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),109).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),110).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),111).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),112).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),113).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),114).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),115).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),116).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),117).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),118).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),119).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),120).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),121).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),122).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),123).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),124).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),125).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),126).
q(127,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),127).
