:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),2).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),3).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),4).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),6).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),7).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),9).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),10).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),11).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),13).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),15).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),16).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),17).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),18).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),19).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),20).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),21).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),22).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),23).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),24).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),25).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),26).
q(27,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',hallway)]),27).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),28).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),30).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),32).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),33).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),35).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),36).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),37).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),40).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),41).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),42).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),43).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),45).
q(46,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),47).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),48).
q(49,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),49).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),50).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),51).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),52).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),53).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),55).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),56).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),58).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),59).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),60).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),61).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),62).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),63).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),64).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),65).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),67).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),68).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),69).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),72).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),74).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),75).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),76).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),77).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),78).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),79).
q(80,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),80).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),81).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),82).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),83).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),84).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),85).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),86).
q(87,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),87).
