:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),1).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),2).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),3).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),6).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),7).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),8).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),9).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),10).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),12).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),15).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),16).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),17).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),18).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),20).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),21).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),22).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),23).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),24).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),25).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),26).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),27).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),28).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),29).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),31).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),32).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),33).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),34).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),35).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),36).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),38).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),41).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),42).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),45).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),46).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),47).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),48).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),49).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),50).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),51).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),52).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),53).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),54).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),55).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),56).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),58).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),59).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),60).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),64).
q(65,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),65).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),67).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),68).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),69).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),70).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),71).
q(72,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),72).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),74).
q(75,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),77).
q(78,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),78).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),79).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),80).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),81).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),82).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),83).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),84).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),85).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),86).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),87).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),88).
q(89,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),89).
