:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),1).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),5).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),6).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),7).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),8).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),9).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),10).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),14).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),15).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),16).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),17).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),20).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),21).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),24).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),25).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),26).
q(27,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),28).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),29).
q(30,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),31).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),34).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),35).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),37).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),39).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),40).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),41).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),45).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),46).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),47).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),48).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),49).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),50).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),51).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),52).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),53).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),58).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),59).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),60).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),62).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),64).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),66).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),69).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),72).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),75).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),77).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),78).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),79).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),80).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),81).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),82).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),83).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),84).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),85).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),86).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),87).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),88).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),89).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),90).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),91).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),92).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),93).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),94).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),95).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),96).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),97).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),98).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),99).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),100).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),101).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),102).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),103).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),104).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),105).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),106).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),107).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),108).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),109).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),110).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),111).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),112).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),113).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),114).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),115).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),116).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),117).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),118).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),119).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),120).
q(121,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),121).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),122).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),123).
q(124,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),124).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),125).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),126).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),127).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),128).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),129).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),130).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),131).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),132).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),133).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),134).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),135).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),136).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),137).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),138).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),139).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),140).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),141).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),142).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),143).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),144).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),145).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),146).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),147).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),148).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),149).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),150).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),151).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),152).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),153).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),154).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),155).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),156).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),157).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),158).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),159).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),160).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),161).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),162).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),163).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),164).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),165).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),166).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),167).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),168).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),169).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),170).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),171).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),172).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),173).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),174).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),175).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),176).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),177).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),178).
q(179,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),179).
