:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),1).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),2).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),3).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),4).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),5).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),9).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),10).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),11).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),14).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),15).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),16).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),17).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),18).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),19).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),20).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),21).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),22).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),24).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),25).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),26).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),27).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),28).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),29).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),31).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),32).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),34).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),35).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),37).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),39).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),40).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),41).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),42).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),43).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),45).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),46).
q(47,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),49).
q(50,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),50).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),51).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),52).
q(53,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),53).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),55).
q(56,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),56).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),57).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),58).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),60).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),61).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),62).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),63).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),65).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),67).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),68).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),69).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),70).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),72).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),73).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),74).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),77).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),78).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),79).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),80).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),81).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),82).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),83).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),84).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),85).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),86).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),87).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),88).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),90).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),91).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),92).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),93).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),94).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),95).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),96).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),97).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),98).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),99).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),100).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),101).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),102).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),103).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),104).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),105).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),106).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),107).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),108).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),109).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),110).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),111).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),112).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),113).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),114).
q(115,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),115).
