:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),4).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),5).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),6).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),8).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),9).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),10).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),11).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),14).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),15).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),16).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),17).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),19).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),21).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),22).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),23).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),24).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),25).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),26).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),27).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),28).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),29).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),32).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),34).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),35).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),38).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),40).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),42).
q(43,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),45).
q(46,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),46).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),47).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),48).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),49).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),50).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),51).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),52).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),53).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),54).
q(55,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),58).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),59).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),60).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),61).
q(62,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),62).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),63).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),64).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),67).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),68).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),69).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),70).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),71).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),73).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),74).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),75).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),76).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),77).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),79).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),80).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),81).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),82).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),83).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),84).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),85).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),86).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),87).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),88).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),89).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),90).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),91).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),92).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),93).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),94).
q(95,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),95).
