:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),1).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),2).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),3).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),6).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),10).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),13).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),15).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),16).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),17).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),19).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),21).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),23).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),24).
q(25,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),25).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),26).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),27).
q(28,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),28).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),29).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),30).
q(31,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),31).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),33).
q(34,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),34).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),35).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),36).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),37).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),38).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),39).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),40).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),41).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),42).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),46).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),47).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),48).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),49).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),50).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),51).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),52).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),53).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),54).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),55).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),56).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),57).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),58).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),59).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),60).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),61).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),63).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),65).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),67).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),68).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),69).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),70).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),71).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),72).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),73).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),75).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),76).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),77).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),79).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),80).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),81).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),82).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),83).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),84).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),85).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),86).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),87).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),88).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),90).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),91).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),92).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),93).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),94).
q(95,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),95).
