:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),1).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),2).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),3).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),4).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),5).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),6).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),9).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),10).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),11).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),12).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),15).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),16).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),17).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),18).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),19).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),20).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),23).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),24).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),25).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),26).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),28).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),29).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),31).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),32).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),34).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),35).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),36).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),37).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),40).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),41).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),44).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),46).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),47).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),48).
q(49,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),49).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),50).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),52).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),53).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),55).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),56).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),57).
q(58,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),58).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),59).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),60).
q(61,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),61).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),63).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),66).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),67).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),68).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),69).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),71).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),72).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),79).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),80).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),81).
q(82,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),82).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),83).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),84).
q(85,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),85).
