:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),1).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),2).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),3).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),6).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),7).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),10).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),12).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),13).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),15).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),16).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),17).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),18).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),19).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),21).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),22).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),24).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),25).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),26).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),27).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),28).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),29).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),30).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),32).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),33).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),34).
q(35,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),35).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),36).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),38).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),39).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),40).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),41).
q(42,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),43).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),46).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),47).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),48).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),49).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),50).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),52).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),53).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),54).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),55).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),56).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),57).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),58).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),59).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),60).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),61).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),62).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),63).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),65).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),66).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),67).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),69).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),70).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),72).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),73).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),74).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),76).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),78).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),79).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),80).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),81).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),82).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),83).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),84).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),85).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),86).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),87).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),88).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),90).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),92).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),93).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),94).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),95).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),96).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),97).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),98).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),99).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),100).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),101).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),102).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),103).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),104).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),105).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),106).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),107).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),108).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),109).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),110).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),111).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),112).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),113).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),114).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),115).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),116).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),117).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),118).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),119).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),120).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),121).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),122).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),123).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),124).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),125).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),126).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),127).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),128).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),129).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),130).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),131).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),132).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),133).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),134).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),135).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),136).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),137).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),138).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),139).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),140).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),141).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),142).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),143).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),144).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),145).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),146).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),147).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),148).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),149).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),150).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),151).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),152).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),153).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),154).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),155).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),156).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),157).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),158).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),159).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),160).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),161).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),162).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),163).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),164).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),165).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),166).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),167).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),168).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),169).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),170).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),171).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),172).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),173).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),174).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),175).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),176).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),177).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),178).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),179).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),180).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),181).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),182).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),183).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),184).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),185).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),186).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),187).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),188).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),189).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),190).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),191).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),192).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),193).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),194).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),195).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),196).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),197).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),198).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),199).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),200).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),201).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),202).
q(203,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),203).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),204).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),205).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),206).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),207).
q(208,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),208).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),209).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),210).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),211).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),212).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),213).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),214).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),215).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),216).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),217).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),218).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),219).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),220).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),221).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),222).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),223).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),224).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),225).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),226).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),227).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),228).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),229).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),230).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),231).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),232).
q(233,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',kitchen)]),233).
