:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),1).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),4).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),6).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),9).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),10).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),12).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),14).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),15).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),16).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),17).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),18).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),19).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),21).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),23).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),24).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),25).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),26).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),28).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),30).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),32).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),33).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),34).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),35).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),37).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),39).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),40).
q(41,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),41).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),43).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),46).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),47).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),48).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),49).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),50).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),52).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),53).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),55).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),56).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),57).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),58).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),59).
q(60,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),60).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),61).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),62).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),63).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),66).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),67).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),69).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),72).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),73).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),74).
q(75,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),75).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),77).
q(78,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),78).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),80).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),81).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),82).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),83).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),84).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),85).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),86).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),87).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),88).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),90).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),91).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),92).
q(93,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),93).
