:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),2).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),3).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),4).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),5).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),6).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),7).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),8).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),9).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),10).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),11).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),12).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),14).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),15).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),16).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),17).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),19).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),21).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),22).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),23).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),24).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),25).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),26).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),28).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),30).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),35).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),36).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),37).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),39).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),40).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),41).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),42).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),47).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),48).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),49).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),50).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),51).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),52).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),53).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),54).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),55).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),56).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),57).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),58).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),59).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),60).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),61).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),63).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),64).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),66).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),69).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),70).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),71).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),72).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),73).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),74).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),75).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),76).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),78).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),79).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),80).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),81).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),82).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),83).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),84).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),85).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),86).
q(87,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),87).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),88).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),89).
q(90,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),90).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),92).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),93).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),94).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),95).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),96).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),97).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),98).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),99).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),100).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),101).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),102).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),103).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),104).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),105).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),106).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),107).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),108).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),109).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),110).
q(111,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),111).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),112).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),113).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),114).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),115).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),116).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),117).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),118).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),119).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),120).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),121).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),122).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),123).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),124).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),125).
q(126,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),126).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),127).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),128).
q(129,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),129).
