:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),1).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),2).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),3).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),5).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),6).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),8).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),10).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),13).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),14).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),15).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),16).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),17).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),18).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),19).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),21).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),22).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),23).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),24).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),25).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),26).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),27).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),28).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),29).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),30).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),31).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),32).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),33).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),35).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),37).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),38).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),39).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),40).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),42).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),46).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),47).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),48).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),49).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),50).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),51).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),52).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),53).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),54).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),55).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),58).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),59).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),60).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),61).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),62).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),64).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),66).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),68).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),69).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),71).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),72).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),74).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),75).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),79).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),80).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),81).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),82).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),83).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),84).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),85).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),86).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),87).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),88).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),89).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),90).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),91).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),92).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),93).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),94).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),95).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),96).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),97).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),98).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),99).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),100).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),101).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),102).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),103).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),104).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),105).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),106).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),107).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),108).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),109).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),110).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),111).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),112).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),113).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),114).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),115).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),116).
q(117,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),117).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),118).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),119).
q(120,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),120).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),121).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),122).
q(123,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),123).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),124).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),125).
q(126,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),126).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),127).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),128).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),129).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),130).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),131).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),132).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),133).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),134).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),135).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),136).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),137).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),138).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),139).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),140).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),141).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),142).
q(143,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),143).
