:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),1).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),3).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),6).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),7).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),9).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),10).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),11).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),14).
q(15,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),15).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),16).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),17).
q(18,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),19).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),20).
q(21,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),22).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),23).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),24).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),25).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),26).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),28).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),29).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),30).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),33).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),34).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),35).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),36).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),38).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),39).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),40).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),42).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),43).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),45).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),46).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),47).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),48).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),49).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),50).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),51).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),52).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),53).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),54).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),55).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),56).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),57).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),58).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),59).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),60).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),61).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),62).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),63).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),65).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),66).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),67).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),68).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),70).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),72).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),75).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),77).
q(78,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),78).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),79).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),80).
q(81,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),81).
