:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),1).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),4).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),6).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),7).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),8).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),9).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),10).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),11).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),15).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),16).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),17).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),18).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),19).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),20).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),21).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),22).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),24).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),27).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),28).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),31).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),33).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),34).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),35).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),36).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),38).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),39).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),40).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),41).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),42).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),43).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),46).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),47).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),48).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),49).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),50).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),52).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),53).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),55).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),58).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),60).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),61).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),62).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),63).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),64).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),65).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),66).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),68).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),69).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),70).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),71).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),72).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),73).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),74).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),75).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),76).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),78).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),80).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),81).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),82).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),83).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),84).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),85).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),86).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),87).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),88).
q(89,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),89).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),90).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),92).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),93).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),94).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),95).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),96).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),97).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),98).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),99).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),100).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),101).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),102).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),103).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),104).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),105).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),106).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),107).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),108).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),109).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),110).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),111).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),112).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),113).
q(114,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),114).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),115).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),116).
q(117,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),117).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),118).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),119).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),120).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),121).
q(122,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),122).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),123).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),124).
q(125,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),125).
