:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),1).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),2).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),3).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),5).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),6).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),7).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),8).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),9).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),10).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),11).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),12).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),13).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),14).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),15).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),16).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),17).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),18).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),20).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),21).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),22).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),23).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),24).
q(25,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),25).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),26).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),28).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),29).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),31).
q(32,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),33).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),34).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),35).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),37).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),38).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),39).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),41).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),42).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),43).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),45).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),46).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),48).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),49).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),50).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),51).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),52).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),53).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),54).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),55).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),57).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),58).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),59).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),60).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),61).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),62).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),66).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),67).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),68).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),69).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),70).
q(71,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),71).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),73).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),75).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),76).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),78).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),79).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),80).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),81).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),82).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),83).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),84).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),85).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),86).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),87).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),88).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),89).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),90).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),91).
q(92,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),92).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),93).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),94).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),95).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),96).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),97).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),98).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),99).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),100).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),101).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),102).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),103).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),104).
q(105,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),105).
