:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),3).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),4).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),6).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),7).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),8).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),9).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),12).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),15).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),16).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),17).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),18).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),19).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),20).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),21).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),22).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),23).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),24).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),25).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),26).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),28).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),29).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),31).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),33).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),34).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),35).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),36).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),37).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),40).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),46).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),48).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),49).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),50).
q(51,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),52).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),53).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),54).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),55).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),58).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),59).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),60).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),62).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),66).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),67).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),69).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),70).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),71).
q(72,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),72).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),73).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),74).
q(75,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),75).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),76).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),77).
q(78,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),80).
q(81,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),81).
