:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),7).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),8).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),9).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),10).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),11).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),14).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),15).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),16).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),17).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),19).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),21).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),22).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),24).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),25).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),26).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),27).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),28).
q(29,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),29).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),30).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),33).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),34).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),35).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),36).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),38).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),39).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),40).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),41).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),42).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),45).
q(46,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),46).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),47).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),48).
q(49,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),49).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),50).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),51).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),52).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),53).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),54).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),56).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),57).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),58).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),59).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),60).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),61).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),62).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),63).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),64).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),67).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),68).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),69).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),70).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),71).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),72).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),73).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),74).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),75).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),76).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),78).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),79).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),80).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),81).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),82).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),83).
q(84,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),84).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),85).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),86).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),87).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),88).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),89).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),90).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),92).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),93).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),94).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),95).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),96).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),97).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),98).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),99).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),100).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),101).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),102).
q(103,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),103).
