:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),3).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),8).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),11).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),14).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),15).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),16).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),17).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),18).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),19).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),21).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),22).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),23).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),24).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),25).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),26).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),27).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),28).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),29).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),31).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),33).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),34).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),35).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),36).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),39).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),40).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),41).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),43).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),44).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),46).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),48).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),49).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),50).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),52).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),53).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),54).
q(55,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),55).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),56).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),57).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),58).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),59).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),60).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),62).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),63).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),64).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),65).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),66).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),68).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),69).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),70).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),71).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),72).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),74).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),75).
q(76,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),76).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),78).
q(79,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),79).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),80).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),81).
q(82,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),82).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),83).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),84).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),85).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),86).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),87).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),88).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),89).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),90).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),91).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),92).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),93).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),94).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),95).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),96).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),97).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),98).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),99).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),100).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),101).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),102).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),103).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),104).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),105).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),106).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),107).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),108).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),109).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),110).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),111).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),112).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),113).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),114).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),115).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),116).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),117).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),118).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),119).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),120).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),121).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),122).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),123).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),124).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),125).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),126).
q(127,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),127).
