:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),1).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),3).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),4).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),6).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),7).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),8).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),10).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),11).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),12).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),14).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),15).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),16).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),17).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),18).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),19).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),20).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),21).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),22).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),23).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),24).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),25).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),26).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),27).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),28).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),29).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),30).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),32).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),33).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),34).
q(35,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),35).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),37).
q(38,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),38).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),39).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),40).
q(41,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),41).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),42).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),43).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),44).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),45).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),46).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),48).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),49).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),50).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),51).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),52).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),53).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),54).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),55).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),56).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),57).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),58).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),59).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),60).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),62).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),65).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),67).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),68).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),69).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),70).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),71).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),72).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),75).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),76).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),78).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),79).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),80).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),81).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),82).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),83).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),84).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),85).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),86).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),87).
q(88,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),88).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),89).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),90).
q(91,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),91).
