:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),2).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),6).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),7).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),10).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),12).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),13).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),14).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),15).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),16).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),17).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),18).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),19).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),20).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),21).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),22).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),23).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),24).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),28).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),29).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),31).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),34).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),35).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),37).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),39).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),40).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),42).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),44).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),45).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),48).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),49).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),50).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),52).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),53).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),54).
q(55,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),55).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),56).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),57).
q(58,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),58).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),60).
q(61,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),61).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),62).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),63).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),68).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),69).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),71).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),72).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),73).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),74).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),75).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),77).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),78).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),80).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),81).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),82).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),83).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),84).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),85).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),86).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),87).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),88).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),89).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),90).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),91).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),92).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),93).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),94).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),95).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),96).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),97).
q(98,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),98).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),99).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),100).
q(101,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),101).
