:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),1).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),2).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),5).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),6).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),7).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),8).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),9).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),10).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),14).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),15).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),16).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),17).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),19).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),20).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),21).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),22).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),23).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),24).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),25).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),26).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),28).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),29).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),30).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),31).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),32).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),34).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),35).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),37).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),38).
q(39,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),39).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),40).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),41).
q(42,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),42).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),43).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),44).
q(45,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),45).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),46).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),47).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),48).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),49).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),50).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),52).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),53).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),54).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),56).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),57).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),58).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),59).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),60).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),61).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),62).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),63).
q(64,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',kitchen)]),64).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),65).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),67).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),68).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),69).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),72).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),73).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),75).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),76).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),77).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),78).
q(79,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),79).
