:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),1).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),2).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),3).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),4).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),6).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),7).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),8).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),10).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),11).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),12).
q(13,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),15).
q(16,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),16).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),17).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),18).
q(19,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),19).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),20).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),21).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),22).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),23).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),24).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),26).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),28).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),29).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),30).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),31).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),34).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),35).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),36).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),37).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),39).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),40).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),41).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),42).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),43).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),44).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),46).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),47).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),48).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),49).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),50).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),51).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),52).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),53).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),54).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),55).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),58).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),59).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),60).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),62).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),66).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),67).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),68).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),69).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),70).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),74).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),75).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),76).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),79).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),80).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),81).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),82).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),83).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),84).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),85).
q(86,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),86).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),87).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),88).
q(89,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),89).
