:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),1).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),2).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),3).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),4).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),5).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),7).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),10).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),11).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),12).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),13).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),14).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),15).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),16).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),17).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),18).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),21).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),22).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),24).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),28).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),29).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),30).
q(31,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),32).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),33).
q(34,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),34).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),35).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),36).
q(37,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),37).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),39).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),41).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),43).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),45).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),46).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),47).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),48).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),49).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),50).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),51).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),52).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),53).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),54).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),57).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),58).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),60).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),61).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),62).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),63).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),64).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),66).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),67).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),68).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),69).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),71).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),72).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),73).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),75).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),76).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),77).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),80).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),81).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),82).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),83).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),84).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),85).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),86).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),87).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),88).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),89).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),90).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),91).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),92).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),93).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),94).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),95).
q(96,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',kitchen)]),96).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),97).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),98).
q(99,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),99).
