:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),1).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),2).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),7).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),8).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),10).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),15).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),16).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),17).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),18).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),19).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),20).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),21).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),22).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),24).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),25).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),27).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),28).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),30).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),32).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),35).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),37).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),38).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),39).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),40).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),41).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),42).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),43).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),44).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),46).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),47).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),49).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),50).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),51).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),52).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),53).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),54).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),55).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),56).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),58).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),59).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),60).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),62).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),63).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),64).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),67).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),69).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),70).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),72).
q(73,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),74).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),76).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),77).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),78).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),79).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),80).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),81).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),82).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),83).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),84).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),85).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),86).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),87).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),88).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),89).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),90).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),92).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),93).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),94).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),95).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),96).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),97).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),98).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),99).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),100).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),101).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),102).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),103).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),104).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),105).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),106).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),107).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),108).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),109).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),110).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),111).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),112).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),113).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),114).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),115).
q(116,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),116).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),117).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),118).
q(119,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),119).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),120).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),121).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),122).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),123).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),124).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),125).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),126).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),127).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),128).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),129).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),130).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),131).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),132).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),133).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),134).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),135).
q(136,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),136).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),137).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),138).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),139).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),140).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),141).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),142).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),143).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),144).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),145).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),146).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),147).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),148).
q(149,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),149).
