:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),1).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),2).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),3).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),6).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),7).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),8).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),10).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),12).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),13).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),14).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),15).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),16).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),17).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),19).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),20).
q(21,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),21).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),22).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),23).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),24).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),25).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),28).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),29).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),32).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),33).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),34).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),35).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),36).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),37).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),39).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),41).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),45).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),46).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),48).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),49).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),50).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),52).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),53).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),54).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),55).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),56).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),58).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),59).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),60).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),61).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),62).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),63).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),64).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),65).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),66).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),67).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),68).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),71).
q(72,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),72).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),73).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),74).
q(75,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),75).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),76).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),77).
q(78,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),79).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),80).
q(81,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),81).
