:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),1).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),2).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),3).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),5).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),6).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),8).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),9).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),10).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),12).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),14).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),15).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),16).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),17).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),18).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),19).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),20).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),24).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),25).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),27).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),28).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),29).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),30).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),31).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),33).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),34).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),35).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),36).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),37).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),38).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),39).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),40).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),41).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),42).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),43).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),44).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),45).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),46).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),49).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),50).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),51).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),52).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),53).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),54).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),55).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),56).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),57).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),58).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),59).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),60).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),61).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),62).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),64).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),65).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),66).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),67).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),68).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),69).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),70).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),73).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),74).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),75).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),77).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),79).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),80).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),81).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),82).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),83).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),84).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),85).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),86).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),87).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),88).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),90).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),91).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),92).
q(93,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),93).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),94).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),95).
q(96,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),96).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),97).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),98).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),99).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),100).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),101).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),102).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),103).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),104).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),105).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),106).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),107).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),108).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),109).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),110).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),111).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),112).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),113).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),114).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),115).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),116).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),117).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),118).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),119).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),120).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),121).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),122).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),123).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),124).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),125).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),126).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),127).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),128).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),129).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),130).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),131).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),132).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),133).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),134).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),135).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),136).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),137).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),138).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),139).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),140).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),141).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),142).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),143).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),144).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),145).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),146).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),147).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),148).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),149).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),150).
q(151,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',kitchen)]),151).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),152).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),153).
q(154,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',hallway)]),154).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),155).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),156).
q(157,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),157).
