:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),2).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),3).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),4).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),5).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),6).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),7).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),8).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),9).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),10).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),11).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),14).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),15).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),16).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),17).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),18).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),19).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),20).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),22).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),23).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),24).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),25).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),26).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),27).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),28).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),29).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),32).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),33).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),34).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),35).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),37).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),41).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),42).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),43).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),44).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),45).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),46).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),47).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),48).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),49).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),50).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),51).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),52).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),53).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),54).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),55).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),56).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),57).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),58).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),59).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),60).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),61).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),62).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),64).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),65).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),66).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),67).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),68).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),69).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),70).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),71).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),72).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),75).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),76).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),77).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),78).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),79).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),80).
q(81,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),81).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),82).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),83).
q(84,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),84).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),85).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),86).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),87).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),88).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),89).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),90).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),91).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),92).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),93).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),94).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),95).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),96).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),97).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),98).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),99).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),100).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),101).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),102).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),103).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),104).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),105).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),106).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),107).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),108).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),109).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),110).
q(111,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),111).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),112).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),113).
q(114,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),114).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),115).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),116).
q(117,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),117).
