:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),1).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),2).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),3).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),4).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),5).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),6).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),7).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),8).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),9).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),10).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),11).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),12).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),14).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),15).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),16).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),17).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),18).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),20).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),21).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),22).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),24).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),25).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),26).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),27).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),28).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),29).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),30).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),31).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),35).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),36).
q(37,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),37).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),38).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),39).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),41).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),42).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),45).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),46).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),48).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),49).
q(50,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),50).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),52).
q(53,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),53).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),54).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),55).
q(56,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',garden)]),56).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),57).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),58).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),59).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),60).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),62).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),64).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),66).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),67).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),68).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),70).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),71).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),72).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),73).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),75).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),77).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),80).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),81).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),82).
q(83,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),83).
