:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),2).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),3).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),4).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),5).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),9).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),11).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),13).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),14).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),15).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),16).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),17).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),18).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),20).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),21).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),22).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),23).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),24).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),25).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),26).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),27).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),28).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),29).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),34).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),35).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),37).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),39).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),41).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),42).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),43).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),44).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),45).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),47).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),48).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),49).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),50).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),51).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),52).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),53).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),54).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),55).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),56).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),57).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),58).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),59).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),60).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),61).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),62).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),63).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),67).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),68).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),69).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),71).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),72).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),73).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),76).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),77).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),79).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),80).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),81).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),82).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),83).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),84).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),85).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),86).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),87).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),88).
q(89,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),89).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),90).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),91).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),92).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),93).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),94).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),95).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),96).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),97).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),98).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),99).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),100).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),101).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),102).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),103).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),104).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),105).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),106).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),107).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),108).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),109).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),110).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),111).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),112).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),113).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),114).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),115).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),116).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),117).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),118).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),119).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),120).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),121).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),122).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),123).
q(124,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),124).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),125).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),126).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),127).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),128).
q(129,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),129).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),130).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),131).
q(132,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),132).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),133).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),134).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),135).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),136).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),137).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),138).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),139).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),140).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),141).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),142).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),143).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),144).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),145).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),146).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),147).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),148).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),149).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),150).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),151).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),152).
q(153,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),153).
