:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),1).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),2).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),3).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),4).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),6).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),7).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),9).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),11).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),14).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),15).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),16).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),17).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),18).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),19).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),20).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),21).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),22).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),24).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),25).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),26).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),27).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),28).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),29).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),30).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),31).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),32).
q(33,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),33).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),34).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),35).
q(36,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),36).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),37).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),38).
q(39,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),39).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),40).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),41).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),42).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),43).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),46).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),47).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),48).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),49).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),50).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),51).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),52).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),53).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),54).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),55).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),56).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),58).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),59).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),60).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),61).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),62).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),64).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),67).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),70).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),72).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),75).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),77).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),78).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),79).
q(80,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),80).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),81).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),82).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),83).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),84).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),85).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),86).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),87).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),88).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),90).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),92).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),93).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),94).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),95).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),96).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),97).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),98).
q(99,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',hallway)]),99).
