:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),1).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),3).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),6).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),7).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),8).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),9).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),11).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),12).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),13).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),14).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),15).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),16).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),17).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),18).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),19).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),21).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),22).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),23).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),24).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),25).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),26).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),28).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),29).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),30).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),31).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),34).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),35).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),37).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),39).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),40).
q(41,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),41).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),43).
q(44,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),44).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),46).
q(47,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),47).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),49).
q(50,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),50).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),51).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),52).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),53).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),55).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),56).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),58).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),60).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),62).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),64).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),68).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),72).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),73).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),75).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),76).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),78).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),80).
q(81,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),81).
