:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),1).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),4).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),6).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),7).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),8).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),9).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),10).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),11).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),12).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),13).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),15).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),16).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),17).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),18).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),20).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),21).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),22).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),24).
q(25,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),25).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),26).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),28).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),29).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),30).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),31).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),32).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),33).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),34).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),35).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),37).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),39).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),41).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),42).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),43).
q(44,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),44).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),45).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),46).
q(47,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),47).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),49).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),50).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),52).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),53).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),54).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),55).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),57).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),58).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),59).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),60).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),61).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),62).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),63).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),64).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),65).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),67).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),68).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),69).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),72).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),78).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),79).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),80).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),81).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),82).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),83).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),84).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),85).
q(86,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bathroom)]),86).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),87).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),88).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),89).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),90).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),91).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),92).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),93).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),94).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),95).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),96).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),97).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),98).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),99).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),100).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),101).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),102).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),103).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),104).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),105).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),106).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),107).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),108).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),109).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),110).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),111).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),112).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),113).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),114).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),115).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),116).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),117).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),118).
q(119,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),119).
