:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),1).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),3).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),5).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),6).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),7).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),8).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),9).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),10).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),11).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),12).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),13).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),14).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),15).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),16).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),17).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),18).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),19).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),20).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),21).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),22).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),23).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),24).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),25).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),26).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),27).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),28).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),29).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),30).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),31).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),32).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),34).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),35).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),36).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),37).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),38).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),39).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),40).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),41).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),42).
q(43,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),43).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),45).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),46).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),47).
q(48,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),48).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),49).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),50).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),51).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),52).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),53).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),54).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),55).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),56).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),58).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),59).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),60).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),61).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),62).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),63).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),64).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),66).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),67).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),69).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),70).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),71).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),73).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),75).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),76).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),77).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),79).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),80).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),81).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),82).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),83).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),84).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),85).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),86).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),87).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),88).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),89).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),90).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),92).
q(93,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',kitchen)]),93).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),94).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),95).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),96).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),97).
q(98,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),98).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),99).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),100).
q(101,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),101).
