:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),1).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),2).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),3).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),4).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),6).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),8).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),9).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),10).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),14).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),15).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),16).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),17).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),18).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),19).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),20).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),21).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),22).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),23).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),24).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),25).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),26).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),27).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),28).
q(29,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),29).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),30).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),31).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),32).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),33).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),34).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),35).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),36).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),37).
q(38,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),38).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),39).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),40).
q(41,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),41).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),42).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),43).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),45).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),47).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),48).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),49).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),50).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),51).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),52).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),53).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),54).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),55).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),56).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),57).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),58).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),60).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),61).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),62).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),64).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),66).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),67).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),69).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),70).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),72).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),73).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),78).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),79).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),80).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),81).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),82).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),83).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),84).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),85).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),86).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),87).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),88).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),89).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),90).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),91).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),92).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),93).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),94).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),95).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),96).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),97).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),98).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),99).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),100).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),101).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),102).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),103).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),104).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),105).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),106).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),107).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),108).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),109).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),110).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),111).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),112).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),113).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),114).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),115).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),116).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),117).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),118).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),119).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),120).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),121).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),122).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),123).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),124).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),125).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),126).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),127).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),128).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),129).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),130).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),131).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),132).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),133).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),134).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),135).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),136).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),137).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),138).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),139).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),140).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),141).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),142).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),143).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),144).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),145).
q(146,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',kitchen)]),146).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),147).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),148).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),149).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),150).
q(151,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bathroom)]),151).
