:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),1).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),2).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),3).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),4).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),5).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),6).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),7).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),8).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),9).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),10).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),11).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),12).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),13).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),14).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),15).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),16).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),17).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),18).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),19).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),20).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),21).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),22).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),23).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),24).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),25).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),26).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),27).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),28).
q(29,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),29).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),30).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),31).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),32).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),33).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),34).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),35).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),36).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),37).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),39).
q(40,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),41).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),42).
q(43,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',office)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),44).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),46).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),47).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),48).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),49).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),50).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),51).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),52).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),53).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),54).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),57).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),58).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),60).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),61).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),62).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),65).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),66).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),67).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),68).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),69).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),70).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),71).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),72).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),76).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),77).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),78).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),80).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),81).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),82).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),83).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),84).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),85).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),86).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),87).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),88).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),89).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),90).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),91).
q(92,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',garden)]),92).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),93).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),94).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),95).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),96).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),97).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),98).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),99).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),100).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),101).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),102).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),103).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),104).
q(105,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',kitchen)]),105).
