:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),1).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),3).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),4).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),5).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),6).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),7).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),8).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),9).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),12).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),13).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),14).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),15).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),16).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),17).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),18).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),19).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),20).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),21).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),22).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),24).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),25).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),26).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),27).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),28).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),29).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),30).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),32).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),34).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),35).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),36).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),37).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),39).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),41).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),42).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),43).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),44).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),45).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),46).
q(47,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),47).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),49).
q(50,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),50).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),51).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),52).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),53).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),54).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),55).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),56).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),57).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),58).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),59).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),60).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),61).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),62).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),63).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),65).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),66).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),67).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),68).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),69).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),70).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),71).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),72).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),73).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),75).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),77).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),78).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),79).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),80).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),81).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),82).
q(83,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',garden)]),83).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),84).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),85).
q(86,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',hallway)]),86).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),87).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),88).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),89).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),90).
q(91,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',hallway)]),91).
