:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),1).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),2).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),3).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),5).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),6).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),7).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),9).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),10).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),11).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),12).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),14).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),15).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),16).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),17).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),18).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),19).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),20).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),21).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),22).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),23).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),24).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),25).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),26).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),27).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),28).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),29).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),30).
q(31,Answer) :- questionedAt(frame('Located',[fe('Entity',football),fe('Place',Answer),fe('Before_place',bedroom)]),31).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),32).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),33).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),34).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),35).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),36).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),38).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),39).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),40).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),41).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',apple)]),42).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',apple)]),43).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),44).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),45).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),46).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),47).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),48).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),49).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),50).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),51).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),52).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),53).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),54).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),55).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),57).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),58).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),59).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),60).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),61).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),62).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),63).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),64).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),65).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),66).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),67).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),68).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),69).
q(70,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),70).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),71).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),72).
q(73,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),73).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),74).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),75).
q(76,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',office)]),76).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),77).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),78).
q(79,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',hallway)]),79).
