:- multifile frame/2.

happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),1).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),2).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),3).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),4).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),5).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),6).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),7).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),8).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),9).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),10).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),11).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),12).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),13).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),15).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),16).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),17).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),18).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),19).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),20).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),21).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),22).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),23).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),24).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),25).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),26).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),27).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),28).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),29).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',milk)]),30).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),32).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),33).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bedroom)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',hallway)]),35).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),36).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),37).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),38).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),39).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),40).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),41).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',milk)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),43).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),44).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),45).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),47).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),49).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),50).
q(51,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),51).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),52).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),53).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),54).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),55).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),56).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),58).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),59).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),60).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),61).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),62).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),63).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),64).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),65).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),66).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',football)]),67).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),68).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),69).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),70).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',football)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),72).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',milk)]),73).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),75).
q(76,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),76).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',garden)]),77).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',football)]),78).
q(79,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),79).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',milk)]),80).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),81).
q(82,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),82).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),83).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',football)]),84).
q(85,Answer) :- questionedAt(frame('Located',[fe('Entity',milk),fe('Place',Answer),fe('Before_place',bedroom)]),85).
