:- multifile frame/2.

happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),1).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),2).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),3).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),4).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',football)]),5).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),6).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),7).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',football)]),8).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',bathroom)]),9).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),10).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),11).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),12).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),13).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),14).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bedroom)]),15).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),16).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',apple)]),17).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),18).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),19).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),20).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',hallway)]),21).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),22).
happensAt(frame('Obtain',[fe('Person',daniel),fe('Theme',milk)]),23).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',hallway)]),24).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),25).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',apple)]),26).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),27).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),28).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),29).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),30).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),31).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),32).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',apple)]),33).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),34).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),35).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',bathroom)]),36).
happensAt(frame('Discard',[fe('Person',daniel),fe('Theme',milk)]),37).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),38).
happensAt(frame('Travel',[fe('Person',john),fe('Place',garden)]),39).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),40).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),41).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),42).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),43).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),44).
happensAt(frame('Obtain',[fe('Person',sandra),fe('Theme',milk)]),45).
happensAt(frame('Discard',[fe('Person',sandra),fe('Theme',milk)]),46).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',office)]),47).
happensAt(frame('Travel',[fe('Person',daniel),fe('Place',kitchen)]),48).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bedroom)]),49).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),50).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),51).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',garden)]),52).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bedroom)]),53).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',office)]),54).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),55).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),56).
happensAt(frame('Travel',[fe('Person',john),fe('Place',bathroom)]),57).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',bathroom)]),58).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),59).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',apple)]),60).
q(61,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bathroom)]),61).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',kitchen)]),62).
happensAt(frame('Obtain',[fe('Person',john),fe('Theme',football)]),63).
q(64,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',bedroom)]),64).
happensAt(frame('Obtain',[fe('Person',mary),fe('Theme',apple)]),65).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),66).
happensAt(frame('Travel',[fe('Person',sandra),fe('Place',hallway)]),67).
happensAt(frame('Travel',[fe('Person',john),fe('Place',kitchen)]),68).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',office)]),69).
happensAt(frame('Discard',[fe('Person',mary),fe('Theme',apple)]),70).
q(71,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),71).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',garden)]),72).
happensAt(frame('Discard',[fe('Person',john),fe('Theme',football)]),73).
q(74,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),74).
happensAt(frame('Travel',[fe('Person',mary),fe('Place',kitchen)]),75).
happensAt(frame('Travel',[fe('Person',john),fe('Place',office)]),76).
q(77,Answer) :- questionedAt(frame('Located',[fe('Entity',apple),fe('Place',Answer),fe('Before_place',office)]),77).
